### ISSUE TITLE
Key error in download

### ISSUE THREAD

**Issue by flysaiah** [vn-ki/anime-downloader#11]
Hi--I just stumbled onto this tool today; I'm trying to download episode 22 from the show Nichijou and I'm erroring out with this error:

```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader', 'console_scripts', 'anime')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/isaiahmayerchak/anime-downloader/anime_downloader/cli.py", line 104, in dl
    format=file_format)
  File "/Users/isaiahmayerchak/anime-downloader/anime_downloader/sites/anime.py", line 150, in download
    total_size = int(r.headers['Content-length'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```

I'm looking into it myself and will make a PR if I find a solution, but thought I'd post it here in case someone more familiar with the codebase sees this and instantly knows a quick fix

**Comment by vn-ki** [comment]
9anime updated it's api. We used their api to get the info about anime. This tool has to updated to reflect the change. For that I'll have to take a look at 9anime site. This is the same issue as #10.

Once I fix it, I will close this issue.
