### ISSUE TITLE
Cannot download from twist.moe

### ISSUE THREAD

**Issue by Aquafina-water-bottle** [vn-ki/anime-downloader#117]
**Describe the bug**

I simply cannot download from twist.moe. It seems to have something to do with "eu1.twist.moe" being an invalid name.

**To reproduce**

```
anime dl "https://twist.moe/a/ouran-koukou-host-club"
```

<details>
<summary>LOG</summary>

```INFO root: anime-downloader 3.6.2
DEBUG root: Platform: Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
DEBUG root: Python 3.6.7
INFO root: Extracting episode info from page
INFO root: Found anime: ouran-koukou-host-club
INFO root: Downloading to /home/austin/pgc/prog/Other/temp
DEBUG root: Extracting stream info of id: https://eu1.twist.moe/anime/highschoolhostclub/[a-s]_ouran_high_school_host_club_-_01_-_starting_today,_you_are_a_host__rs2_[1080p_bd-rip][0C161243].mp4
DEBUG root: Sources :
INFO root: Downloading ouran-koukou-host-club-1
INFO root: ./ouran-koukou-host-club/ouran-koukou-host-club_1.mp4
ERROR urllib3.connection: Certificate did not match expected hostname: eu1.twist.moe. Certificate: {'subject': ((('commonName', 'twist.moe'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', "Let's Encrypt Authority X3"),)), 'version': 3, 'serialNumber': '04371B972502DBF0310E83793A306E6E0257', 'notBefore': 'Nov 29 03:49:20 2018 GMT', 'notAfter': 'Feb 27 03:49:20 2019 GMT', 'subjectAltName': (('DNS', 'twist.moe'), ('DNS', 'www.twist.moe')), 'OCSP': ('http://ocsp.int-x3.letsencrypt.org',), 'caIssuers': ('http://cert.int-x3.letsencrypt.org/',)}
Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/austin/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/austin/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/austin/.local/lib/python3.6/site-packages/urllib3/connection.py", line 364, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/home/austin/.local/lib/python3.6/site-packages/urllib3/connection.py", line 374, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3.6/ssl.py", line 327, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'eu1.twist.moe' doesn't match either of 'twist.moe', 'www.twist.moe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/austin/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/austin/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/austin/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='eu1.twist.moe', port=443): Max retries exceeded with url: /anime/highschoolhostclub/[a-s]_ouran_high_school_host_club_-_01_-_starting_today,_you_are_a_host__rs2_[1080p_bd-rip][0C161243].mp4 (Caused by SSLError(CertificateError("hostname 'eu1.twist.moe' doesn't match either of 'twist.moe', 'www.twist.moe'",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/austin/.local/bin/anime", line 11, in <module>
    sys.exit(cli())
  File "/home/austin/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/austin/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/austin/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/austin/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/austin/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/austin/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/austin/.local/lib/python3.6/site-packages/anime_downloader/cli.py", line 146, in dl
    range_size=chunk_size)
  File "/home/austin/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 183, in download
    path, force, range_size=range_size)
  File "/home/austin/.local/lib/python3.6/site-packages/anime_downloader/downloader/base_downloader.py", line 23, in __init__
    r = session.get_session().get(self.url, stream=True)
  File "/home/austin/.local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/austin/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/austin/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/austin/.local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='eu1.twist.moe', port=443): Max retries exceeded with url: /anime/highschoolhostclub/[a-s]_ouran_high_school_host_club_-_01_-_starting_today,_you_are_a_host__rs2_[1080p_bd-rip][0C161243].mp4 (Caused by SSLError(CertificateError("hostname 'eu1.twist.moe' doesn't match either of 'twist.moe', 'www.twist.moe'",),))

```

**Comment by rehtlaw** [comment]
try the same command, but with `--disable-ssl`, since it seems like their SSL certificate only counts for the main website, not their CDNs

**Comment by Aquafina-water-bottle** [comment]
Works like a charm, thanks!
