### ISSUE TITLE
Kisscartoon Error

### ISSUE THREAD

**Issue by robzombie91** [vn-ki/anime-downloader#118]
**Describe the bug**
Downloading a episode from kisscartoon throws out an error

**To reproduce**
anime dl --provider kisscartoon family

```

```

<details>
<summary>LOG</summary>

```
C:\Users\rob>anime dl -e 01 --provider kisscartoon --log-level DEBUG family
INFO root: anime-downloader 3.6.2
DEBUG root: Platform: Windows-10-10.0.17134-SP0
DEBUG root: Python 3.7.2
DEBUG root: Result url: https://kisscartoon.su/Search/?s=family&s=family
DEBUG root: Family Guy Season 17
DEBUG root: Family Guy Season 17 Episode 009...
DEBUG root: Family Guy Season 16
DEBUG root: Family Guy Season 16 Episode 020...
DEBUG root: Family Guy Season 15
DEBUG root: Family Guy Season 15 Episode 020...
DEBUG root: Family Guy Season 14
DEBUG root: Family Guy Season 10
DEBUG root: Family Guy Season 13
DEBUG root: Family Guy Season 11
DEBUG root: Family Guy Season 12
DEBUG root: F Is For Family Season 3
DEBUG root: Monster Family
DEBUG root: Monster Family (2017)
DEBUG root: F Is For Family Season 2
DEBUG root: F Is For Family Season 2 Episode 010
DEBUG root: A Flintstone Family Christmas
DEBUG root: The Proud Family
DEBUG root: F is for Family
DEBUG root: Family Guy Season 8
DEBUG root: The Family-Ness
DEBUG root: The Moo Family Holiday Hoe-Down
DEBUG root: A Special Valentine with the Family
DEBUG root: The Care Bears
DEBUG root: Festival of Family Classics
DEBUG root: Family Dog
DEBUG root: Family Guy Season 4
DEBUG root: Laugh It Up, Fuzzball: The Family
DEBUG root: Family Guy: Up Late with Stewie
DEBUG root: The Goode Family
DEBUG root: Family Guy Season 3
DEBUG root: Family Guy Season 9
DEBUG root: The Addams Family (1973)
DEBUG root: A Muppet Family Christmas
DEBUG root: A Family Circus Christmas
DEBUG root: Family
DEBUG root: The Swan Princess: A Royal Family
DEBUG root: Duckman: Private Dick/Family Man
DEBUG root: The Addams Family (1992)
DEBUG root: The Proud Family Movie
DEBUG root: Family Guy Presents Stewie Griffin
DEBUG root: Family Guy Season 7
DEBUG root: Family Guy Season 2
DEBUG root: Family Guy Season 5
DEBUG root: Family Guy Season 6
DEBUG root: Family Guy Season 1
 1: Family Guy Season 17
 2: Family Guy Season 17 Episode 009...
 3: Family Guy Season 16
 4: Family Guy Season 16 Episode 020...
 5: Family Guy Season 15
 6: Family Guy Season 15 Episode 020...
 7: Family Guy Season 14
 8: Family Guy Season 10
 9: Family Guy Season 13
10: Family Guy Season 11
11: Family Guy Season 12
12: F Is For Family Season 3
13: Monster Family
14: Monster Family (2017)
15: F Is For Family Season 2
16: F Is For Family Season 2 Episode 010
17: A Flintstone Family Christmas
18: The Proud Family
19: F is for Family
20: Family Guy Season 8
21: The Family-Ness
22: The Moo Family Holiday Hoe-Down
23: A Special Valentine with the Family
24: The Care Bears
25: Festival of Family Classics
26: Family Dog

Enter the anime no:  [1]: 1
INFO root: Selected Family Guy Season 17
INFO root: Extracting episode info from page
DEBUG root: EPISODE IDS: length: 9, ids: ['https://kisscartoon.su/Cartoon/Family-Guy-Season-17/Episode-001-Married-With-Cancer?id=81513', 'https://kisscartoon.su/Cartoon/Family-Guy-Season-17/Episode-002-Dead-Dog-Walking?id=81592', 'https://kisscartoon.su/Cartoon/Family-Guy-Season-17/Episode-003-Pal-Stewie?id=81665', 'https://kisscartoon.su/Cartoon/Family-Guy-Season-17/Episode-004-Big-Trouble-in-Little-Quahog?id=81738', 'https://kisscartoon.su/Cartoon/Family-Guy-Season-17/Episode-005-Regarding-Carter?id=81923', 'https://kisscartoon.su/Cartoon/Family-Guy-Season-17/Episode-006-Stand-by-Meg?id=81957', 'https://kisscartoon.su/Cartoon/Family-Guy-Season-17/Episode-007-The-Griffin-Winter-Games?id=82206', 'https://kisscartoon.su/Cartoon/Family-Guy-Season-17/Episode-008-Con-Heiress?id=82375', 'https://kisscartoon.su/Cartoon/Family-Guy-Season-17/Episode-009-Pawtucket-Pete?id=82451']
INFO root: Found anime: Family Guy Season 17
DEBUG root: Extracting stream info of id: https://kisscartoon.su/Cartoon/Family-Guy-Season-17/Episode-001-Married-With-Cancer?id=81513
Traceback (most recent call last):
  File "c:\users\rob\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\rob\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rob\AppData\Local\Programs\Python\Python37\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\cli.py", line 117, in dl
    animes = util.parse_ep_str(anime, episode_range)
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\util.py", line 120, in parse_ep_str
    episodes.append(anime[int(episode_grammar) - 1])
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 78, in __getitem__
    ep_no=ep_id[0])
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 122, in __init__
    self.get_data()
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 162, in get_data
    self._sources = self._get_sources()
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\kisscartoon.py", line 29, in _get_sources
    url = res.json()['value']
  File "c:\users\rob\appdata\local\programs\python\python37\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\users\rob\appdata\local\programs\python\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\rob\appdata\local\programs\python\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\rob\appdata\local\programs\python\python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by vn-ki** [comment]
Still happening?

**Comment by meyerovb** [comment]
if its still happening try "pip install cfscrape -U"

**Comment by vn-ki** [comment]
Closing due to no response

**Comment by robzombie91** [comment]
i tried pming you on discord but got no response.
