### ISSUE TITLE
Animepahe is not working

### ISSUE THREAD

**Issue by kougamishinyaa** [vn-ki/anime-downloader#120]
cant download anything from animepahe.com......cant extract any url if i use -u command..
someother improvements also needed....the mp4upload server is no longer available at animepahe so set the server to kwik...getting the following error alltime
![screenshot 27](https://user-images.githubusercontent.com/46401062/50755577-42a68f00-127b-11e9-8b9c-fa129bf38e40.png)

**Comment by kougamishinyaa** [comment]
`Traceback (most recent call last):
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\Scripts\anime-script.py", line 11, in <module>
    load_entry_point('anime-downloader==3.6.2', 'console_scripts', 'anime')()
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\cli.py", line 125, in dl
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\anime.py", line 78, in __getitem__
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\anime.py", line 124, in __init__
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\extractors\base_extractor.py", line 26, in stream_url
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\extractors\base_extractor.py", line 38, in get_data
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\extractors\mp4upload.py", line 26, in _get_data
AttributeError: 'NoneType' object has no attribute 'groups'`

**Comment by kougamishinyaa** [comment]
> `Traceback (most recent call last): File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\Scripts\anime-script.py", line 11, in <module> load_entry_point('anime-downloader==3.6.2', 'console_scripts', 'anime')() File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__ return self.main(*args, **kwargs) File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main rv = self.invoke(ctx) File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params) File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke return callback(*args, **kwargs) File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\decorators.py", line 17, in new_func return f(get_current_context(), *args, **kwargs) File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\cli.py", line 125, in dl File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\anime.py", line 78, in __getitem__ File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\anime.py", line 124, in __init__ File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\extractors\base_extractor.py", line 26, in stream_url File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\extractors\base_extractor.py", line 38, in get_data File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\extractors\mp4upload.py", line 26, in _get_data AttributeError: 'NoneType' object has no attribute 'groups'`

**Comment by ngomile** [comment]
Hi there, what anime were you attempting to download? Recently there's been quite a crackdown on a lot of anime on mp4upload which is the main source the animepahe extractor happens to get the download links from. Since the error is occurring in the mp4upload extractor this holds true because I've experienced the same thing. 

The only solution apart from of course making the extractor handle errors better is to choose another site to get the anime or personally use animepahes kwik source. Since that usually seems to be free from being DMCA'd. I hope this helps. The extractor is still working, I just didn't make the error handling good for DMCA'd or incorrect links.

**Comment by kougamishinyaa** [comment]
Then how i can download from kwik server?
