### ISSUE TITLE
cant download from twist.moe Error : no module named 'winrandom'

### ISSUE THREAD

**Issue by kougamishinyaa** [vn-ki/anime-downloader#122]
i cant download from twist.moe .it is giving the following error
`E:\>anime dl assassination-classroom --provider twist.moe
[32manime[0m: anime-downloader 3.6.2
Traceback (most recent call last):
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\Scripts\anime-script.py", line 11, in <module>
    load_entry_point('anime-downloader==3.6.2', 'console_scripts', 'anime')()
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\cli.py", line 102, in dl
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\util.py", line 58, in search
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\init.py", line 21, in get_anime_class
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\twistmoe.py", line 1, in <module>
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pycrypto-2.6.1-py3.7-win32.egg\Crypto\Random\__init__.py", line 28, in <module>
    from Crypto.Random import OSRNG
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pycrypto-2.6.1-py3.7-win32.egg\Crypto\Random\OSRNG\__init__.py", line 34, in <module>
    from Crypto.Random.OSRNG.nt import new
  File "C:\Users\Ahsan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pycrypto-2.6.1-py3.7-win32.egg\Crypto\Random\OSRNG\nt.py", line 28, in <module>
    import winrandom
ModuleNotFoundError: No module named 'winrandom'`
no command is working with twist.moe

**Comment by kougamishinyaa** [comment]
getting error 
`C:\Users\Ahsan>pip install winrandom
Collecting winrandom
  Downloading https://files.pythonhosted.org/packages/b8/db/b0a2e6b6600c8e00e1cf31e0cd95622283c31a380259dd5e0998201583d0/winrandom-1.2.zip
Installing collected packages: winrandom
  Running setup.py install for winrandom ... error
    Complete output from command c:\users\ahsan\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ahsan\\AppData\\Local\\Temp\\pip-install-zedpcb_g\\winrandom\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ahsan\AppData\Local\Temp\pip-record-i_cmwf1c\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Ahsan\AppData\Local\Temp\pip-install-zedpcb_g\winrandom\setup.py", line 43, in <module>
        ext_modules=[winrandom1])
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\command\build_ext.py", line 308, in run
        force=self.force)
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\cygwinccompiler.py", line 282, in __init__
        CygwinCCompiler.__init__ (self, verbose, dry_run, force)
      File "c:\users\ahsan\appdata\local\programs\python\python37-32\lib\distutils\cygwinccompiler.py", line 126, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: '>=' not supported between instances of 'NoneType' and 'str'

    ----------------------------------------
Command "c:\users\ahsan\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ahsan\\AppData\\Local\\Temp\\pip-install-zedpcb_g\\winrandom\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ahsan\AppData\Local\Temp\pip-record-i_cmwf1c\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Ahsan\AppData\Local\Temp\pip-install-zedpcb_g\winrandom\`
