### ISSUE TITLE
AnimePahe Kwik Issues

### ISSUE THREAD

**Issue by 29ayush** [vn-ki/anime-downloader#124]
Nowdays all anime of animepahe are hosted on kwik rather than mp4upload, how can I download them.

**Comment by rehtlaw** [comment]
afaik kwik isn't supported at all right now, so someone would have to write an extractor for it.

**Comment by 29ayush** [comment]
https://github.com/vn-ki/anime-downloader/pull/127

**Comment by kougamishinyaa** [comment]
How to use ??? #127

**Comment by rehtlaw** [comment]
@kougamishinyaa you could either pull his fork with pip or wait until it's merged and then pull the latest commit from the main repository with the command in the README here.

**Comment by kougamishinyaa** [comment]
@rehtlaw the 1st command not working its giving
```
C:\Windows\system32>pip install -U git+https://github.com/29ayush/anime-downloader.git#egg=anime-downloader[cloudflare]
Collecting anime-downloader[cloudflare] from git+https://github.com/29ayush/anime-downloader.git#egg=anime-downloader[cloudflare]
  Cloning https://github.com/29ayush/anime-downloader.git to c:\users\ahsan\appdata\local\temp\pip-install-dl4uws_r\anime-downloader
  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/29ayush/anime-downloader.git C:\Users\Ahsan\AppData\Local\Temp\pip-install-dl4uws_r\anime-downloader
Cannot find command 'git' - do you have 'git' installed and in your PATH?```

**Comment by rehtlaw** [comment]
As the error message is saying, you need to have git installed. Since you are on windows, I'd suggest that you get [Git Bash](https://git-scm.com/download/win) and try to run the command with it (I'd also recommend using this terminal over the regular cmd.exe in general).

**Comment by rehtlaw** [comment]
Shouldn't this be closed now though? Since anything else is pretty much about the PR, which should be discussed in the PR itself.

**Comment by kougamishinyaa** [comment]
a;so error in git bash
```Kougami Shinya@KougamiShinya MINGW32 ~                                                                                                          $ pip install -U git+https://github.com/29ayush/anime-downloader.git#egg=anime-d                                                                ownloader[cloudflare]                                                                                                                           Collecting anime-downloader[cloudflare] from git+https://github.com/29ayush/anim                                                                e-downloader.git#egg=anime-downloader[cloudflare]                                                                                                 Cloning https://github.com/29ayush/anime-downloader.git to c:\users\kougam~1\a                                                                ppdata\local\temp\pip-install-89rbf2l4\anime-downloader                                                                                         Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.6.0 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib \site-packages\beautifulsoup4-4.7.0-py3.7.egg (from anime-downloader[cloudflare]) (4.7.0)                                                       Requirement already satisfied, skipping upgrade: requests>=2.18.4 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site -packages\requests-2.21.0-py3.7.egg (from anime-downloader[cloudflare]) (2.21.0)                                                                Requirement already satisfied, skipping upgrade: Click>=6.7 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packa ges\click-7.0-py3.7.egg (from anime-downloader[cloudflare]) (7.0)                                                                               Requirement already satisfied, skipping upgrade: fuzzywuzzy>=0.16.0 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\si te-packages\fuzzywuzzy-0.17.0-py3.7.egg (from anime-downloader[cloudflare]) (0.17.0)                                                            Requirement already satisfied, skipping upgrade: cfscrape>=1.9.5 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site- packages (from anime-downloader[cloudflare]) (1.9.5)                                                                                            Requirement already satisfied, skipping upgrade: soupsieve>=1.2 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-p ackages\soupsieve-1.6.1-py3.7.egg (from beautifulsoup4>=4.6.0->anime-downloader[cloudflare]) (1.6.1)                                            Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\si te-packages\certifi-2018.11.29-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (2018.11.29)                                     Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib \site-packages\chardet-3.0.4-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (3.0.4)                                            Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-p ackages\idna-2.8-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (2.8)                                                          Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib \site-packages\urllib3-1.24.1-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (1.24.1)                                          Installing collected packages: anime-downloader                                                                                                   Found existing installation: anime-downloader 3.6.2                                                                                               Uninstalling anime-downloader-3.6.2:                                                                                                              Successfully uninstalled anime-downloader-3.6.2                                                                                             Running setup.py install for anime-downloader: started                                                                                            Running setup.py install for anime-downloader: finished with status 'done'                                                                  Successfully installed anime-downloader-3.6.2                                                                                                   Traceback (most recent call last):                                                                                                                File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main                           "__main__", mod_spec)                                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code                                      exec(code, run_globals)                                                                                                                       File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\Scripts\pip.exe\__main__.py", line 9, in                        File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\__init__.py", line 78, in main            return command.main(cmd_args)                                                                                                                 File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\cli\base_command.py", line 184, in ma in                                                                                                                                                  timeout=min(5, options.timeout)                                                                                                               File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\cli\base_command.py", line 79, in _bu ild_session                                                                                                                                         insecure_hosts=options.trusted_hosts,                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\download.py", line 337, in __init__       self.headers["User-Agent"] = user_agent()                                                                                                     File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\download.py", line 126, in user_agent     setuptools_version = get_installed_version("setuptools")                                                                                      File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\utils\misc.py", line 836, in get_inst alled_version                                                                                                                                       working_set = pkg_resources.WorkingSet()                                                                                                      File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 562, i n __init__                                                                                                                                          self.add_entry(entry)                                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 618, i n add_entry                                                                                                                                         for dist in find_distributions(entry, True):                                                                                                  File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1883,  in find_eggs_in_zip                                                                                                                                 if metadata.has_metadata('PKG-INFO'):                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1402,  in has_metadata                                                                                                                                     return self.egg_info and self._has(self._fn(self.egg_info, name))                                                                             File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1757,  in _has                                                                                                                                             return zip_path in self.zipinfo or zip_path in self._index()                                                                                  File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1634,  in zipinfo                                                                                                                                          return self._zip_manifests.load(self.loader.archive)                                                                                          File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1591,  in load                                                                                                                                             mtime = os.stat(path).st_mtime                                                                                                              FileNotFoundError: [WinError 2] The system cannot find the file specified: 'c:\\users\\kougami shinya\\appdata\\local\\programs\\python\\python 37-32\\lib\\site-packages\\anime_downloader-3.6.2-py3.7.egg'                                                                                                                                                                                                                                    Kougami Shinya@KougamiShinya MINGW32 ~                                                                                                          ownloader[cloudflare]https://github.com/29ayush/anime-downloader.git#egg=anime-do
--```

**Comment by kougamishinyaa** [comment]
error in git bash
```

Kougami Shinya@KougamiShinya MINGW32 ~                                                                                                          $ pip install -U git+https://github.com/29ayush/anime-downloader.git#egg=anime-d                                                                ownloader[cloudflare]                                                                                                                           Collecting anime-downloader[cloudflare] from git+https://github.com/29ayush/anim                                                                e-downloader.git#egg=anime-downloader[cloudflare]                                                                                                 Cloning https://github.com/29ayush/anime-downloader.git to c:\users\kougam~1\a                                                                ppdata\local\temp\pip-install-89rbf2l4\anime-downloader                                                                                         Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.6.0 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib \site-packages\beautifulsoup4-4.7.0-py3.7.egg (from anime-downloader[cloudflare]) (4.7.0)                                                       Requirement already satisfied, skipping upgrade: requests>=2.18.4 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site -packages\requests-2.21.0-py3.7.egg (from anime-downloader[cloudflare]) (2.21.0)                                                                Requirement already satisfied, skipping upgrade: Click>=6.7 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packa ges\click-7.0-py3.7.egg (from anime-downloader[cloudflare]) (7.0)                                                                               Requirement already satisfied, skipping upgrade: fuzzywuzzy>=0.16.0 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\si te-packages\fuzzywuzzy-0.17.0-py3.7.egg (from anime-downloader[cloudflare]) (0.17.0)                                                            Requirement already satisfied, skipping upgrade: cfscrape>=1.9.5 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site- packages (from anime-downloader[cloudflare]) (1.9.5)                                                                                            Requirement already satisfied, skipping upgrade: soupsieve>=1.2 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-p ackages\soupsieve-1.6.1-py3.7.egg (from beautifulsoup4>=4.6.0->anime-downloader[cloudflare]) (1.6.1)                                            Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\si te-packages\certifi-2018.11.29-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (2018.11.29)                                     Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib \site-packages\chardet-3.0.4-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (3.0.4)                                            Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-p ackages\idna-2.8-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (2.8)                                                          Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib \site-packages\urllib3-1.24.1-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (1.24.1)                                          Installing collected packages: anime-downloader                                                                                                   Found existing installation: anime-downloader 3.6.2                                                                                               Uninstalling anime-downloader-3.6.2:                                                                                                              Successfully uninstalled anime-downloader-3.6.2                                                                                             Running setup.py install for anime-downloader: started                                                                                            Running setup.py install for anime-downloader: finished with status 'done'                                                                  Successfully installed anime-downloader-3.6.2                                                                                                   Traceback (most recent call last):                                                                                                                File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main                           "__main__", mod_spec)                                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code                                      exec(code, run_globals)                                                                                                                       File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\Scripts\pip.exe\__main__.py", line 9, in                        File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\__init__.py", line 78, in main            return command.main(cmd_args)                                                                                                                 File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\cli\base_command.py", line 184, in ma in                                                                                                                                                  timeout=min(5, options.timeout)                                                                                                               File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\cli\base_command.py", line 79, in _bu ild_session                                                                                                                                         insecure_hosts=options.trusted_hosts,                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\download.py", line 337, in __init__       self.headers["User-Agent"] = user_agent()                                                                                                     File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\download.py", line 126, in user_agent     setuptools_version = get_installed_version("setuptools")                                                                                      File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\utils\misc.py", line 836, in get_inst alled_version                                                                                                                                       working_set = pkg_resources.WorkingSet()                                                                                                      File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 562, i n __init__                                                                                                                                          self.add_entry(entry)                                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 618, i n add_entry                                                                                                                                         for dist in find_distributions(entry, True):                                                                                                  File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1883,  in find_eggs_in_zip                                                                                                                                 if metadata.has_metadata('PKG-INFO'):                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1402,  in has_metadata                                                                                                                                     return self.egg_info and self._has(self._fn(self.egg_info, name))                                                                             File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1757,  in _has                                                                                                                                             return zip_path in self.zipinfo or zip_path in self._index()                                                                                  File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1634,  in zipinfo                                                                                                                                          return self._zip_manifests.load(self.loader.archive)                                                                                          File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1591,  in load                                                                                                                                             mtime = os.stat(path).st_mtime                                                                                                              FileNotFoundError: [WinError 2] The system cannot find the file specified: 'c:\\users\\kougami shinya\\appdata\\local\\programs\\python\\python 37-32\\lib\\site-packages\\anime_downloader-3.6.2-py3.7.egg'                                                                                                                                                                                                                                    Kougami Shinya@KougamiShinya MINGW32 ~                                                                                                          ownloader[cloudflare]https://github.com/29ayush/anime-downloader.git#egg=anime-do
--

```

**Comment by kougamishinyaa** [comment]
error in git bash 
```Kougami Shinya@KougamiShinya MINGW32 ~                                                                                                          $ pip install -U git+https://github.com/29ayush/anime-downloader.git#egg=anime-d                                                                ownloader[cloudflare]                                                                                                                           Collecting anime-downloader[cloudflare] from git+https://github.com/29ayush/anim                                                                e-downloader.git#egg=anime-downloader[cloudflare]                                                                                                 Cloning https://github.com/29ayush/anime-downloader.git to c:\users\kougam~1\a                                                                ppdata\local\temp\pip-install-89rbf2l4\anime-downloader                                                                                         Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.6.0 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib \site-packages\beautifulsoup4-4.7.0-py3.7.egg (from anime-downloader[cloudflare]) (4.7.0)                                                       Requirement already satisfied, skipping upgrade: requests>=2.18.4 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site -packages\requests-2.21.0-py3.7.egg (from anime-downloader[cloudflare]) (2.21.0)                                                                Requirement already satisfied, skipping upgrade: Click>=6.7 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packa ges\click-7.0-py3.7.egg (from anime-downloader[cloudflare]) (7.0)                                                                               Requirement already satisfied, skipping upgrade: fuzzywuzzy>=0.16.0 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\si te-packages\fuzzywuzzy-0.17.0-py3.7.egg (from anime-downloader[cloudflare]) (0.17.0)                                                            Requirement already satisfied, skipping upgrade: cfscrape>=1.9.5 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site- packages (from anime-downloader[cloudflare]) (1.9.5)                                                                                            Requirement already satisfied, skipping upgrade: soupsieve>=1.2 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-p ackages\soupsieve-1.6.1-py3.7.egg (from beautifulsoup4>=4.6.0->anime-downloader[cloudflare]) (1.6.1)                                            Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\si te-packages\certifi-2018.11.29-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (2018.11.29)                                     Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib \site-packages\chardet-3.0.4-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (3.0.4)                                            Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-p ackages\idna-2.8-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (2.8)                                                          Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib \site-packages\urllib3-1.24.1-py3.7.egg (from requests>=2.18.4->anime-downloader[cloudflare]) (1.24.1)                                          Installing collected packages: anime-downloader                                                                                                   Found existing installation: anime-downloader 3.6.2                                                                                               Uninstalling anime-downloader-3.6.2:                                                                                                              Successfully uninstalled anime-downloader-3.6.2                                                                                             Running setup.py install for anime-downloader: started                                                                                            Running setup.py install for anime-downloader: finished with status 'done'                                                                  Successfully installed anime-downloader-3.6.2                                                                                                   Traceback (most recent call last):                                                                                                                File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main                           "__main__", mod_spec)                                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code                                      exec(code, run_globals)                                                                                                                       File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\Scripts\pip.exe\__main__.py", line 9, in                        File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\__init__.py", line 78, in main            return command.main(cmd_args)                                                                                                                 File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\cli\base_command.py", line 184, in ma in                                                                                                                                                  timeout=min(5, options.timeout)                                                                                                               File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\cli\base_command.py", line 79, in _bu ild_session                                                                                                                                         insecure_hosts=options.trusted_hosts,                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\download.py", line 337, in __init__       self.headers["User-Agent"] = user_agent()                                                                                                     File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\download.py", line 126, in user_agent     setuptools_version = get_installed_version("setuptools")                                                                                      File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\utils\misc.py", line 836, in get_inst alled_version                                                                                                                                       working_set = pkg_resources.WorkingSet()                                                                                                      File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 562, i n __init__                                                                                                                                          self.add_entry(entry)                                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 618, i n add_entry                                                                                                                                         for dist in find_distributions(entry, True):                                                                                                  File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1883,  in find_eggs_in_zip                                                                                                                                 if metadata.has_metadata('PKG-INFO'):                                                                                                         File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1402,  in has_metadata                                                                                                                                     return self.egg_info and self._has(self._fn(self.egg_info, name))                                                                             File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1757,  in _has                                                                                                                                             return zip_path in self.zipinfo or zip_path in self._index()                                                                                  File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1634,  in zipinfo                                                                                                                                          return self._zip_manifests.load(self.loader.archive)                                                                                          File "c:\users\kougami shinya\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1591,  in load                                                                                                                                             mtime = os.stat(path).st_mtime                                                                                                              FileNotFoundError: [WinError 2] The system cannot find the file specified: 'c:\\users\\kougami shinya\\appdata\\local\\programs\\python\\python 37-32\\lib\\site-packages\\anime_downloader-3.6.2-py3.7.egg' ```
