### ISSUE TITLE
cant download from masterani.me

### ISSUE THREAD

**Issue by kougamishinyaa** [vn-ki/anime-downloader#126]
After that animepahe is not working I switched to masterani.me but this is also giving a fucking error and dont download anything
`E:\>anime dl https://www.masterani.me/anime/info/746-amagi-brilliant-park -e7:13 --disable-ssl
[32manime[0m: anime-downloader 3.6.2
[32manime[0m: Extracting episode info from page
[32manime[0m: Found anime: Amagi Brilliant Park
Traceback (most recent call last):
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\Scripts\anime-script.py", line 11, in <module>
    load_entry_point('anime-downloader==3.6.2', 'console_scripts', 'anime')()
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\cli.py", line 117, in dl
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\util.py", line 117, in parse_ep_str
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\anime.py", line 78, in __getitem__
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\anime.py", line 122, in __init__
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\anime.py", line 162, in get_data
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\masterani.py", line 27, in _get_sources
TypeError: 'NoneType' object is not subscriptable`

**Comment by kougamishinyaa** [comment]
I tried alot with `ll DEBUG`  but getting the same error

**Comment by rehtlaw** [comment]
well `-ll DEBUG` gives you a more verbose output, so we can see if it gets stuck somewhere/doesn't find something. So I wanted you to post that output with the `DEBUG` log level

**Comment by kougamishinyaa** [comment]
Ok

**Comment by kougamishinyaa** [comment]
here what i got by `ll DEBUG`
`E:\>anime dl "https://www.masterani.me/anime/info/746-amagi-brilliant-park" -e 7:13 -ll DEBUG
INFO root: anime-downloader 3.6.2
DEBUG root: Platform: Windows-10-10.0.10240-SP0
DEBUG root: Python 3.7.2
INFO root: Extracting episode info from page
INFO root: Found anime: Amagi Brilliant Park
DEBUG root: Extracting stream info of id: https://www.masterani.me/anime/watch/746-amagi-brilliant-park/7
DEBUG root: [cfscrape] Calling https://www.masterani.me/anime/watch/746-amagi-brilliant-park/7`
`Traceback (most recent call last):`
`File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\Scripts\anime-script.py", line 11, in <module>
    load_entry_point('anime-downloader==3.6.2', 'console_scripts', 'anime')()
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click-7.0-py3.7.egg\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\cli.py", line 117, in dl
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\util.py", line 117, in parse_ep_str
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\anime.py", line 78, in __getitem__
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\anime.py", line 122, in __init__
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\anime.py", line 162, in get_data
  File "C:\Users\Kougami Shinya\AppData\Local\Programs\Python\Python37-32\lib\site-packages\anime_downloader-3.6.2-py3.7.egg\anime_downloader\sites\masterani.py", line 27, in _get_sources
TypeError: 'NoneType' object is not subscriptable`

**Comment by rehtlaw** [comment]
(and please, wrap the output in triple backticks, not single ones)

**Comment by kougamishinyaa** [comment]
(i did it but i guess i messed up)

**Comment by rehtlaw** [comment]
nope those are single quotes, 
```
triple quotes should look like this
```
`not like this`

**Comment by kougamishinyaa** [comment]
any solution how to fix this error?

**Comment by rehtlaw** [comment]
also make sure you can visit the site in your browser... I had it once where it wanted me to answer a recaptcha once i opened the site in a browser

**Comment by kougamishinyaa** [comment]
I visited the site also .....

**Comment by rehtlaw** [comment]
well can you also actually watch the video on the site itself, because i still have a feeling the script can't even get to the player

**Comment by kougamishinyaa** [comment]
Issue solved
By doing recaptcha and then after again copy the link it worked
BTW how can i download from kwik in animepahe

**Comment by kougamishinyaa** [comment]
Closing this issue bcoz the issue regarding kwik in animepahe is already opened
