### ISSUE TITLE
very specific(?) mp4upload error

### ISSUE THREAD

**Issue by rehtlaw** [vn-ki/anime-downloader#132]
**Describe the bug**

the extractor doesn't seem to be able to find the actual video file on the embedded mp4upload site [even tho it's definitely there](https://fred.moe/Eoy.png) and it has `video` in the name (which seems to be how the link is found)

**To reproduce**

```
anime dl 'https://www.masterani.me/anime/info/1792-rezero-kara-hajimeru-isekai-seikatsu' --disable-ssl -e 9:
```
I should also note that, at least for me, this only happened from the 9th episode on, all other 8 episodes downloaded just fine

<details>
<summary>LOG</summary>

cannot copy more of the logs, but every attempt at downloading an episode results in the same
```

DEBUG root: Domain: s1, Video ID: qsx7723gz3b4quuoyouugpchkiep7xfa5leb2zduxhz4y4pr3okpmw4a, Protocol: 282
DEBUG root: Title is ReZero_kara_Hajimeru_Isekai_Seikatsu_-_17_-_1080p
DEBUG root: Stream URL: https://s1.mp4upload.com:282/d/qsx7723gz3b4quuoyouugpchkiep7xfa5leb2zduxhz4y4pr3okpmw4a/ReZero_kara_Hajimeru_Isekai_Seikatsu_-_17_-_1080p.mp4
DEBUG root: Extracting stream info of id: https://www.masterani.me/anime/watch/1792-rezero-kara-hajimeru-isekai-seikatsu/18
DEBUG root: [cfscrape] Calling https://www.masterani.me/anime/watch/1792-rezero-kara-hajimeru-isekai-seikatsu/18
DEBUG root: Found sources [{'id': 265820, 'host_id': 1, 'embed_id': '4dy8cd17urn6', 'quality': 1080, 'type': 1, 'host': {'id': 1, 'name': 'MP4Upload', 'embed_prefix': 'https://mp4upload.com/embed-', 'embed_suffix': '.html'}}, {'id': 265672, 'host_id': 18, 'embed_id': 'rssadqqloollbrbn', 'quality': 1080, 'type': 1, 'host': {'id': 18, 'name': 'Streamango', 'embed_prefix': 'https://streamango.com/embed/', 'embed_suffix': None}}, {'id': 265647, 'host_id': 15, 'embed_id': 'LJiaQO9hl7M/ReZero_kara_Hajimeru_Isekai_Seikatsu_-_18_-_1080p.mp4', 'quality': 1080, 'type': 1, 'host': {'id': 15,
'name': 'Openload', 'embed_prefix': 'https://openload.co/embed/', 'embed_suffix': None}}, {'id': 265795, 'host_id': 1, 'embed_id': '0dtyavhtq6gn', 'quality': 480, 'type': 1, 'host': {'id': 1, 'name': 'MP4Upload', 'embed_prefix': 'https://mp4upload.com/embed-', 'embed_suffix': '.html'}}, {'id': 265720, 'host_id': 18, 'embed_id': 'dffqeflsfmrcsmfn', 'quality': 480, 'type': 1, 'host': {'id':
18, 'name': 'Streamango', 'embed_prefix': 'https://streamango.com/embed/', 'embed_suffix': None}}, {'id': 265770, 'host_id': 15, 'embed_id': 'BwKyIlHegsU/ReZero_kara_Hajimeru_Isekai_Seikatsu_-_18_-_480p.mp4', 'quality': 480, 'type': 1, 'host': {'id': 15, 'name': 'Openload', 'embed_prefix': 'https://openload.co/embed/', 'embed_suffix': None}}]. filtering...
DEBUG root: [('mp4upload', 'https://mp4upload.com/embed-4dy8cd17urn6.html')]
DEBUG root: Sources :
Traceback (most recent call last):
  File "/home/rehtlaw/.local/share/virtualenvs/anime-downloader-1cgG9WrQ/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader', 'console_scripts', 'anime')()
  File "/home/rehtlaw/.local/share/virtualenvs/anime-downloader-1cgG9WrQ/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rehtlaw/.local/share/virtualenvs/anime-downloader-1cgG9WrQ/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/rehtlaw/.local/share/virtualenvs/anime-downloader-1cgG9WrQ/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rehtlaw/.local/share/virtualenvs/anime-downloader-1cgG9WrQ/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rehtlaw/.local/share/virtualenvs/anime-downloader-1cgG9WrQ/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rehtlaw/.local/share/virtualenvs/anime-downloader-1cgG9WrQ/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rehtlaw/programming/anime-downloader/anime_downloader/cli.py", line 117, in dl
    animes = util.parse_ep_str(anime, episode_range)
  File "/home/rehtlaw/programming/anime-downloader/anime_downloader/util.py", line 117, in parse_ep_str
    for episode in split_anime(anime, episode_grammar):
  File "/home/rehtlaw/programming/anime-downloader/anime_downloader/sites/anime.py", line 78, in __getitem__
    ep_no=ep_id[0])
  File "/home/rehtlaw/programming/anime-downloader/anime_downloader/sites/anime.py", line 124, in __init__
    self.source().stream_url
  File "/home/rehtlaw/programming/anime-downloader/anime_downloader/extractors/base_extractor.py", line 26, in stream_url
    self.get_data()
  File "/home/rehtlaw/programming/anime-downloader/anime_downloader/extractors/base_extractor.py", line 38, in get_data
    data = self._get_data()
  File "/home/rehtlaw/programming/anime-downloader/anime_downloader/extractors/mp4upload.py", line 26, in _get_data
    domain, video_id, protocol = source_parts_re.match(mp4u_embed).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

```

**Comment by kougamishinyaa** [comment]
Its also happened to me just only for one episode ....when i was trying to download `Mo dao zu shi` the same error occurred on episode 8 even the ep was available....

**Comment by rehtlaw** [comment]
....pretty sure it had a 1080p option though, or at least 720p

Jan 28, 2019, 7:57 PM by notifications@github.com:

**Comment by MichaelDavidJohnson** [comment]
Your command works in 2020. Closing
