### ISSUE TITLE
Issue with animepahe

### ISSUE THREAD

**Issue by moonpen** [vn-ki/anime-downloader#149]
**Describe the bug**

error is thrown when downloading from AnimePahe source, tried different animes but same result.

Tried again with 9anime and was able to start the download. 

**To reproduce**

```
anime dl -e 1:20 --download-dir /mnt/c/Users/icraz/Desktop/Conan --provider animepahe -xd "{aria2}" -ll DEBUG "Shougeki"

```

<details>
<summary>LOG</summary>

```


INFO root: anime-downloader 3.6.2
DEBUG root: Platform: Linux-4.4.0-17763-Microsoft-x86_64-with-Ubuntu-18.04-bionic
DEBUG root: Python 3.6.7
DEBUG root: API call URL: https://animepahe.com/api with params {'l': 8, 'm': 'search', 'q': 'Shougeki'}
DEBUG root: URL: https://animepahe.com/api?l=8&m=search&q=Shougeki
DEBUG root: Returned data: {'total': 2, 'data': [{'id': 2722, 'slug': 'tales-of-symphonia-the-animation-tethe-039-alla-hen-specials', 'title': "Tales of Symphonia The Animation: Tethe'alla-hen Specials", 'type': 'Special', 'episodes': 4, 'status': 'Finished Airing', 'season': 'Spring 2010', 'score': 7.18, 'image': 'https://i.animepahe.com/posters/69d37268c0f1ed518a629d4ecd5e9be9.jpg', 'relevance': '39'}, {'id': 91, 'slug': 'shokugeki-no-souma', 'title': 'Shokugeki no Souma', 'type': 'TV', 'episodes': 24, 'status': 'Finished Airing', 'season': 'Spring 2015', 'score': 8.55, 'image': 'https://i.animepahe.com/posters/c850a415b57767748faeb3f6975372f1.jpg', 'relevance': '22'}]}
DEBUG root: Tales of Symphonia The Animation: Tethe'alla-hen Specials
DEBUG root: Shokugeki no Souma
 1: Tales of Symphonia The Animation: Tethe'
 2: Shokugeki no Souma

Enter the anime no:  [1]: 2
INFO root: Selected Shokugeki no Souma
INFO root: Extracting episode info from page
DEBUG root: API call URL: https://animepahe.com/api with params {'m': 'release', 'id': '91', 'sort': 'episode_asc', 'page': 1}
DEBUG root: URL: https://animepahe.com/api?m=release&id=91&sort=episode_asc&page=1
DEBUG root: Returned data: {'total': 24, 'per_page': 30, 'current_page': 1, 'last_page': 1, 'next_page_url': None, 'prev_page_url': None, 'from': 1, 'to': 24, 'data': [{'id': 39936, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '01', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/b460717d25c02fc2ac45dd471d1dced2.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': 'c4ec3e454038b3cee9c10eacaad8627fd7af8d18', 'filler': 0, 'created_at': '2017-10-19 11:35:20'}, {'id': 39937, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '02', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/42a07462f39286aedfa8a08c49a541ab.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '2df1c5dbd190f6e38d89fbd418cea5cb475b15eb', 'filler': 0, 'created_at': '2017-10-19 11:50:21'}, {'id': 39938, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '03', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/f8bcd79b6ad2592f4d866573d2addb8c.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': 'a4533313a6c548442d67c3f20d0b3438acd3940a', 'filler': 0, 'created_at': '2017-10-19 12:00:21'}, {'id': 39939, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '04', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/9cefc9400c9b8e2be0039804a3ca79e9.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '65e663cf43d227a05c30a913e8023e755a525887', 'filler': 0, 'created_at': '2017-10-19 12:15:25'}, {'id': 39940, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '05', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/167d9fa58b28574a429c3f1e1d84181a.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '64dbce1eec5d23f50fd16264bc3fa1c266038e83', 'filler': 0, 'created_at': '2017-10-19 12:30:19'}, {'id': 39941, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '06', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/baaab062cf97af29b2522989e8b398f5.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': 'a0f08c8349448db4e92f786d32370039075d1964', 'filler': 0, 'created_at': '2017-10-19 12:45:20'}, {'id': 39942, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '07', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/222e798a09d9d9fb41b8b60d40e2bfd9.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': 'd5bc105c6cfdcb0c2bc3ef69237127fa290466a5', 'filler': 0, 'created_at': '2017-10-19 13:00:20'}, {'id': 39943, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '08', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/3935090969a6e8d4aa35e33f7e4afd5e.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '961dbbf1587f84c8d31d20a66b6286658e046856', 'filler': 0, 'created_at': '2017-10-19 13:10:25'}, {'id': 39944, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '09', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/8257f88638f0217d97686622db5950f6.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '47529cf8c47f69dbe94cdcc4dd1ad0dd195dc7a4', 'filler': 0, 'created_at': '2017-10-19 13:25:23'}, {'id': 39945, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '10', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/992d98b6bf3c2de6f5a0020c5ec27580.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '82a75b39d0b61daf24c38c3a5626837b13c78f45', 'filler': 0, 'created_at': '2017-10-19 13:40:21'}, {'id': 39946, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '11', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/a5314fff3eda3280c772caea5cf44137.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '1040dd88bbc2c15616d4f6107df449e006880993', 'filler': 0, 'created_at': '2017-10-19 13:55:19'}, {'id': 39947, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '12', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/748549257d20af39e33d94eac909a01c.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '90b918efdb5f686178d99b0b3c129a4c1251ca06', 'filler': 0, 'created_at': '2017-10-19 14:10:25'}, {'id': 39948, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '13', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/5a9a65332ce4b94513c56e4cd45e717b.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '2a1149861c1f6944e45e4aaaedba428607b04b31', 'filler': 0, 'created_at': '2017-10-19 14:25:20'}, {'id': 39949, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '14', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/02aaba9e0681bcf48eb33cf663892e3a.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '18d0a8f663000c622c24b10cf6944beb98107a95', 'filler': 0, 'created_at': '2017-10-19 14:40:21'}, {'id': 39950, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '15', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/18311b92eedadb9a0807f3ce616b81fd.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '06907b73305ae84fe8f8e255fde438741c0048da', 'filler': 0, 'created_at': '2017-10-19 14:55:28'}, {'id': 39951, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '16', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/52b8a81eb75739522b6c2b1ec318a79b.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '1b65139909c8b9f59d9964fc24b5a15d855d061e', 'filler': 0, 'created_at': '2017-10-19 15:10:22'}, {'id': 39952, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '17', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/2e148e244397eb4266a8bde4fe3471ab.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': 'b3cbb3beb17382f7a453e3b13eeab60c8f3ed949', 'filler': 0, 'created_at': '2017-10-19 15:25:19'}, {'id': 39953, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '18', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/43c5e0b7b67aa8b4650998271018f62c.jpg', 'disc': 'BD', 'duration': '00:24:57', 'session': '3f46f771446dcc4e65cb87147597587d8388d94f', 'filler': 0, 'created_at': '2017-10-19 15:40:26'}, {'id': 39954, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '19', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/d6a585e9a3eb66c95088eab68c90c0e6.jpg', 'disc': 'BD', 'duration': '00:24:42', 'session': 'bedde877a4ccffbb91457f1f8dcd1de2756fb612', 'filler': 0, 'created_at': '2017-10-19 16:05:20'}, {'id': 39955, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '20', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/99e9e1b39fe4d89a81a9b78a7d88ba36.jpg', 'disc': 'BD', 'duration': '00:24:42', 'session': '788d10273e41a36067d8e981570e4c8e4631de17', 'filler': 0, 'created_at': '2017-10-19 16:10:19'}, {'id': 39956, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '21', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/63635a264dbaf34da929931e22450e3e.jpg', 'disc': 'BD', 'duration': '00:24:42', 'session': '570a12726d0df10e425b8199e12b6d8911120154', 'filler': 0, 'created_at': '2017-10-19 16:30:20'}, {'id': 39957, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '22', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/8bb6c7376c073031799054cbb3f7265f.jpg', 'disc': 'BD', 'duration': '00:24:42', 'session': '5e0f1cebfb4ffef133dc880676ccc7a34d02fda4', 'filler': 0, 'created_at': '2017-10-19 16:45:20'}, {'id': 39958, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '23', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/030e989921d575b33b240cb89e6f2a11.jpg', 'disc': 'BD', 'duration': '00:24:42', 'session': 'f0db4476c5e7fd28b4495fc8787e02f1270ccb9e', 'filler': 0, 'created_at': '2017-10-19 17:00:28'}, {'id': 39959, 'anime_id': 91, 'anime_title': 'Shokugeki no Souma', 'anime_slug': 'shokugeki-no-souma', 'episode': '24', 'edition': '', 'title': '', 'fansub': 'FFF', 'snapshot': 'https://i.animepahe.com/snapshots/da79d3e00138f7ff8c7dfe0c2cd55916.jpg', 'disc': 'BD', 'duration': '00:24:42', 'session': '9e175f3b85c275e237cef6a58866f51fe8df4e58', 'filler': 0, 'created_at': '2017-10-19 17:15:21'}]}
INFO root: Found anime: Shokugeki no Souma
DEBUG root: Extracting stream info of id: https://animepahe.com/anime/shokugeki-no-souma/39936
DEBUG root: API call URL: https://animepahe.com/api with params {'id': '39936', 'm': 'embed', 'p': 'mp4upload'}
DEBUG root: URL: https://animepahe.com/api?id=39936&m=embed&p=mp4upload
DEBUG root: Returned data: []
Traceback (most recent call last):
  File "/home/moonpen/.local/bin/anime", line 11, in <module>
    sys.exit(cli())
  File "/home/moonpen/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/moonpen/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/moonpen/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/moonpen/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/moonpen/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/moonpen/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/moonpen/.local/lib/python3.6/site-packages/anime_downloader/cli.py", line 117, in dl
    animes = util.parse_ep_str(anime, episode_range)
  File "/home/moonpen/.local/lib/python3.6/site-packages/anime_downloader/util.py", line 117, in parse_ep_str
    for episode in split_anime(anime, episode_grammar):
  File "/home/moonpen/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 78, in __getitem__
    ep_no=ep_id[0])
  File "/home/moonpen/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 122, in __init__
    self.get_data()
  File "/home/moonpen/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 162, in get_data
    self._sources = self._get_sources()
  File "/home/moonpen/.local/lib/python3.6/site-packages/anime_downloader/sites/animepahe.py", line 28, in _get_sources
    sources = episode['data'][episode_id]
TypeError: list indices must be integers or slices, not str

```

**Comment by 29ayush** [comment]
@moonpen I am unable to reproduce the issue.
Based on the log, I am pretty sure you are using older version of anime-downloader.

Please update:- 

> !pip install -U git+https://github.com/vn-ki/anime-downloader.git#egg=anime-downloader[cloudflare]

**Comment by moonpen** [comment]
The update seems to fix it, thanks 😄 

Pip repository might have been out of date when I installed this
