### ISSUE TITLE
Error raised when trying to read from watch file if you still have the old watch file.

### ISSUE THREAD

**Issue by Enderlein** [vn-ki/anime-downloader#15]
When I tried to open my watch list in the most recent version, the following error was thrown:
```
Kevin@CHF117 MINGW32 /d/git/anime-downloader (master)
$ anime watch -l
anime: anime-downloader 2.6.0
Traceback (most recent call last):
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python36-32\Scripts\anime-s                                                                                                                           cript.py", line 11, in <module>
    load_entry_point('anime-downloader', 'console_scripts', 'anime')()
  File "c:\users\kevin\appdata\local\programs\python\python36-32\lib\site-packag                                                                                                                           es\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\kevin\appdata\local\programs\python\python36-32\lib\site-packag                                                                                                                           es\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\kevin\appdata\local\programs\python\python36-32\lib\site-packag                                                                                                                           es\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\kevin\appdata\local\programs\python\python36-32\lib\site-packag                                                                                                                           es\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\kevin\appdata\local\programs\python\python36-32\lib\site-packag                                                                                                                           es\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "d:\git\anime-downloader\anime_downloader\cli.py", line 190, in watch
    list_animes(watcher, quality, download_dir)
  File "d:\git\anime-downloader\anime_downloader\cli.py", line 208, in list_anim                                                                                                                           es
    watcher.list()
  File "d:\git\anime-downloader\anime_downloader\watch.py", line 34, in list
    animes = self._read_from_watch_file()
  File "d:\git\anime-downloader\anime_downloader\watch.py", line 114, in _read_f                                                                                                                           rom_watch_file
    data = json.load(watch_file)
  File "c:\users\kevin\appdata\local\programs\python\python36-32\lib\json\__init                                                                                                                           __.py", line 296, in load
    return loads(fp.read(),
  File "c:\users\kevin\appdata\local\programs\python\python36-32\lib\encodings\c                                                                                                                           p1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 43: chara                                                                                                                           cter maps to <undefined>

```

I figured it was because the old file was a pickle file and it was trying to decode it as a json file, so I deleted the old file (`AppData > Roaming > anime downloader` on Windows) and voila, it works. 

Is there a way we can identify and delete the old watch file automatically so that people don't have to do this on their own?

**Comment by KashTag** [comment]
I can't really understand which file you're trying to delete I found out there's a function 'remove(file path)' in the module 'os' that can delete files.
If you want I could try it out but you'll have to tell me which file you exactly want deleted and when, though I can't guarantee anything cause i'm still pretty crappy at python.

**Comment by KashTag** [comment]
Hmm are you saying that the config.json file should be deleted when the command anime watch -l is entered?

**Comment by vn-ki** [comment]
I think we shouldn't remove any file. We can catch the unicode error and do `raise` a more informational error. I think that is not required because the only people using `watch` would be us 3, and all installs after `2.6.0` would use json by default.

**Comment by Enderlein** [comment]
That would make a lot more sense. I'll work on doing that.

**Comment by vn-ki** [comment]
@Enderlein Even though you have push access to the repository, it's better to open a PR, unless it's a very minor change. I'll do the same too, because another pair of eyes is always better.

**Comment by Enderlein** [comment]
Of course.

**Comment by Enderlein** [comment]
Ah never mind, I've changed my mind. The only 3 people who need to be worried about this are already informed about it and I already deleted the old file so I can't properly test anything new.

**Comment by vn-ki** [comment]
Haha. Okay then.
