### ISSUE TITLE
Unable to download or watch

### ISSUE THREAD

**Issue by SakshamV** [vn-ki/anime-downloader#158]
I am unable to use the tool, in my (limited) understanding its some sort of installation error, I would be grateful for any guidance. I tried using all the possible formats and methods to download, same long error [list.](https://imgur.com/a/p8fOBEA)
Thanks

CMD log:

C:\Users\saksh>anime dl https://www2.9anime.to/watch/gintama.5kq/8m6wxq
[32manime[0m: anime-downloader 3.6.2
[32manime[0m: Extracting episode info from page
[32manime[0m: Found anime: Gintama
[32manime[0m: Downloading to C:\Users\saksh
Traceback (most recent call last):
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001A994F4E240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.rapidvideo.com', port=443): Max retries exceeded with url: /e/G12ZJB56KL&q=720p (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001A994F4E240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\extractors\rapidvideo.py", line 18, in _get_data
    r = session.get(url, headers=headers)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.rapidvideo.com', port=443): Max retries exceeded with url: /e/G12ZJB56KL&q=720p (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001A994F4E240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001A995A3B240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.rapidvideo.com', port=443): Max retries exceeded with url: /e/G12ZJB56KL&q=720p (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001A995A3B240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\saksh\AppData\Local\Programs\Python\Python37\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\cli.py", line 125, in dl
    for episode in animes:
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 78, in __getitem__
    ep_no=ep_id[0])
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 124, in __init__
    self.source().stream_url
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 26, in stream_url
    self.get_data()
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 38, in get_data
    data = self._get_data()
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\extractors\rapidvideo.py", line 24, in _get_data
    }, headers=headers)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\saksh\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.rapidvideo.com', port=443): Max retries exceeded with url: /e/G12ZJB56KL&q=720p (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001A995A3B240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by perit5039** [comment]
if u r staying in india, sometimes the isp will block connection to rapidvideo, u can try using vpn or the easiest way is to use google dns and try again

**Comment by SakshamV** [comment]
> 
> 
> if u r staying in india, sometimes the isp will block connection to rapidvideo, u can try using vpn or the easiest way is to use google dns and try again

It worked, thank you so much
