### ISSUE TITLE
anime_downloader.sites.exceptions.NotFoundError

### ISSUE THREAD

**Issue by nedz14** [vn-ki/anime-downloader#166]
C:\Users\user>anime dl "https://www2.9anime.to/watch/fullmetal-alchemist-brotherhood.0r7" --url
←[32manime←[0m: anime-downloader 3.6.2
←[32manime←[0m: Extracting episode info from page
←[32manime←[0m: Found anime: Fullmetal Alchemist: Brotherhood
←[32manime←[0m: Quality 720p not found. Trying 480p.
←[32manime←[0m: Quality 480p not found. Trying 360p.
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python36\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python36\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python36\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python36\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python36\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python36\lib\site-packages\anime_downloader\cli.py", line 127, in dl
    util.print_episodeurl(episode)
  File "c:\python36\lib\site-packages\anime_downloader\util.py", line 125, in print_episodeurl
    print(episode.source().stream_url)
  File "c:\python36\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 26, in stream_url
    self.get_data()
  File "c:\python36\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 41, in get_data
    raise NotFoundError
anime_downloader.sites.exceptions.NotFoundError

with --log-level DEBUG
**********************

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\user>anime dl --url "https://www2.9anime.to/watch/fullmetal-alchemist-brotherhood.0r7" --log-level DEBUG
INFO root: anime-downloader 3.6.2
DEBUG root: Platform: Windows-7-6.1.7601-SP1
DEBUG root: Python 3.6.0
INFO root: Extracting episode info from page
DEBUG root: data-ts: 1553529600
DEBUG root: EPISODE IDS: length: 64, ids: ['25v2m2', '67j9q0', '95mlwm', 'm1zmr8', 'okv9w5', 'pl8kxq', 'vr8n3l', 'yx817z', '3
5vqor', '67j9r0', 'kz2on4', 'l08po6', 'm1zmp8', 'okv9r5', 'pl8kvq', 'rn4mxn', 'wv8927', '08xpl5', '15v2mp', '35vqmr', '55vro9
', '75kmq1', '85lkry', 'm1zmk8', 'nj4nlm', 'pl8knq', 'rn4mpn', '08xpj5', '25v212', '75km61', '95mlkm', 'l08pw6', 'm1zm98', 'l
08pwm', 'nj4nyj', 'okv9zy', 'qmvl1w', 'wv89jl', 'x98pkw', 'jyzvv8', 'kz2ww6', 'm1z227', 'jyzvvy', 'nj433l', 'rn4ljm', 'x98rjv
', 'zy8l1w', '15vnrv', '55v2km', '67jlv4', '85l0nq', 'kz2wkr', 'qmvxk5', 'vr8v9v', 'x98rvv', '45vq27', 'jyzvpy', 'm1z2vp', 'o
kvjxz', 'rn4lom', 'zy8lkw', '35vr0y', '55v2wm', '67jl04']
INFO root: Found anime: Fullmetal Alchemist: Brotherhood
DEBUG root: Extracting stream info of id: 25v2m2
DEBUG root: API call URL: https://9anime.to/ajax/episode/info with params {'id': '25v2m2', 'server': '33', 'ts': '1553529600'
, '_': 744}
DEBUG root: URL: https://www2.9anime.to/ajax/episode/info?id=25v2m2&server=33&ts=1553529600&_=744
DEBUG root: Returned data: {'grabber': 'https://www2.9anime.to/grabber-api/?server=33', 'params': [], 'backup': 0, 'target':
'https://www.rapidvideo.com/e/G1FBRPD3JC', 'type': 'iframe', 'name': '01', 'subtitle': ''}
DEBUG root: Sources :
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/G1FBRPD3JC&q=720p
WARNING root: Quality 720p not found. Trying 480p.
DEBUG root: API call URL: https://9anime.to/ajax/episode/info with params {'id': '25v2m2', 'server': '33', 'ts': '1553529600'
, '_': 744}
DEBUG root: URL: https://www2.9anime.to/ajax/episode/info?id=25v2m2&server=33&ts=1553529600&_=744
DEBUG root: Returned data: {'grabber': 'https://www2.9anime.to/grabber-api/?server=33', 'params': [], 'backup': 0, 'target':
'https://www.rapidvideo.com/e/G1FBRPD3JC', 'type': 'iframe', 'name': '01', 'subtitle': ''}
DEBUG root: Sources :
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/G1FBRPD3JC&q=480p
WARNING root: Quality 480p not found. Trying 360p.
DEBUG root: API call URL: https://9anime.to/ajax/episode/info with params {'id': '25v2m2', 'server': '33', 'ts': '1553529600'
, '_': 744}
DEBUG root: URL: https://www2.9anime.to/ajax/episode/info?id=25v2m2&server=33&ts=1553529600&_=744
DEBUG root: Returned data: {'grabber': 'https://www2.9anime.to/grabber-api/?server=33', 'params': [], 'backup': 0, 'target':
'https://www.rapidvideo.com/e/G1FBRPD3JC', 'type': 'iframe', 'name': '01', 'subtitle': ''}
DEBUG root: Sources :
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/G1FBRPD3JC&q=360p
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/G1FBRPD3JC&q=360p
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python36\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python36\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python36\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python36\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python36\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python36\lib\site-packages\anime_downloader\cli.py", line 127, in dl
    util.print_episodeurl(episode)
  File "c:\python36\lib\site-packages\anime_downloader\util.py", line 125, in print_episodeurl
    print(episode.source().stream_url)
  File "c:\python36\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 26, in stream_url
    self.get_data()
  File "c:\python36\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 41, in get_data
    raise NotFoundError
anime_downloader.sites.exceptions.NotFoundError

Same output for the other Options.

**Comment by DaBoss5** [comment]
I have also been getting this error, and I believe it might have something to do with rapidvideo (they've changed it so that you must press button before you get to the video). Is there any way to make it default to mp4upload until something is done about that?

**Comment by vn-ki** [comment]
Fixed in 3.6.3
