### ISSUE TITLE
9anime api watch error

### ISSUE THREAD

**Issue by CBeige** [vn-ki/anime-downloader#176]
**Describe the bug**

Bug on anime watch, points to 9anime API then crashes.

**To reproduce**

```
anime watch "one punch"
with one punch man S2 on list, 1 Ep watched
```

<details>
<summary>LOG</summary>

```
INFO root: anime-downloader 3.6.3
DEBUG root: Platform: Linux-4.20.17-1-MANJARO-x86_64-with-arch-Manjaro-Linux
DEBUG root: Python 3.7.3
DEBUG root: Anime:
Site: 9anime
Anime: One Punch Man 2nd Season
Episode count: 3
, episodes_done: 1
INFO root: Found One Punch Man 2nd Season
DEBUG root: Sliced epiosdes: [[2, '3969354b05ea5cdf185f09c179239ab4eec62ecde5d25e9f28dcc3dbb63e4ccb'], [3, '4101fccdce51c713e88ccdb33460ee0734f5e3da034c32f0c46d0f9f68de39ab']]
DEBUG root: Extracting stream info of id: 3969354b05ea5cdf185f09c179239ab4eec62ecde5d25e9f28dcc3dbb63e4ccb
DEBUG root: API call URL: https://9anime.to/ajax/episode/info with params {'id': '3969354b05ea5cdf185f09c179239ab4eec62ecde5d25e9f28dcc3dbb63e4ccb', 'server': '33', 'ts': 0, '_': 744}
DEBUG root: URL: https://www3.9anime.to/ajax/episode/info?id=3969354b05ea5cdf185f09c179239ab4eec62ecde5d25e9f28dcc3dbb63e4ccb&server=33&ts=0&_=744
DEBUG root: Returned data: {'error': 404}
DEBUG root: API call URL: http://9anime.cloud/ajax/episode/info with params {'id': '3969354b05ea5cdf185f09c179239ab4eec62ecde5d25e9f28dcc3dbb63e4ccb', 'server': '33'}
DEBUG root: URL: https://9anime.vip/ajax/episode/info?id=3969354b05ea5cdf185f09c179239ab4eec62ecde5d25e9f28dcc3dbb63e4ccb&server=33
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/nineanime.py", line 43, in _get_sources
    'http://9anime.cloud/ajax/episode/info', params=params)
  File "/usr/lib/python3.7/site-packages/anime_downloader/util.py", line 153, in get_json
    data = res.json()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/anime", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/anime_downloader/cli.py", line 244, in watch
    watch_anime(watcher, anime)
  File "/usr/lib/python3.7/site-packages/anime_downloader/cli.py", line 335, in watch_anime
    episode = anime[anime.episodes_done]
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 78, in __getitem__
    ep_no=ep_id[0])
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 122, in __init__
    self.get_data()
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 162, in get_data
    self._sources = self._get_sources()
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/nineanime.py", line 50, in _get_sources
    ) from e
anime_downloader.sites.exceptions.AnimeDLError: 9anime probably changed their API again. Check the issueshere https://github.com/vn-ki/anime-downloader/issues. If it has not been reported yet, please open a new issue



```

**Comment by vn-ki** [comment]
#183
