### ISSUE TITLE
9anime probably changed the API.

### ISSUE THREAD

**Issue by GoobyTheBOI** [vn-ki/anime-downloader#190]
**Describe the bug**

**To reproduce**
I try to watch anime any 9anime show

```
Traceback (most recent call last):
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\nineanime.py", line 35, in _get_sources
    url = get_stream_url(self._base_url, params)
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\nineanime.py", line 32, in get_stream_url
    return data['target']
KeyError: 'target'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\nineanime.py", line 44, in _get_sources
    url = data['target']
KeyError: 'target'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Luuk\AppData\Local\Programs\Python\Python37\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\cli.py", line 230, in watch
    list_animes(watcher, quality, download_dir)
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\cli.py", line 304, in list_animes
    for episode in anime:
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 78, in __getitem__
    ep_no=ep_id[0])
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 122, in __init__
    self.get_data()
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 162, in get_data
    self._sources = self._get_sources()
  File "c:\users\luuk\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\nineanime.py", line 50, in _get_sources
    ) from e
anime_downloader.sites.exceptions.AnimeDLError: 9anime probably changed their API again. Check the issues here https://github.com/vn-ki/anime-downloader/issues. If it has not been reported yet, please open a new issue

```

anime watch --log-level DEBUG
INFO root: anime-downloader 3.6.3
DEBUG root: Platform: Windows-10-10.0.17763-SP0
DEBUG root: Python 3.7.2

<details>
<summary>LOG</summary>

```



```

**Comment by vn-ki** [comment]
You are using an old version
