### ISSUE TITLE
9Anime is not working now!

### ISSUE THREAD

**Issue by AmitGamingKing** [vn-ki/anime-downloader#193]
**Describe the bug**
I recently started using this library and on the first day 9Anime worked fine but from second day it is not working and on website I'm getting captcha on every visit!

**To reproduce**
```python
NineAnime = get_anime_class('9anime')
results = NineAnime.search('death note')
anime = NineAnime(results[0].url)
```

**Error showing**
```
Traceback (most recent call last):
  File "an.py", line 4, in <module>
    results = NineAnime.search('death note')
  File "/home/user/.local/lib/python3.6/site-packages/anime_downloader/sites/nineanime.py", line 71, in search
    'div', {'class': 'film-list'}).find_all('div', {'class': 'item'})
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by vn-ki** [comment]
#183
