### ISSUE TITLE
Problem downloading

### ISSUE THREAD

**Issue by jcurrenc** [vn-ki/anime-downloader#196]
I get this error message when attempting to download, not sure what to do.

`C:\MiaS3>anime dl https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3 -xd {aria2}
[32manime[0m: anime-downloader 3.6.1
[32manime[0m: Extracting episode info from page
[32manime[0m: Found anime: Mia and Me - Season 3
[32manime[0m: Downloading to C:\MiaS3
Traceback (most recent call last):
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\Scripts\anime-script.py", line 11, in <module>
    load_entry_point('anime-downloader==3.6.1', 'console_scripts', 'anime')()
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\click-7.0-py3.7.egg\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\anime_downloader-3.6.1-py3.7.egg\anime_downloader\cli.py", line 125, in dl
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\anime_downloader-3.6.1-py3.7.egg\anime_downloader\sites\anime.py", line 78, in __getitem__
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\anime_downloader-3.6.1-py3.7.egg\anime_downloader\sites\anime.py", line 122, in __init__
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\anime_downloader-3.6.1-py3.7.egg\anime_downloader\sites\anime.py", line 162, in get_data
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\anime_downloader-3.6.1-py3.7.egg\anime_downloader\sites\kisscartoon.py", line 29, in _get_sources
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\site-packages\requests-2.22.0-py3.7.egg\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**To reproduce**

```

```

<details>
<summary>LOG</summary>

```



```

**Comment by ngomile** [comment]
I ran the same command and received an error that it couldn't pass through a cloudflare challenge. I updated cfscrape and it managed to go through with the same command. Try updating your cfscrape.

**Comment by jcurrenc** [comment]
Alright, i tried reinstalling cfscrape and I am still getting the same error.

**Comment by jcurrenc** [comment]
Never mind, my version of the script was out of date. Sorry.
