### ISSUE TITLE
KeyError: 'playlist'

### ISSUE THREAD

**Issue by jcurrenc** [vn-ki/anime-downloader#198]
KeyError: 'playlist'

I was able to download the first 14 episodes with no issue, no episodes past this will download.

**To reproduce**

```
anime dl https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3 -e 15:26 -ll DEBUG -xd "{aria2}"
```

<details>
<summary>LOG</summary>

```
PS C:\MiaS3> anime dl https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3 -e 15:26 -ll DEBUG -xd "{aria2}"
INFO root: anime-downloader 3.6.3
DEBUG root: Platform: Windows-10-10.0.17134-SP0
DEBUG root: Python 3.7.3
INFO root: Extracting episode info from page
DEBUG root: EPISODE IDS: length: 26, ids: ['https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-001-Kyara-s-Birth?id=78278', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-002-The-Dark-Elfs-Arrival?id=78306', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-003-King-and-Queen-Asleep?id=78307', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-004-Pan-Kings-Secret?id=78308', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-005-Sister-Wracked?id=78309', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-006-Unicorn-Kindergarden?id=78310', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-007-Phuddle-Moves-Out?id=78311', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-008-The-Highest-Bidder?id=78312', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-009-Night-Becomes-Day?id=78313', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-010-Circle-of-Life?id=78314', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-011-Glowing-Arrows?id=78315', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-012-Finding-Simo?id=78316', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-013-Freeze-and-Snoot?id=78317', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-014-The-Six-eyed-Monster?id=78318', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-015-Moonstruck?id=78319', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-016-Under-the-Heartleaf-Tree?id=78320', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-017-Bluebardo-in-Trouble?id=78321', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-018-Giant-Butterfly?id=78322', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-019-Shyest-Unicorn?id=78323', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-020-Return-to-Rainbow-Island?id=78324', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-021-Ziggo-Moves-Out?id=78325', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-022-Return-to-Crystal-Cave?id=78326', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-023-Heist-On-Dark-Castle?id=78327', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-024-Seeing-in-the-Dark?id=78328', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-025-Big-Sleep?id=78329', 'https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-026-The-Last-Stand?id=78330']
INFO root: Found anime: Mia and Me - Season 3
DEBUG root: Extracting stream info of id: https://kisscartoon.is/Cartoon/Mia-and-Me-Season-3/Episode-015-Moonstruck?id=78319
Traceback (most recent call last):
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jjenn\AppData\Local\Programs\Python\Python37\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\click-7.0-py3.7.egg\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\cli.py", line 119, in dl
    animes = util.parse_ep_str(anime, episode_range)
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\util.py", line 118, in parse_ep_str
    for episode in split_anime(anime, episode_grammar):
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 78, in __getitem__
    ep_no=ep_id[0])
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 122, in __init__
    self.get_data()
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 162, in get_data
    self._sources = self._get_sources()
  File "c:\users\jjenn\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\kisscartoon.py", line 37, in _get_sources
    res.json()['playlist'][0]['file']
KeyError: 'playlist'


```

**Comment by vn-ki** [comment]
Apparently, there is a version 2 of kisscartoon API. 

From inspecting the network requests, 
```
https://kisscartoon.is/ajax/anime/load_episodes_v2?s=hserver
{"status":true,"value":"<iframe src=\"https:\/\/embed.streamx.live?k=a4c6759644252e20cb5449dbf0b891a4&li=78319&tham=1569235591&lt=hydrax&check_hot=1&qlt=720p&spq=p&prv=&key=ab5115254e87c6568b0dcc4094b58aa7&ua=a55153776e867fa45db0d074986d096afd50e77b7a5c3084ec923f9ad930b8f16ebb5ae07b401e419b0f1f33f0f691dce3fa71313d5a0f21a3cc216afe1f83c8c15a2ed2f2d6e99c0801e69ad416dfcfd7a708094b482133594be79b683fd9771f9cffe25fc10cd9cd35256ef2083cf6\" width=\"100%\" height=\"100%\" style=\"border:none;overflow:hidden\" scrolling=\"no\" frameborder=\"0\" allowTransparency=\"true\" allowFullScreen=\"true\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\"><\/iframe>","embed":true,"html5":false,"type":"","sv":"hydrax","download_get":""}
```

Someone will have to update the provider to use the new API.

**Comment by MichaelDavidJohnson** [comment]
Inactivity
