### ISSUE TITLE
Odd error when downloading from gogoanime

### ISSUE THREAD

**Issue by hbashton** [vn-ki/anime-downloader#202]
```
Traceback (most recent call last):
  File "animedownloader.py", line 100, in <module>
    main()
  File "animedownloader.py", line 59, in main
    ep = Anime[epnum - 1]
  File "/home/jbw716/.local/lib/python3.5/site-packages/anime_downloader/sites/anime.py", line 78, in __getitem__
    ep_no=ep_id[0])
  File "/home/jbw716/.local/lib/python3.5/site-packages/anime_downloader/sites/anime.py", line 124, in __init__
    self.source().stream_url
  File "/home/jbw716/.local/lib/python3.5/site-packages/anime_downloader/extractors/base_extractor.py", line 26, in stream_url
    self.get_data()
  File "/home/jbw716/.local/lib/python3.5/site-packages/anime_downloader/extractors/base_extractor.py", line 38, in get_data
    data = self._get_data()
  File "/home/jbw716/.local/lib/python3.5/site-packages/anime_downloader/extractors/mp4upload.py", line 26, in _get_data
    domain, video_id, protocol = source_parts_re.match(mp4u_embed).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by vn-ki** [comment]
Can you try master and see if this is the case?

**Comment by vn-ki** [comment]
Closing due to inactivity. No information to test too.
