### ISSUE TITLE
Some weird issue while downloading from kissanime 

### ISSUE THREAD

**Issue by Esarve** [vn-ki/anime-downloader#208]
I was downloading from kissanime with this command (Windows) 
anime dl 'dororo' --provider kissanime

I got this error:

[32manime[0m: anime-downloader 3.6.3
Traceback (most recent call last):
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sourav\AppData\Local\Programs\Python\Python37-32\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\cli.py", line 102, in dl
    anime_url = util.search(anime_url, provider)
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\util.py", line 59, in search
    cls = get_anime_class(provider)
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\init.py", line 21, in get_anime_class
    'anime_downloader.sites.{}'.format(site[0])
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\sourav\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\kissanime.py", line 1, in <module>
    import cfscrape
ModuleNotFoundError: No module named 'cfscrape'

**Comment by vn-ki** [comment]
```
pip install -U anime-downloader[cloudflare]
```

Please read readme
