### ISSUE TITLE
Download Issue with twistmoe

### ISSUE THREAD

**Issue by 5ud52** [vn-ki/anime-downloader#209]
**Describe the bug**
Whenever I try to download from twist moe i get the following issue:

**To reproduce**
[32manime[0m: anime-downloader 3.6.3
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\anime-script.py", line 11, in <module>
    load_entry_point('anime-downloader==3.6.3', 'console_scripts', 'anime')()
  File "C:\Program Files\Python36\lib\site-packages\click-7.0-py3.6.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\click-7.0-py3.6.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python36\lib\site-packages\click-7.0-py3.6.egg\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python36\lib\site-packages\click-7.0-py3.6.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python36\lib\site-packages\click-7.0-py3.6.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\click-7.0-py3.6.egg\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\anime_downloader-3.6.3-py3.6.egg\anime_downloader\cli.py", line 102, in dl
  File "C:\Program Files\Python36\lib\site-packages\anime_downloader-3.6.3-py3.6.egg\anime_downloader\util.py", line 59, in search
  File "C:\Program Files\Python36\lib\site-packages\anime_downloader-3.6.3-py3.6.egg\anime_downloader\sites\init.py", line 21, in get_anime_class
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Program Files\Python36\lib\site-packages\anime_downloader-3.6.3-py3.6.egg\anime_downloader\sites\twistmoe.py", line 1, in <module>
ModuleNotFoundError: No module named 'Crypto'

<details>
<summary>LOG</summary>

```



```

**Comment by vn-ki** [comment]
```
pip install pycryptodome
```

**Comment by 5ud52** [comment]
Still not working.
 :( :( :(

**Comment by vn-ki** [comment]
Try master branch

**Comment by 5ud52** [comment]
how?

**Comment by lizoren** [comment]
join the discord

**Comment by 5ud52** [comment]
can you send me invite link?

**Comment by vn-ki** [comment]
https://discord.gg/Qn2nWGm. It's in the readme

**Comment by vn-ki** [comment]
You can follow this to install: https://github.com/vn-ki/anime-downloader/wiki/Installation#windows-via-choco-method-2

**Comment by 5ud52** [comment]
Thanks it solved it!
