### ISSUE TITLE
Shows server error 503 when using kissanime even though it works perfectly fine in my browser

### ISSUE THREAD

**Issue by redfanglicker** [vn-ki/anime-downloader#218]
**Describe the bug**
I am able to add anime via kissanime but when i try to watch it using anime watch, it shows server error 503 but the website perfectly opens in my browser

**To reproduce**

```

```
this is the log
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.util[16576] INFO anime-downloader 4.0.0.r1
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.util[16576] DEBUG Platform: Linux-4.15.0-54-generic-x86_64-with-LinuxMint-19.1-tessa
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.util[16576] DEBUG Python 3.6.8
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.sites.helpers.request[16576] DEBUG HTML file temp_dir: /tmp/animedly9afwgwi
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.watch[16576] DEBUG Anime: 
Site: kissanime
Anime: Miru Tights
Episode count: 11
, episodes_done: 0
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.sites.anime[16576] DEBUG Extracting stream info of id: http://kissanime.ru/Anime/Miru-Tights/Episode-001?id=158099
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.sites.helpers.request[16576] DEBUG -----
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.sites.helpers.request[16576] DEBUG GET http://kissanime.ru/Anime/Miru-Tights/Episode-001?id=158099&s=rapidvideo
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.sites.helpers.request[16576] DEBUG {}
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.sites.helpers.request[16576] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19'}
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.sites.helpers.request[16576] DEBUG -----
send: b'GET http://kissanime.ru/Anime/Miru-Tights/Episode-001?id=158099&s=rapidvideo HTTP/1.1\r\nHost: kissanime.ru\r\nuser-agent: Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.45 Safari/535.19\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 503 Service Temporarily Unavailable\r\n'
header: Date: Sun, 21 Jul 2019 16:07:30 GMT
header: Content-Type: text/html; charset=UTF-8
header: X-Frame-Options: SAMEORIGIN
header: Set-Cookie: __cfduid=d659a73abd6baabdee0979754a294555d1563725250; expires=Mon, 20-Jul-20 16:07:30 GMT; path=/; domain=.kissanime.ru; HttpOnly
header: Cache-Control: no-cache
header: Vary: Accept-Encoding
header: Server: ATS/5.3.1
header: CF-RAY: 4f9e6d9f7bbad9cc-SIN
header: Age: 0
header: Transfer-Encoding: chunked
header: Connection: keep-alive
2019-07-21 21:36:35 red-Alienware-15-R3 anime_downloader.session[16576] DEBUG uncached request
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader==4.0.0.post1', 'console_scripts', 'anime')()
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/cli.py", line 51, in main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/commands/watch.py", line 101, in command
    watch_anime(watcher, anime)
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/commands/watch.py", line 192, in watch_anime
    episode = anime[anime.episodes_done]
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/anime.py", line 182, in __getitem__
    ep_no=ep_id[0])
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/anime.py", line 282, in __init__
    try_data()
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/anime.py", line 278, in try_data
    self.get_data()
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/anime.py", line 335, in get_data
    self._sources = self._get_sources()
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/kissanime.py", line 17, in _get_sources
    ret = helpers.get(self.url+'&s=rapidvideo', cf=True)
  File "/usr/local/lib/python3.6/dist-packages/anime_downloader/sites/helpers/request.py", line 67, in setup_func
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: http://kissanime.ru/Anime/Miru-Tights/Episode-001?id=158099&s=rapidvideo

```

**Comment by vn-ki** [comment]
Please use some other sites than kissanime or 9anime

**Comment by ngomile** [comment]
Try updating cfscrape with this command:
pip install cfscrape -U

**Comment by redfanglicker** [comment]
> Please use some other sites than kissanime or 9anime

i would if i can but twist.moe is very slow for me and masteranime is dead

**Comment by vn-ki** [comment]
@redfanglicker are you using aria2 for downloads? If not, use that (twist will be faster). Also there are other new providers available.

**Comment by vn-ki** [comment]
I cannot reproduce this. Please reopen if the issue still exists.
