### ISSUE TITLE
Option to choose [1] by default ( -y / --assume-yes / --no-confirm )

### ISSUE THREAD

**Issue by RaitaroH** [vn-ki/anime-downloader#226]
**Describe the feature here**

Basically I want an option to have anime-dl choose the first option [1] by itself. Usually that first option is the only one if you give anime dl the exact title.

This is possible as such:
```bash
echo | anime dl --play "mpv" "Casshern Sins" --episodes 2
```
Except... vlc doesn't work with this. Not sure if a vlc bug or anime-dl bug. So I guess if anime-dl had the option then this pipe hack isn't needed.

<details>
<summary>LOG</summary>

```
$ echo | anime dl --play "vlc" "Casshern Sins" --episodes 2
anime: anime-downloader 3.6.3
 1: Casshern Sins                                                   

Enter the anime no:  [1]: anime: Selected Casshern Sins
anime: Extracting episode info from page
anime: Found anime: Casshern Sins
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
[00005614154d2570] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[00005614155e3e90] qt interface error: cannot start Qt multiple times
[00007f0e64019310] qt generic error: cannot start Qt multiple times
[00005614155e3e90] skins2 interface error: cannot instantiate dialogs provider
[00005614155e3e90] [cli] lua interface: Listening on host "*console".
VLC media player 3.0.8 Vetinari
Command Line Interface initialized. Type `help' for help.
> Shutting down.
[00005614155e3e90] [cli] lua interface: Requested shutdown.
[00005614155e3e90] [cli] lua interface error: Error loading script /usr/lib/vlc/lua/intf/cli.luac: lua/intf/modules/host.lua:289: Interrupted.
[00007f0e5800cbe0] main tls client error: cannot resolve s1.kwik.cx port 443: System error
[00007f0e580057c0] access stream error: HTTP connection failure
Failed to unregister window menu, reason: org.freedesktop.DBus.Error.UnknownMethod ("Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3.7/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: UnregisterWindow is not a valid method of interface com.canonical.AppMenu.Registrar
")
QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by vn-ki** [comment]
I think we should add a CLI option `--choice` which can take individual number or comma separated numbers to select multiple anime.

**Comment by vn-ki** [comment]
@RaitaroH This is in master now.
