### ISSUE TITLE
NoneType object is not subscriptable

### ISSUE THREAD

**Issue by ESPGranEdu** [vn-ki/anime-downloader#252]
**Describe the bug**
Getting NoneType object is no subscriptable with a specific provider

**To reproduce**

```
anime dl "Steins;Gate 0" --provider animeflv
```

<details>
<summary>LOG</summary>

```

[edupy@archlinux-edupy → Steins;Gate 0]$ anime -ll DEBUG dl "Steins;Gate 0" --provider animeflv
2019-10-20 19:14:07 archlinux-edupy anime_downloader.util[2155] INFO anime-downloader 4.0.0
2019-10-20 19:14:07 archlinux-edupy anime_downloader.util[2155] DEBUG Platform: Linux-5.3.7-arch1-1-ARCH-x86_64-with-arch
2019-10-20 19:14:07 archlinux-edupy anime_downloader.util[2155] DEBUG Python 3.7.4
2019-10-20 19:14:07 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG HTML file temp_dir: /tmp/animedlohk_igd0
2019-10-20 19:14:07 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG -----
2019-10-20 19:14:07 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG GET https://animeflv.net/browse?q=Steins;Gate 0
2019-10-20 19:14:07 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG {}
2019-10-20 19:14:07 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; AMD Mac OS X 10_8_2) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/18.6.872'}
2019-10-20 19:14:07 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG -----
send: b'GET /browse?q=Steins;Gate%200 HTTP/1.1\r\nHost: animeflv.net\r\nuser-agent: Mozilla/5.0 (Macintosh; AMD Mac OS X 10_8_2) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/18.6.872\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 20 Oct 2019 17:14:07 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d546a509cb579f1a8d82395870e38208e1571591647; expires=Mon, 19-Oct-20 17:14:07 GMT; path=/; domain=.animeflv.net; HttpOnly; Secure
header: X-Powered-By: PHP/7.2.23
header: Set-Cookie: device=computer; path=/
header: Set-Cookie: PHPSESSID=t6vvgaeltite3tj93q4oqncvg8; path=/
header: Expires: Thu, 19 Nov 1981 08:52:00 GMT
header: Cache-Control: no-store, no-cache, must-revalidate
header: Pragma: no-cache
header: Vary: Accept-Encoding
header: X-Powered-By: PleskLin
header: MS-Author-Via: DAV
header: X-Turbo-Charged-By: LiteSpeed
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 528ca0538b0ed681-MAD
header: Content-Encoding: gzip
2019-10-20 19:14:07 archlinux-edupy anime_downloader.session[2155] DEBUG uncached request
2019-10-20 19:14:07 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG https://animeflv.net/browse?q=Steins;Gate%200
2019-10-20 19:14:07 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG /tmp/animedlohk_igd0/tmpbql_unb_
+--------+-------------------------------------------------------------+--------+
|      6 | Steins;Gate: Kyoukaimenjou no Missing Link - Divide By Zero |        |
|      5 | Steins;Gate - Soumei Eichi no Cognitive Computing           |        |
|      4 | Steins;Gate Fuka Ryoiki no Deja vu                          |        |
|      3 | Steins;Gate: Oukoubakko no Poriomania                       |        |
|      2 | Steins;Gate 0                                               |        |
|      1 | Steins;Gate                                                 |        |
|--------+-------------------------------------------------------------+--------|
|   SlNo | Title                                                       | Meta   |
+--------+-------------------------------------------------------------+--------+
Enter the anime no:  [1]: 2
2019-10-20 19:14:14 archlinux-edupy anime_downloader.util[2155] INFO Selected Steins;Gate 0
2019-10-20 19:14:14 archlinux-edupy anime_downloader.sites.anime[2155] INFO Extracting episode info from page
2019-10-20 19:14:14 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG -----
2019-10-20 19:14:14 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG GET https://animeflv.net//anime/5110/steinsgate-0
2019-10-20 19:14:14 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG {}
2019-10-20 19:14:14 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; AMD Mac OS X 10_8_2) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/18.6.872'}
2019-10-20 19:14:14 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG -----
send: b'GET //anime/5110/steinsgate-0 HTTP/1.1\r\nHost: animeflv.net\r\nuser-agent: Mozilla/5.0 (Macintosh; AMD Mac OS X 10_8_2) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/18.6.872\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCookie: __cfduid=d546a509cb579f1a8d82395870e38208e1571591647; PHPSESSID=t6vvgaeltite3tj93q4oqncvg8; device=computer\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 20 Oct 2019 17:14:14 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: X-Powered-By: PHP/7.2.23
header: Expires: Thu, 19 Nov 1981 08:52:00 GMT
header: Cache-Control: no-store, no-cache, must-revalidate
header: Pragma: no-cache
header: Vary: Accept-Encoding
header: X-Powered-By: PleskLin
header: MS-Author-Via: DAV
header: X-Turbo-Charged-By: LiteSpeed
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 528ca07c1db4d681-MAD
header: Content-Encoding: gzip
2019-10-20 19:14:15 archlinux-edupy anime_downloader.session[2155] DEBUG uncached request
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG https://animeflv.net//anime/5110/steinsgate-0
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG /tmp/animedlohk_igd0/tmpj3f9c8yd
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG -----
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG GET https://animeflv.net//anime/5110/steinsgate-0
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG {}
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; AMD Mac OS X 10_8_2) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/18.6.872'}
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG -----
2019-10-20 19:14:15 archlinux-edupy anime_downloader.session[2155] DEBUG cached request
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG https://animeflv.net//anime/5110/steinsgate-0
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG /tmp/animedlohk_igd0/tmpilffok74
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.anime[2155] DEBUG EPISODE IDS: length: 24, ids: ['https://animeflv.net/ver/48716/steinsgate-0-1', 'https://animeflv.net/ver/48782/steinsgate-0-2', 'https://animeflv.net/ver/48850/steinsgate-0-3', 'https://animeflv.net/ver/48915/steinsgate-0-4', 'https://animeflv.net/ver/48985/steinsgate-0-5', 'https://animeflv.net/ver/49047/steinsgate-0-6', 'https://animeflv.net/ver/49116/steinsgate-0-7', 'https://animeflv.net/ver/49183/steinsgate-0-8', 'https://animeflv.net/ver/49249/steinsgate-0-9', 'https://animeflv.net/ver/49315/steinsgate-0-10', 'https://animeflv.net/ver/49409/steinsgate-0-11', 'https://animeflv.net/ver/49465/steinsgate-0-12', 'https://animeflv.net/ver/49513/steinsgate-0-13', 'https://animeflv.net/ver/49628/steinsgate-0-14', 'https://animeflv.net/ver/49688/steinsgate-0-15', 'https://animeflv.net/ver/49750/steinsgate-0-16', 'https://animeflv.net/ver/49810/steinsgate-0-17', 'https://animeflv.net/ver/49874/steinsgate-0-18', 'https://animeflv.net/ver/49937/steinsgate-0-19', 'https://animeflv.net/ver/50056/steinsgate-0-20', 'https://animeflv.net/ver/50109/steinsgate-0-21', 'https://animeflv.net/ver/50170/steinsgate-0-22', 'https://animeflv.net/ver/50232/steinsgate-0-23', 'https://animeflv.net/ver/50969/steinsgate-0-24']                                                                                                                                                                                                 
2019-10-20 19:14:15 archlinux-edupy anime_downloader.commands.dl[2155] INFO Found anime: Steins;Gate 0
2019-10-20 19:14:15 archlinux-edupy anime_downloader.commands.dl[2155] INFO Downloading to /home/edupy/Downloads/Steins;Gate 0
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.anime[2155] DEBUG Extracting stream info of id: https://animeflv.net/ver/48716/steinsgate-0-1
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG -----
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG GET https://animeflv.net/ver/48716/steinsgate-0-1
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG {}
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; AMD Mac OS X 10_8_2) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/18.6.872'}
2019-10-20 19:14:15 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG -----
send: b'GET /ver/48716/steinsgate-0-1 HTTP/1.1\r\nHost: animeflv.net\r\nuser-agent: Mozilla/5.0 (Macintosh; AMD Mac OS X 10_8_2) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/18.6.872\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCookie: __cfduid=d546a509cb579f1a8d82395870e38208e1571591647; PHPSESSID=t6vvgaeltite3tj93q4oqncvg8; device=computer\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 20 Oct 2019 17:14:15 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: X-Powered-By: PHP/7.2.23
header: Expires: Thu, 19 Nov 1981 08:52:00 GMT
header: Cache-Control: no-store, no-cache, must-revalidate
header: Pragma: no-cache
header: Vary: Accept-Encoding
header: X-Powered-By: PleskLin
header: MS-Author-Via: DAV
header: X-Turbo-Charged-By: LiteSpeed
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 528ca0838e7ad681-MAD
header: Content-Encoding: gzip
2019-10-20 19:14:15 archlinux-edupy anime_downloader.session[2155] DEBUG uncached request
2019-10-20 19:14:16 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG https://animeflv.net/ver/48716/steinsgate-0-1
2019-10-20 19:14:16 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG /tmp/animedlohk_igd0/tmp1q5pxxmy
2019-10-20 19:14:16 archlinux-edupy anime_downloader.sites.anime[2155] DEBUG Sources : 
2019-10-20 19:14:16 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG -----
2019-10-20 19:14:16 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG GET https://animeflv.net/ver/48716/steinsgate-0-1
2019-10-20 19:14:16 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG {}
2019-10-20 19:14:16 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; AMD Mac OS X 10_8_2) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/18.6.872'}
2019-10-20 19:14:16 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG -----
2019-10-20 19:14:16 archlinux-edupy anime_downloader.session[2155] DEBUG cached request
2019-10-20 19:14:16 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG https://animeflv.net/ver/48716/steinsgate-0-1
2019-10-20 19:14:16 archlinux-edupy anime_downloader.sites.helpers.request[2155] DEBUG /tmp/animedlohk_igd0/tmptov9n_c7
2019-10-20 19:14:16 archlinux-edupy anime_downloader.sites.anime[2155] DEBUG Sources : 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 336, in source
    sitename, url = self._sources[index]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader==4.0.0', 'console_scripts', 'anime')()
  File "/usr/lib/python3.7/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/anime_downloader/commands/dl.py", line 108, in command
    for episode in animes:
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 198, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 293, in __init__
    try_data()
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 291, in try_data
    self.source().stream_url
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 338, in source
    return self._sources[index]
TypeError: 'NoneType' object is not subscriptable


```

**Comment by andrewlef** [comment]
Animeflv appears to be broken at the moment.  I assume it's due to changes in the site.  Not exactly sure.  I've come up with a quick and dirty fix to get it working again.

**Comment by ESPGranEdu** [comment]
Yep, that fixed the problem, but there's a bunch of animes like Jojo Golden Wind that for some reason returns an index out of range when it searchs for number of episodes

´´´

anime dl "Jojo Golden Wind" -xd "{aria2}" --provider animeflv
´´´
<details>
<summary>LOG</summary>
```
pi@raspberrypi:~/Downloads $ anime dl "Jojo Golden Wind" -xd "{aria2}" --provider animeflv
anime: anime-downloader 4.0.1
+--------+-----------------------------------------+--------+
|      1 | JoJo no Kimyou na Bouken: Ougon no Kaze |        |
|--------+-----------------------------------------+--------|
|   SlNo | Title                                   | Meta   |
+--------+-----------------------------------------+--------+
Enter the anime no:  [1]: 
anime: Selected JoJo no Kimyou na Bouken: Ougon no Kaze
anime: Extracting episode info from page
anime: Found anime: JoJo no Kimyou na Bouken: Ougon no Kaze
anime: Downloading to /home/pi/Downloads
ERROR: list index out of range

```

**Comment by andrewlef** [comment]
That error occurs when the file hoster (streamango) returns a file not found response.  In other words, the link is no good. You can try to download the video manually from one of the other servers.  Currently Streamango is the only supported file host for that site.
