### ISSUE TITLE
ERROR: 405 Client Error: Not Allowed for url: 

### ISSUE THREAD

**Issue by gingerbeardman** [vn-ki/anime-downloader#256]
**Describe the bug**

ERROR: 405 Client Error: Not Allowed for url: 

Downloading from kissanime

**To reproduce**

```
anime dl "Angel's Egg"
```

<details>
<summary>LOG</summary>

```
$ anime --log-level DEBUG dl "Angel's Egg"
2019-10-24 17:43:49 matt.local anime_downloader.util[26961] INFO anime-downloader 4.0.1
2019-10-24 17:43:49 matt.local anime_downloader.util[26961] DEBUG Platform: Darwin-18.7.0-x86_64-i386-64bit
2019-10-24 17:43:49 matt.local anime_downloader.util[26961] DEBUG Python 3.7.4
2019-10-24 17:43:49 matt.local anime_downloader.sites.helpers.request[26961] DEBUG HTML file temp_dir: /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedl26fi6763
2019-10-24 17:43:49 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
2019-10-24 17:43:49 matt.local anime_downloader.sites.helpers.request[26961] DEBUG POST https://kissanime.ru/Search/Anime
2019-10-24 17:43:49 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {'data': {'keyword': "Angel's Egg"}}
2019-10-24 17:43:49 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0', 'referer': 'https://kissanime.ru'}
2019-10-24 17:43:49 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
send: b'POST /Search/Anime HTTP/1.1\r\nHost: kissanime.ru\r\nuser-agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://kissanime.ru\r\nContent-Length: 21\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'keyword=Angel%27s+Egg'
reply: 'HTTP/1.1 503 Service Temporarily Unavailable\r\n'
header: Date: Thu, 24 Oct 2019 16:43:49 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: close
header: X-Frame-Options: SAMEORIGIN
header: Set-Cookie: __cfduid=d86008e99842001ad453c8578984144931571935429; expires=Fri, 23-Oct-20 16:43:49 GMT; path=/; domain=.kissanime.ru; HttpOnly
header: Cache-Control: no-cache
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Vary: Accept-Encoding
header: Server: cloudflare
header: CF-RAY: 52ad69722f3fdc13-LHR
2019-10-24 17:43:49 matt.local anime_downloader.session[26961] DEBUG uncached request
send: b'POST /cdn-cgi/l/chk_jschl?s=2c336aa864c7c4ebcb40cb9fc5adbd33ff572f2a-1571935429-0-AY6ywLPOOOL8Oz0bGpUGZhiMelI3KV9gQZdDASZZ7INaoIsuwsw7e3JfMEuGxnPFkMefLRkLJmdvZq%2FhUFYWJubtsyxYcdKek9G0px9cLzZZbT8g1IzoshnY9X9z8qNJLu68IiRFLgVFey2FgHzaEDM%3D&jschl_vc=62704b198a264c266b214fff3297700a&pass=1571935433.466-Lex0NAVvrV&jschl_answer=13.4918527296 HTTP/1.1\r\nHost: kissanime.ru\r\nuser-agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nReferer: https://kissanime.ru/Search/Anime\r\nCookie: __cfduid=d86008e99842001ad453c8578984144931571935429\r\nContent-Length: 21\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'keyword=Angel%27s+Egg'
reply: 'HTTP/1.1 302 Moved Temporarily\r\n'
header: Date: Thu, 24 Oct 2019 16:43:53 GMT
header: Content-Type: text/html
header: Content-Length: 159
header: Connection: keep-alive
header: Set-Cookie: cf_clearance=4d0eeff4aeacf474e76e73be6ac7953fba906a1d-1571935433-0-150; path=/; expires=Fri, 25-Oct-19 17:43:53 GMT; domain=.kissanime.ru; HttpOnly
header: Location: /Search/Anime
header: Server: cloudflare
header: CF-RAY: 52ad698bdf32ce2b-LHR
header: X-Frame-Options: SAMEORIGIN
2019-10-24 17:43:53 matt.local anime_downloader.session[26961] DEBUG uncached request
send: b'POST /Search/Anime HTTP/1.1\r\nHost: kissanime.ru\r\nuser-agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://kissanime.ru\r\nCookie: __cfduid=d86008e99842001ad453c8578984144931571935429; cf_clearance=4d0eeff4aeacf474e76e73be6ac7953fba906a1d-1571935433-0-150\r\nContent-Length: 21\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'keyword=Angel%27s+Egg'
reply: 'HTTP/1.1 302 Found\r\n'
header: Date: Thu, 24 Oct 2019 16:43:53 GMT
header: Content-Type: text/html; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Cache-Control: private
header: Location: /Anime/Angel-s-Egg
header: Set-Cookie: idtz=86.168.61.243-260823118; expires=Wed, 01-Jan-2020 00:00:00 GMT; path=/
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 52ad698c1fd7ce2b-LHR
2019-10-24 17:43:53 matt.local anime_downloader.session[26961] DEBUG uncached request
send: b'GET /Anime/Angel-s-Egg HTTP/1.1\r\nHost: kissanime.ru\r\nuser-agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://kissanime.ru\r\nCookie: __cfduid=d86008e99842001ad453c8578984144931571935429; cf_clearance=4d0eeff4aeacf474e76e73be6ac7953fba906a1d-1571935433-0-150; idtz=86.168.61.243-260823118\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Thu, 24 Oct 2019 16:43:54 GMT
header: Content-Type: text/html; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Cache-Control: private
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 52ad698ded92ce2b-LHR
header: Content-Encoding: gzip
2019-10-24 17:43:54 matt.local anime_downloader.session[26961] DEBUG uncached request
2019-10-24 17:43:54 matt.local anime_downloader.sites.helpers.request[26961] DEBUG https://kissanime.ru/Anime/Angel-s-Egg
2019-10-24 17:43:54 matt.local anime_downloader.sites.helpers.request[26961] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedl26fi6763/tmpqk4owr8i
+--------+-------------+--------+
|      1 | Angel's Egg |        |
|--------+-------------+--------|
|   SlNo | Title       | Meta   |
+--------+-------------+--------+
Enter the anime no:  [1]: 1
2019-10-24 17:43:56 matt.local anime_downloader.util[26961] INFO Selected Angel's Egg
2019-10-24 17:43:56 matt.local anime_downloader.sites.anime[26961] INFO Extracting episode info from page
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG GET https://kissanime.ru/Anime/Angel-s-Egg
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {}
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0', 'referer': 'https://kissanime.ru'}
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
2019-10-24 17:43:56 matt.local anime_downloader.session[26961] DEBUG cached request
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG https://kissanime.ru/Anime/Angel-s-Egg
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedl26fi6763/tmptcwqqpe6
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG GET https://kissanime.ru/Anime/Angel-s-Egg
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {}
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0', 'referer': 'https://kissanime.ru'}
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
2019-10-24 17:43:56 matt.local anime_downloader.session[26961] DEBUG cached request
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG https://kissanime.ru/Anime/Angel-s-Egg
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedl26fi6763/tmptll4gi4n
2019-10-24 17:43:56 matt.local anime_downloader.sites.kissanime[26961] DEBUG Unfiltered episodes : ['https://kissanime.ru/Anime/Angel-s-Egg/Promotional?id=35612', 'https://kissanime.ru/Anime/Angel-s-Egg/Movie?id=35632', 'https://kissanime.ru/Anime/Angel-s-Egg/FelineYogi-720p?id=53338']
2019-10-24 17:43:56 matt.local anime_downloader.sites.kissanime[26961] DEBUG Filtered episodes : ['https://kissanime.ru/Anime/Angel-s-Egg/Promotional?id=35612', 'https://kissanime.ru/Anime/Angel-s-Egg/Movie?id=35632', 'https://kissanime.ru/Anime/Angel-s-Egg/FelineYogi-720p?id=53338']
2019-10-24 17:43:56 matt.local anime_downloader.sites.anime[26961] DEBUG EPISODE IDS: length: 3, ids: ['https://kissanime.ru/Anime/Angel-s-Egg/FelineYogi-720p?id=53338', 'https://kissanime.ru/Anime/Angel-s-Egg/Movie?id=35632', 'https://kissanime.ru/Anime/Angel-s-Egg/Promotional?id=35612']
2019-10-24 17:43:56 matt.local anime_downloader.commands.dl[26961] INFO Found anime: Angel's Egg
2019-10-24 17:43:56 matt.local anime_downloader.commands.dl[26961] INFO Downloading to /Users/matt/Downloads/1234_JD
2019-10-24 17:43:56 matt.local anime_downloader.sites.anime[26961] DEBUG Extracting stream info of id: https://kissanime.ru/Anime/Angel-s-Egg/FelineYogi-720p?id=53338
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG GET https://kissanime.ru/Anime/Angel-s-Egg/FelineYogi-720p?id=53338&s=rapidvideo
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {}
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0', 'referer': 'https://kissanime.ru'}
2019-10-24 17:43:56 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
send: b'GET /Anime/Angel-s-Egg/FelineYogi-720p?id=53338&s=rapidvideo HTTP/1.1\r\nHost: kissanime.ru\r\nuser-agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/4.0.211.2 Safari/532.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://kissanime.ru\r\nCookie: __cfduid=d86008e99842001ad453c8578984144931571935429; cf_clearance=4d0eeff4aeacf474e76e73be6ac7953fba906a1d-1571935433-0-150; idtz=86.168.61.243-260823118\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Thu, 24 Oct 2019 16:43:57 GMT
header: Content-Type: text/html; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Cache-Control: private
header: Set-Cookie: ASP.NET_SessionId=opipriqhramn0lbvoxlciga1; path=/; HttpOnly
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 52ad699caa92ce2b-LHR
header: Content-Encoding: gzip
2019-10-24 17:43:57 matt.local anime_downloader.session[26961] DEBUG uncached request
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG https://kissanime.ru/Anime/Angel-s-Egg/FelineYogi-720p?id=53338&s=rapidvideo
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedl26fi6763/tmpnjvziprj
2019-10-24 17:43:57 matt.local anime_downloader.sites.anime[26961] DEBUG Sources : 
2019-10-24 17:43:57 matt.local anime_downloader.extractors.rapidvideo[26961] DEBUG Calling Rapid url: https://www.novelplanet.me/v/env8d-rw091&q=720p
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG GET https://www.novelplanet.me/v/env8d-rw091&q=720p
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {}
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0', 'referer': 'https://www.novelplanet.me/v/env8d-rw091&q=720p'}
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
send: b'GET /v/env8d-rw091&q=720p HTTP/1.1\r\nHost: www.novelplanet.me\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://www.novelplanet.me/v/env8d-rw091&q=720p\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Thu, 24 Oct 2019 16:43:57 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d5a4e9b1b9ed6f8a368ee6778629e97541571935437; expires=Fri, 23-Oct-20 16:43:57 GMT; path=/; domain=.novelplanet.me; HttpOnly; Secure
header: Vary: Accept-Encoding
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
header: CF-Cache-Status: HIT
header: Age: 134
header: Expires: Thu, 24 Oct 2019 17:13:57 GMT
header: Cache-Control: public, max-age=1800
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 52ad69a3ae8a72a5-AMS
2019-10-24 17:43:57 matt.local anime_downloader.session[26961] DEBUG uncached request
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG https://www.novelplanet.me/v/env8d-rw091&q=720p
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedl26fi6763/tmptkhxkrmr
2019-10-24 17:43:57 matt.local anime_downloader.extractors.rapidvideo[26961] DEBUG Exception happened when getting normally
2019-10-24 17:43:57 matt.local anime_downloader.extractors.rapidvideo[26961] DEBUG list index out of range
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG POST https://www.novelplanet.me/v/env8d-rw091&q=720p
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {'data': {'confirm.x': 12, 'confirm.y': 12, 'block': 1}}
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0', 'referer': 'https://www.novelplanet.me/v/env8d-rw091&q=720p'}
2019-10-24 17:43:57 matt.local anime_downloader.sites.helpers.request[26961] DEBUG -----
send: b'POST /v/env8d-rw091&q=720p HTTP/1.1\r\nHost: www.novelplanet.me\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://www.novelplanet.me/v/env8d-rw091&q=720p\r\nCookie: __cfduid=d5a4e9b1b9ed6f8a368ee6778629e97541571935437\r\nContent-Length: 33\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'block=1&confirm.x=12&confirm.y=12'
reply: 'HTTP/1.1 405 Not Allowed\r\n'
header: Date: Thu, 24 Oct 2019 16:43:57 GMT
header: Content-Type: text/html
header: Content-Length: 163
header: Connection: keep-alive
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 52ad69a40ecf72a5-AMS
2019-10-24 17:43:57 matt.local anime_downloader.session[26961] DEBUG uncached request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/extractors/rapidvideo.py", line 62, in get_source
    return soup.find_all('source')[0].get('src')
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/extractors/rapidvideo.py", line 20, in _get_data
    stream_url = get_source(soup)
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/extractors/rapidvideo.py", line 64, in get_source
    return str(src_re.findall(str(soup))[0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/anime", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/commands/dl.py", line 108, in command
    for episode in animes:
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 198, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 293, in __init__
    try_data()
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 291, in try_data
    self.source().stream_url
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/extractors/base_extractor.py", line 29, in stream_url
    self.get_data()
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/extractors/base_extractor.py", line 41, in get_data
    data = self._get_data()
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/extractors/rapidvideo.py", line 28, in _get_data
    }, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/sites/helpers/request.py", line 67, in setup_func
    res.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Not Allowed for url: https://www.novelplanet.me/v/env8d-rw091&q=720p


```

**Comment by andrewlef** [comment]
The video linked is/was hosted on rapidvideo.  Rapidvideo is dead.  Why not use a better site like gogo?

**Comment by gingerbeardman** [comment]
Who are you asking? I'm just a user.

**Comment by andrewlef** [comment]
Try this:  anime -ll DEBUG dl "angel"  -q 720p  --provider gogoanime

Also, make sure you're using the latest version of anime-downloader.  I rewrote some of the code for gogo, so it's been working pretty well now.

**Comment by gingerbeardman** [comment]
Thanks for your help. I am running 4.0.1 latest, I reinstall using `pip install -U git+https://github.com/vn-ki/anime-downloader.git` before every use (I may change when `brew` is up-to-date)

Anyway, your command does not find the movie "Angel's Egg" (but it does find a TV series with a similar name "Angel Egg")

- https://en.wikipedia.org/wiki/Angel%27s_Egg
- https://www.imdb.com/title/tt0208502/

I can still manually download the movies by visiting kissanime.ru myself, all of which downloads are hosted by Google User Content.

- https://kissanime.ru/Anime/Angel-s-Egg

So what's going on?

**Comment by andrewlef** [comment]
The problem is that the program code has only implemented downloading from rapidvideo servers for kissanime.  Since rapidvideo is dead, the kissanime implementation is currently broken.

**Comment by MichaelDavidJohnson** [comment]
I think people fixed KissAnime when they added selenium, will add to the new list nevertheless
