### ISSUE TITLE
kissanime introduced captcha

### ISSUE THREAD

**Issue by andrewlef** [vn-ki/anime-downloader#260]
**Describe the bug**

Looks like kissanime has a captcha now.  Looking over some code scrapes, the program gets stuck there and can't get to the link page.  I'd say kissanime is fully broken at the moment, given that rapidvideo was the only supported host.

Might make sense to insert some pre-emptive error handling until it's fixed.

**To reproduce**

```
anime -ll DEBUG dl "magus" -e 1  --provider kissanime 
```

<details>
<summary>LOG</summary>

```
iMac:~ user$ anime -ll DEBUG dl "magus" -e 1  --provider kissanime 
2019-10-27 23:36:18 iMac.local anime_downloader.util[32363] INFO anime-downloader 4.0.1
2019-10-27 23:36:18 iMac.local anime_downloader.util[32363] DEBUG Platform: Darwin-18.5.0-x86_64-i386-64bit
2019-10-27 23:36:18 iMac.local anime_downloader.util[32363] DEBUG Python 3.7.4
2019-10-27 23:36:18 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG HTML file temp_dir: /var/folders/sy/f41bjb5d2v743qrsz51t_z680000gn/T/animedlmdhff7e0
2019-10-27 23:36:18 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
2019-10-27 23:36:18 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG POST https://kissanime.ru/Search/Anime
2019-10-27 23:36:18 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {'data': {'keyword': 'magus'}}
2019-10-27 23:36:18 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {'user-agent': 'Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.65 Safari/535.11', 'referer': 'https://kissanime.ru'}
2019-10-27 23:36:18 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
send: b'POST /Search/Anime HTTP/1.1\r\nHost: kissanime.ru\r\nuser-agent: Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.65 Safari/535.11\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://kissanime.ru\r\nContent-Length: 13\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'keyword=magus'
reply: 'HTTP/1.1 503 Service Temporarily Unavailable\r\n'
header: Date: Mon, 28 Oct 2019 03:36:18 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: close
header: X-Frame-Options: SAMEORIGIN
header: Set-Cookie: __cfduid=d156eb5fa726ebc30decebbeaa24b06291572233778; expires=Tue, 27-Oct-20 03:36:18 GMT; path=/; domain=.kissanime.ru; HttpOnly
header: Cache-Control: no-cache
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Vary: Accept-Encoding
header: Server: cloudflare
header: CF-RAY: 52c9dd5bfe7de83d-EWR
2019-10-27 23:36:18 iMac.local anime_downloader.session[32363] DEBUG uncached request
send: b'POST /cdn-cgi/l/chk_jschl?s=d04d5346ba840de764b7943591499f62f37666a0-1572233778-0-AdAxpI3f3bPXoFhDBT3zKPkWPbmcqAEpVb1hdtgAwjX6BeQx0dylhB%2FY6IUMEyRTSru42nbxjQLC3qX8FC1KP1P6okCtwSazYsUwMtRVCKjCjAZqL3E%2FkVQi51adNSgOWumbm1wapqyxMPRQm%2ByV4QY%3D&jschl_vc=de3b68fc1438ebc38a8d198ff128d658&pass=1572233782.557-qVUs5KCgpS&jschl_answer=250.8785081960 HTTP/1.1\r\nHost: kissanime.ru\r\nuser-agent: Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.65 Safari/535.11\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nReferer: https://kissanime.ru/Search/Anime\r\nCookie: __cfduid=d156eb5fa726ebc30decebbeaa24b06291572233778\r\nContent-Length: 13\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'keyword=magus'
reply: 'HTTP/1.1 302 Moved Temporarily\r\n'
header: Date: Mon, 28 Oct 2019 03:36:22 GMT
header: Content-Type: text/html
header: Content-Length: 159
header: Connection: keep-alive
header: Set-Cookie: cf_clearance=860d71d493c0bbac8b5acf86cec2146decc9c472-1572233782-0-150; path=/; expires=Tue, 29-Oct-19 04:36:22 GMT; domain=.kissanime.ru; HttpOnly
header: Location: /Search/Anime
header: Server: cloudflare
header: CF-RAY: 52c9dd756b1699fc-EWR
header: X-Frame-Options: SAMEORIGIN
2019-10-27 23:36:22 iMac.local anime_downloader.session[32363] DEBUG uncached request
send: b'POST /Search/Anime HTTP/1.1\r\nHost: kissanime.ru\r\nuser-agent: Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.65 Safari/535.11\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://kissanime.ru\r\nCookie: __cfduid=d156eb5fa726ebc30decebbeaa24b06291572233778; cf_clearance=860d71d493c0bbac8b5acf86cec2146decc9c472-1572233782-0-150\r\nContent-Length: 13\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'keyword=magus'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Mon, 28 Oct 2019 03:36:23 GMT
header: Content-Type: text/html; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Cache-Control: private
header: Set-Cookie: idtz=68.0.238.177-327111660; expires=Wed, 01-Jan-2020 00:00:00 GMT; path=/
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 52c9dd759b3399fc-EWR
header: Content-Encoding: gzip
2019-10-27 23:36:23 iMac.local anime_downloader.session[32363] DEBUG uncached request
2019-10-27 23:36:23 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG https://kissanime.ru/Search/Anime
2019-10-27 23:36:23 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG /var/folders/sy/f41bjb5d2v743qrsz51t_z680000gn/T/animedlmdhff7e0/tmpclh53tie
2019-10-27 23:36:23 iMac.local anime_downloader.sites.kissanime[32363] DEBUG Maho Yome Episode 0
2019-10-27 23:36:23 iMac.local anime_downloader.sites.kissanime[32363] DEBUG Mahoutsukai no Yome (Dub)
2019-10-27 23:36:23 iMac.local anime_downloader.sites.kissanime[32363] DEBUG Mahoutsukai no Yome (Sub)
2019-10-27 23:36:23 iMac.local anime_downloader.sites.kissanime[32363] DEBUG Mahoutsukai no Yome: Hoshi Matsu Hito
2019-10-27 23:36:23 iMac.local anime_downloader.sites.kissanime[32363] DEBUG MahoYome
+--------+---------------------------------------+--------+
|      5 | MahoYome                              |        |
|      4 | Mahoutsukai no Yome: Hoshi Matsu Hito |        |
|      3 | Mahoutsukai no Yome (Sub)             |        |
|      2 | Mahoutsukai no Yome (Dub)             |        |
|      1 | Maho Yome Episode 0                   |        |
|--------+---------------------------------------+--------|
|   SlNo | Title                                 | Meta   |
+--------+---------------------------------------+--------+
Enter the anime no:  [1]: 2
2019-10-27 23:36:30 iMac.local anime_downloader.util[32363] INFO Selected Mahoutsukai no Yome (Dub)
2019-10-27 23:36:30 iMac.local anime_downloader.sites.anime[32363] INFO Extracting episode info from page
2019-10-27 23:36:30 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
2019-10-27 23:36:30 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG GET https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub
2019-10-27 23:36:30 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {}
2019-10-27 23:36:30 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {'user-agent': 'Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.65 Safari/535.11', 'referer': 'https://kissanime.ru'}
2019-10-27 23:36:30 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
send: b'GET /Anime/Mahoutsukai-no-Yome-Dub HTTP/1.1\r\nHost: kissanime.ru\r\nuser-agent: Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.65 Safari/535.11\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://kissanime.ru\r\nCookie: __cfduid=d156eb5fa726ebc30decebbeaa24b06291572233778; cf_clearance=860d71d493c0bbac8b5acf86cec2146decc9c472-1572233782-0-150; idtz=68.0.238.177-327111660\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Mon, 28 Oct 2019 03:36:31 GMT
header: Content-Type: text/html; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Cache-Control: private
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 52c9dda8bc0d99fc-EWR
header: Content-Encoding: gzip
2019-10-27 23:36:31 iMac.local anime_downloader.session[32363] DEBUG uncached request
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG /var/folders/sy/f41bjb5d2v743qrsz51t_z680000gn/T/animedlmdhff7e0/tmppl6uq7s_
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG GET https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {}
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {'user-agent': 'Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.65 Safari/535.11', 'referer': 'https://kissanime.ru'}
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
2019-10-27 23:36:31 iMac.local anime_downloader.session[32363] DEBUG cached request
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG /var/folders/sy/f41bjb5d2v743qrsz51t_z680000gn/T/animedlmdhff7e0/tmp8l_agohz
2019-10-27 23:36:31 iMac.local anime_downloader.sites.kissanime[32363] DEBUG Unfiltered episodes : ['https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-024?id=144869', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-023?id=144675', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-022?id=144377', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-021?id=144199', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-020?id=143997', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-019?id=143788', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-018?id=143582', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-017?id=143397', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-016?id=143227', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-015?id=143073', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-014?id=142899', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-013?id=142681', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-012?id=142297', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-011?id=142020', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-010?id=141881', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-009?id=141715', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-008?id=141468', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-007?id=141171', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-006?id=140944', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-005?id=140766', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-004?id=140564', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-003?id=140413', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-002?id=140200', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-001?id=140011']
2019-10-27 23:36:31 iMac.local anime_downloader.sites.kissanime[32363] DEBUG Filtered episodes : ['https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-024?id=144869', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-023?id=144675', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-022?id=144377', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-021?id=144199', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-020?id=143997', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-019?id=143788', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-018?id=143582', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-017?id=143397', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-016?id=143227', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-015?id=143073', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-014?id=142899', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-013?id=142681', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-012?id=142297', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-011?id=142020', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-010?id=141881', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-009?id=141715', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-008?id=141468', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-007?id=141171', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-006?id=140944', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-005?id=140766', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-004?id=140564', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-003?id=140413', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-002?id=140200', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-001?id=140011']
2019-10-27 23:36:31 iMac.local anime_downloader.sites.anime[32363] DEBUG EPISODE IDS: length: 24, ids: ['https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-001?id=140011', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-002?id=140200', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-003?id=140413', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-004?id=140564', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-005?id=140766', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-006?id=140944', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-007?id=141171', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-008?id=141468', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-009?id=141715', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-010?id=141881', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-011?id=142020', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-012?id=142297', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-013?id=142681', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-014?id=142899', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-015?id=143073', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-016?id=143227', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-017?id=143397', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-018?id=143582', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-019?id=143788', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-020?id=143997', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-021?id=144199', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-022?id=144377', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-023?id=144675', 'https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-024?id=144869']
2019-10-27 23:36:31 iMac.local anime_downloader.commands.dl[32363] INFO Found anime: Mahoutsukai no Yome (Dub)
2019-10-27 23:36:31 iMac.local anime_downloader.sites.anime[32363] DEBUG Extracting stream info of id: https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-001?id=140011
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG GET https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-001?id=140011&s=rapidvideo
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {}
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {'user-agent': 'Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.65 Safari/535.11', 'referer': 'https://kissanime.ru'}
2019-10-27 23:36:31 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
send: b'GET /Anime/Mahoutsukai-no-Yome-Dub/Episode-001?id=140011&s=rapidvideo HTTP/1.1\r\nHost: kissanime.ru\r\nuser-agent: Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.65 Safari/535.11\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://kissanime.ru\r\nCookie: __cfduid=d156eb5fa726ebc30decebbeaa24b06291572233778; cf_clearance=860d71d493c0bbac8b5acf86cec2146decc9c472-1572233782-0-150; idtz=68.0.238.177-327111660\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Mon, 28 Oct 2019 03:36:32 GMT
header: Content-Type: text/html; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Cache-Control: private
header: Set-Cookie: ASP.NET_SessionId=ce0y2lbxxgzj2vodv1njkscc; path=/; HttpOnly
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 52c9ddac9f4f99fc-EWR
header: Content-Encoding: gzip
2019-10-27 23:36:32 iMac.local anime_downloader.session[32363] DEBUG uncached request
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG https://kissanime.ru/Anime/Mahoutsukai-no-Yome-Dub/Episode-001?id=140011&s=rapidvideo
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG /var/folders/sy/f41bjb5d2v743qrsz51t_z680000gn/T/animedlmdhff7e0/tmpe135zs6v
2019-10-27 23:36:32 iMac.local anime_downloader.sites.anime[32363] DEBUG Sources : 
2019-10-27 23:36:32 iMac.local anime_downloader.extractors.rapidvideo[32363] DEBUG Calling Rapid url: https://www.novelplanet.me/v/4lo0pmqrx9q&q=720p
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG GET https://www.novelplanet.me/v/4lo0pmqrx9q&q=720p
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {}
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0', 'referer': 'https://www.novelplanet.me/v/4lo0pmqrx9q&q=720p'}
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
send: b'GET /v/4lo0pmqrx9q&q=720p HTTP/1.1\r\nHost: www.novelplanet.me\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://www.novelplanet.me/v/4lo0pmqrx9q&q=720p\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Mon, 28 Oct 2019 03:36:32 GMT
header: Content-Type: text/html
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d137fe9d686cebd05ab5877555d0589e81572233792; expires=Tue, 27-Oct-20 03:36:32 GMT; path=/; domain=.novelplanet.me; HttpOnly; Secure
header: Last-Modified: Thu, 24 Oct 2019 21:02:05 GMT
header: ETag: W/"5db2114d-264"
header: CF-Cache-Status: MISS
header: Expires: Mon, 28 Oct 2019 04:06:32 GMT
header: Cache-Control: public, max-age=1800
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Vary: Accept-Encoding
header: Server: cloudflare
header: CF-RAY: 52c9ddb319cde6e8-EWR
header: Content-Encoding: gzip
2019-10-27 23:36:32 iMac.local anime_downloader.session[32363] DEBUG uncached request
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG https://www.novelplanet.me/v/4lo0pmqrx9q&q=720p
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG /var/folders/sy/f41bjb5d2v743qrsz51t_z680000gn/T/animedlmdhff7e0/tmp4_tsbenv
2019-10-27 23:36:32 iMac.local anime_downloader.extractors.rapidvideo[32363] DEBUG Exception happened when getting normally
2019-10-27 23:36:32 iMac.local anime_downloader.extractors.rapidvideo[32363] DEBUG list index out of range
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG POST https://www.novelplanet.me/v/4lo0pmqrx9q&q=720p
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {'data': {'confirm.x': 12, 'confirm.y': 12, 'block': 1}}
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0', 'referer': 'https://www.novelplanet.me/v/4lo0pmqrx9q&q=720p'}
2019-10-27 23:36:32 iMac.local anime_downloader.sites.helpers.request[32363] DEBUG -----
send: b'POST /v/4lo0pmqrx9q&q=720p HTTP/1.1\r\nHost: www.novelplanet.me\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nreferer: https://www.novelplanet.me/v/4lo0pmqrx9q&q=720p\r\nCookie: __cfduid=d137fe9d686cebd05ab5877555d0589e81572233792\r\nContent-Length: 33\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'block=1&confirm.x=12&confirm.y=12'
reply: 'HTTP/1.1 405 Not Allowed\r\n'
header: Date: Mon, 28 Oct 2019 03:36:33 GMT
header: Content-Type: text/html
header: Content-Length: 163
header: Connection: keep-alive
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 52c9ddb56fbfe6e8-EWR
2019-10-27 23:36:33 iMac.local anime_downloader.session[32363] DEBUG uncached request
Traceback (most recent call last):
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/extractors/rapidvideo.py", line 62, in get_source
    return soup.find_all('source')[0].get('src')
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/extractors/rapidvideo.py", line 20, in _get_data
    stream_url = get_source(soup)
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/extractors/rapidvideo.py", line 64, in get_source
    return str(src_re.findall(str(soup))[0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader', 'console_scripts', 'anime')()
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/cli.py", line 53, in main
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/commands/dl.py", line 96, in command
    animes = util.parse_ep_str(anime, episode_range)
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/util.py", line 139, in parse_ep_str
    episodes.append(anime[int(episode_grammar) - 1])
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/sites/anime.py", line 185, in __getitem__
    ep_no=ep_id[0])
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/sites/anime.py", line 293, in __init__
    try_data()
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/sites/anime.py", line 291, in try_data
    self.source().stream_url
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/extractors/base_extractor.py", line 29, in stream_url
    self.get_data()
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/extractors/base_extractor.py", line 41, in get_data
    data = self._get_data()
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/extractors/rapidvideo.py", line 28, in _get_data
    }, headers=headers)
  File "/Users/user/Documents/GitHub/anime-downloader/anime_downloader/sites/helpers/request.py", line 67, in setup_func
    res.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Not Allowed for url: https://www.novelplanet.me/v/4lo0pmqrx9q&q=720p



```

**Comment by MichaelDavidJohnson** [comment]
'Fixed' with selenium. It should work now. Reopen if it doesn't
