### ISSUE TITLE
Animeflix: Empty name, odd file names and no downloads?

### ISSUE THREAD

**Issue by IngwiePhoenix** [vn-ki/anime-downloader#276]
**Describe the bug**
When passing a URL or using the integrated search function in order to download an anime, the name of the detected series stays blank and the downloads look...off. No folder is created, and the filenames are simply `_NN.mp4`, with NN being a two digit number.

Looking at the debug output, it looks like some API changes had been made (like `{}.slug` being missing). I also ran the program with `-ll DEBUG` after it seemed to be stuck and I am just gonna let it run for a while and see what happens. But I doubt it would download everything - or rather, nothing at all, since it seems kinda broken.

Also: Being able to just download the dubs would be a nice option - but I dont mind having to manually delete them :)

**To reproduce**
```
$ anime dl "https://animeflix.io/shows/nanbaka"
```

<details>
<summary>LOG</summary>

```
ingwie@macmini.local /V/U/Animes $ anime -ll DEBUG dl "https://animeflix.io/shows/nanbaka"
2019-12-29 14:46:50 macmini.local anime_downloader.util[1028] INFO anime-downloader 4.0.1
2019-12-29 14:46:50 macmini.local anime_downloader.util[1028] DEBUG Platform: Darwin-19.0.0-x86_64-i386-64bit
2019-12-29 14:46:50 macmini.local anime_downloader.util[1028] DEBUG Python 3.7.3
2019-12-29 14:46:50 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG HTML file temp_dir: /var/folders/dx/wzf8sqqn0l75tz9c6z7mg0_c0000gn/T/animedl_kz9u3_z
2019-12-29 14:46:50 macmini.local anime_downloader.sites.anime[1028] INFO Extracting episode info from page
2019-12-29 14:46:50 macmini.local anime_downloader.sites.anime[1028] DEBUG Metadata scraping error: 'AnimeFlix' object has no attribute 'slug'
2019-12-29 14:46:50 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG -----
2019-12-29 14:46:50 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG GET https://www.animeflix.io/api/anime-schema
2019-12-29 14:46:50 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG {'params': {'slug': 'nanbaka'}}
2019-12-29 14:46:50 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20'}
2019-12-29 14:46:50 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG -----
send: b'GET /api/anime-schema?slug=nanbaka HTTP/1.1\r\nHost: www.animeflix.io\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Date: Sun, 29 Dec 2019 13:46:51 GMT
header: Content-Type: text/html
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d2877cc14f805583448551594ac21d7e51577627211; expires=Tue, 28-Jan-20 13:46:51 GMT; path=/; domain=.animeflix.io; HttpOnly; SameSite=Lax; Secure
header: Location: https://animeflix.io/api/anime-schema?slug=nanbaka
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 54cc38f4de1d9766-FRA
2019-12-29 14:46:51 macmini.local anime_downloader.session[1028] DEBUG uncached request
send: b'GET /api/anime-schema?slug=nanbaka HTTP/1.1\r\nHost: animeflix.io\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCookie: __cfduid=d2877cc14f805583448551594ac21d7e51577627211\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 29 Dec 2019 13:47:13 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: X-Powered-By: PHP/7.3.6
header: Cache-Control: no-cache, private
header: X-RateLimit-Limit: 60
header: X-RateLimit-Remaining: 59
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 54cc38f72a64637d-FRA
header: Content-Encoding: gzip
2019-12-29 14:47:13 macmini.local anime_downloader.session[1028] DEBUG uncached request
2019-12-29 14:47:13 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG https://animeflix.io/api/anime-schema?slug=nanbaka
2019-12-29 14:47:13 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG /var/folders/dx/wzf8sqqn0l75tz9c6z7mg0_c0000gn/T/animedl_kz9u3_z/tmpqg08b_2c
2019-12-29 14:47:13 macmini.local anime_downloader.sites.anime[1028] DEBUG EPISODE IDS: length: 13, ids: ['https://www.animeflix.io/shows/shows/nanbaka/episode-1-733766-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-2-109494-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-3-138789-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-4-736956-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-5-356565-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-6-905296-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-7-736334-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-8-839657-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-9-119973-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-10-329140-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-11-980953-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-12-585508-sub', 'https://www.animeflix.io/shows/shows/nanbaka/episode-13-496866-sub']
2019-12-29 14:47:13 macmini.local anime_downloader.commands.dl[1028] INFO Found anime: 
2019-12-29 14:47:13 macmini.local anime_downloader.commands.dl[1028] INFO Downloading to /Volumes/UserSpace/Animes
2019-12-29 14:47:13 macmini.local anime_downloader.sites.anime[1028] DEBUG Extracting stream info of id: https://www.animeflix.io/shows/shows/nanbaka/episode-1-733766-sub
2019-12-29 14:47:13 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG -----
2019-12-29 14:47:13 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG GET https://animeflix.io/api/episode
2019-12-29 14:47:13 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG {'params': {'episode_num': 1, 'slug': 'nanbaka'}}
2019-12-29 14:47:13 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20'}
2019-12-29 14:47:13 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG -----
send: b'GET /api/episode?episode_num=1&slug=nanbaka HTTP/1.1\r\nHost: animeflix.io\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCookie: __cfduid=d2877cc14f805583448551594ac21d7e51577627211\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 29 Dec 2019 13:47:29 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: X-Powered-By: PHP/7.3.6
header: Cache-Control: no-cache, private
header: X-RateLimit-Limit: 60
header: X-RateLimit-Remaining: 58
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 54cc39811b87637d-FRA
header: Content-Encoding: gzip
2019-12-29 14:47:29 macmini.local anime_downloader.session[1028] DEBUG uncached request
2019-12-29 14:47:29 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG https://animeflix.io/api/episode?episode_num=1&slug=nanbaka
2019-12-29 14:47:29 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG /var/folders/dx/wzf8sqqn0l75tz9c6z7mg0_c0000gn/T/animedl_kz9u3_z/tmpbg0z9o71
2019-12-29 14:47:29 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG -----
2019-12-29 14:47:29 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG GET https://animeflix.io/api/videos?episode_id=7905
2019-12-29 14:47:29 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG {}
2019-12-29 14:47:29 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20'}
2019-12-29 14:47:29 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG -----
send: b'GET /api/videos?episode_id=7905 HTTP/1.1\r\nHost: animeflix.io\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCookie: __cfduid=d2877cc14f805583448551594ac21d7e51577627211\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 29 Dec 2019 13:47:44 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: X-Powered-By: PHP/7.3.6
header: Cache-Control: no-cache, private
header: X-RateLimit-Limit: 60
header: X-RateLimit-Remaining: 57
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 54cc39e46d1e637d-FRA
header: Content-Encoding: gzip
2019-12-29 14:47:44 macmini.local anime_downloader.session[1028] DEBUG uncached request
2019-12-29 14:47:44 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG https://animeflix.io/api/videos?episode_id=7905
2019-12-29 14:47:44 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG /var/folders/dx/wzf8sqqn0l75tz9c6z7mg0_c0000gn/T/animedl_kz9u3_z/tmp_wi1nl8t
2019-12-29 14:47:44 macmini.local anime_downloader.sites.anime[1028] DEBUG Sources : 
2019-12-29 14:47:44 macmini.local anime_downloader.util[1028] DEBUG cmd: {aria2}
DEBUG:anime_downloader.util:cmd: {aria2}
2019-12-29 14:47:44 macmini.local anime_downloader.util[1028] DEBUG episode: <anime_downloader.sites.animeflix.AnimeFlixEpisode object at 0x10373a400>
DEBUG:anime_downloader.util:episode: <anime_downloader.sites.animeflix.AnimeFlixEpisode object at 0x10373a400>
2019-12-29 14:47:44 macmini.local anime_downloader.util[1028] DEBUG file format: {anime_title}/{anime_title}_{ep_no}
DEBUG:anime_downloader.util:file format: {anime_title}/{anime_title}_{ep_no}
2019-12-29 14:47:44 macmini.local anime_downloader.util[1028] DEBUG formatted cmd: aria2c https://dl.v.vrv.co/evs/d561ae189894233abaa48d34163ea45c/assets/8a15436472e612bade90ceb5484f8316_,3581698.mp4,3581699.mp4,3581697.mp4,3581696.mp4,3581695.mp4,.urlset/master.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9kbC52LnZydi5jby9ldnMvZDU2MWFlMTg5ODk0MjMzYWJhYTQ4ZDM0MTYzZWE0NWMvYXNzZXRzLzhhMTU0MzY0NzJlNjEyYmFkZTkwY2ViNTQ4NGY4MzE2XywzNTgxNjk4Lm1wNCwzNTgxNjk5Lm1wNCwzNTgxNjk3Lm1wNCwzNTgxNjk2Lm1wNCwzNTgxNjk1Lm1wNCwudXJsc2V0L21hc3Rlci5tM3U4IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTc3NzQ0MTY0fX19XX0_&Signature=XaX9EJRqFvGyu4lX~x2npz~-8P8p7tEhye4dklQYtiTV2i6NYBOnty-qBjNEIOu8k6IXjcdxBSg-W~JQ~yq7jlgHRpi2ojLxMWAOASJ6MVSYgMn7qSn1j3ns2LhIj49mM5pk6e8QjwSnbwr9gYqL8mLdR3Q9Lunb-EDJYoe5Uu~FD7EV9iUVYlIVqhYdsvr5xFsXAf-UByrYmFqdYRsI~liD5LV7kZxlxfkHaNDWXnncCeb~oDTBykd-THK9~sqbLqkdEgSFIH9zyT~CV2VLpN-5prg8RYbkif03yd46BER14haEzitzLZX3mCJsdNDXIhXVv4L2g0xETeemjaxP9A__&Key-Pair-Id=DLVR -x 12 -s 12 -j 12 -k 10M -o /_01.mp4 --continue=true --dir=/Volumes/UserSpace/Animes --stream-piece-selector=inorder --min-split-size=5M --referer=None --check-certificate=false
DEBUG:anime_downloader.util:formatted cmd: aria2c https://dl.v.vrv.co/evs/d561ae189894233abaa48d34163ea45c/assets/8a15436472e612bade90ceb5484f8316_,3581698.mp4,3581699.mp4,3581697.mp4,3581696.mp4,3581695.mp4,.urlset/master.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9kbC52LnZydi5jby9ldnMvZDU2MWFlMTg5ODk0MjMzYWJhYTQ4ZDM0MTYzZWE0NWMvYXNzZXRzLzhhMTU0MzY0NzJlNjEyYmFkZTkwY2ViNTQ4NGY4MzE2XywzNTgxNjk4Lm1wNCwzNTgxNjk5Lm1wNCwzNTgxNjk3Lm1wNCwzNTgxNjk2Lm1wNCwzNTgxNjk1Lm1wNCwudXJsc2V0L21hc3Rlci5tM3U4IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTc3NzQ0MTY0fX19XX0_&Signature=XaX9EJRqFvGyu4lX~x2npz~-8P8p7tEhye4dklQYtiTV2i6NYBOnty-qBjNEIOu8k6IXjcdxBSg-W~JQ~yq7jlgHRpi2ojLxMWAOASJ6MVSYgMn7qSn1j3ns2LhIj49mM5pk6e8QjwSnbwr9gYqL8mLdR3Q9Lunb-EDJYoe5Uu~FD7EV9iUVYlIVqhYdsvr5xFsXAf-UByrYmFqdYRsI~liD5LV7kZxlxfkHaNDWXnncCeb~oDTBykd-THK9~sqbLqkdEgSFIH9zyT~CV2VLpN-5prg8RYbkif03yd46BER14haEzitzLZX3mCJsdNDXIhXVv4L2g0xETeemjaxP9A__&Key-Pair-Id=DLVR -x 12 -s 12 -j 12 -k 10M -o /_01.mp4 --continue=true --dir=/Volumes/UserSpace/Animes --stream-piece-selector=inorder --min-split-size=5M --referer=None --check-certificate=false

12/29 14:47:44 [NOTICE] Downloading 1 item(s)

12/29 14:47:44 [NOTICE] GID#04975552cd357958 - Download has already completed: /Volumes/UserSpace/Animes//_01.mp4

12/29 14:47:44 [NOTICE] Download complete: /Volumes/UserSpace/Animes//_01.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
049755|OK  |       0B/s|/Volumes/UserSpace/Animes//_01.mp4

Status Legend:
(OK):download completed.
2019-12-29 14:47:44 macmini.local anime_downloader.sites.anime[1028] DEBUG Extracting stream info of id: https://www.animeflix.io/shows/shows/nanbaka/episode-2-109494-sub
DEBUG:anime_downloader.sites.anime:Extracting stream info of id: https://www.animeflix.io/shows/shows/nanbaka/episode-2-109494-sub
2019-12-29 14:47:44 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG -----
DEBUG:anime_downloader.sites.helpers.request:-----
2019-12-29 14:47:44 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG GET https://animeflix.io/api/episode
DEBUG:anime_downloader.sites.helpers.request:GET https://animeflix.io/api/episode
2019-12-29 14:47:44 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG {'params': {'episode_num': 2, 'slug': 'nanbaka'}}
DEBUG:anime_downloader.sites.helpers.request:{'params': {'episode_num': 2, 'slug': 'nanbaka'}}
2019-12-29 14:47:44 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20'}
DEBUG:anime_downloader.sites.helpers.request:{'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20'}
2019-12-29 14:47:44 macmini.local anime_downloader.sites.helpers.request[1028] DEBUG -----
DEBUG:anime_downloader.sites.helpers.request:-----
send: b'GET /api/episode?episode_num=2&slug=nanbaka HTTP/1.1\r\nHost: animeflix.io\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCookie: __cfduid=d2877cc14f805583448551594ac21d7e51577627211\r\n\r\n'
```

**UPDATE**
After waiting for a little while, this error shows up:

```
DEBUG:anime_downloader.session:uncached request
Traceback (most recent call last):
  File "/Users/ingwie/.local/bin/anime", line 8, in <module>
    sys.exit(main())
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/anime_downloader/commands/dl.py", line 108, in command
    for episode in animes:
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 198, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 293, in __init__
    try_data()
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 289, in try_data
    self.get_data()
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 349, in get_data
    self._sources = self._get_sources()
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/anime_downloader/sites/animeflix.py", line 56, in _get_sources
    f'{self.stream_url}={id}').json()[0]['file']
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/anime_downloader/sites/helpers/request.py", line 67, in setup_func
    res.raise_for_status()
  File "/Users/ingwie/.local/pipx/venvs/anime-downloader/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://animeflix.io/api/videos?episode_id=7906
```

**Comment by vn-ki** [comment]
I believe this has been fixed. Please reopen if not.
