### ISSUE TITLE
Can't add anything to watch list <'charmap' codec can't encode character..>

### ISSUE THREAD

**Issue by MichaelDavidJohnson** [vn-ki/anime-downloader#288]
**Describe the bug**

Can't add an anime to watch list using ```anime -ll DEBUG watch --new``` on windows 10. 

**To reproduce**

```
anime -ll DEBUG watch --new
```
enter name or url:
```
One Piece
```

<details>
<summary>LOG</summary>

```
C:\Users\liqui>anime -ll DEBUG watch --new
2020-02-18 17:58:48 Liquid anime_downloader.util[16432] INFO anime-downloader 4.0.1
2020-02-18 17:58:48 Liquid anime_downloader.util[16432] DEBUG Platform: Windows-10-10.0.17134-SP0
2020-02-18 17:58:48 Liquid anime_downloader.util[16432] DEBUG Python 3.7.4
Enter a anime name or url: One Piece
2020-02-18 17:58:54 Liquid anime_downloader.sites.helpers.request[16432] DEBUG HTML file temp_dir: C:\Users\liqui\AppData\Local\Temp\animedlrgd_924a
2020-02-18 17:58:54 Liquid anime_downloader.sites.helpers.request[16432] DEBUG -----
2020-02-18 17:58:54 Liquid anime_downloader.sites.helpers.request[16432] DEBUG GET https://www4.9anime.to/search?
2020-02-18 17:58:54 Liquid anime_downloader.sites.helpers.request[16432] DEBUG {'params': {'keyword': 'One Piece'}}
2020-02-18 17:58:54 Liquid anime_downloader.sites.helpers.request[16432] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0'}
2020-02-18 17:58:54 Liquid anime_downloader.sites.helpers.request[16432] DEBUG -----
send: b'GET /search?keyword=One+Piece HTTP/1.1\r\nHost: www4.9anime.to\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Date: Tue, 18 Feb 2020 17:58:54 GMT
header: Content-Type: text/html
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d1d2c52c2d7850190b79d1c64cb332b901582048734; expires=Thu, 19-Mar-20 17:58:54 GMT; path=/; domain=.9anime.to; HttpOnly; SameSite=Lax
header: Location: http://9anime.to/search?keyword=One+Piece
header: UCS: m1
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 5671e44bed0b3540-LHR
2020-02-18 17:58:54 Liquid anime_downloader.session[16432] DEBUG uncached request
send: b'GET /search?keyword=One+Piece HTTP/1.1\r\nHost: 9anime.to\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCookie: __cfduid=d1d2c52c2d7850190b79d1c64cb332b901582048734\r\n\r\n'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Date: Tue, 18 Feb 2020 17:58:54 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Location: https://9anime.to/search?keyword=One+Piece
header: UCS: e3
header: CF-Cache-Status: DYNAMIC
header: Alt-Svc: h2=":443"; ma=60
header: Server: cloudflare
header: CF-RAY: 5671e44dfe02f3f3-LHR
2020-02-18 17:58:55 Liquid anime_downloader.session[16432] DEBUG uncached request
send: b'GET /search?keyword=One+Piece HTTP/1.1\r\nHost: 9anime.to\r\nuser-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCookie: __cfduid=d1d2c52c2d7850190b79d1c64cb332b901582048734\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Tue, 18 Feb 2020 17:58:54 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: UCS: e3
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 5671e44fbc596ac5-LHR
header: Content-Encoding: gzip
2020-02-18 17:58:55 Liquid anime_downloader.session[16432] DEBUG uncached request
2020-02-18 17:58:55 Liquid anime_downloader.sites.helpers.request[16432] DEBUG https://9anime.to/search?keyword=One+Piece
2020-02-18 17:58:55 Liquid anime_downloader.sites.helpers.request[16432] DEBUG C:\Users\liqui\AppData\Local\Temp\animedlrgd_924a\tmpjl6nz40y
Traceback (most recent call last):
  File "c:\users\liqui\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\liqui\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\liqui\Anaconda3\Scripts\anime.exe\__main__.py", line 7, in <module>
  File "c:\users\liqui\anaconda3\lib\site-packages\anime_downloader\cli.py", line 53, in main
    cli()
  File "c:\users\liqui\anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\liqui\anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\liqui\anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\liqui\anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\liqui\anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\liqui\anaconda3\lib\site-packages\anime_downloader\commands\watch.py", line 64, in command
    url = util.search(query, provider)
  File "c:\users\liqui\anaconda3\lib\site-packages\anime_downloader\util.py", line 79, in search
    search_results = cls.search(query)
  File "c:\users\liqui\anaconda3\lib\site-packages\anime_downloader\sites\nineanime.py", line 77, in search
    r = helpers.get('https://www4.9anime.to/search?', params={'keyword': query}, headers=desktop_headers)
  File "c:\users\liqui\anaconda3\lib\site-packages\anime_downloader\sites\helpers\request.py", line 71, in setup_func
    _log_response_body(res)
  File "c:\users\liqui\anaconda3\lib\site-packages\anime_downloader\sites\helpers\request.py", line 144, in _log_response_body
    f.write(res.text)
  File "c:\users\liqui\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u301c' in position 35991: character maps to <undefined>


```

**Comment by vn-ki** [comment]
9anime is not supported anymore.
