### ISSUE TITLE
random stopping issue

### ISSUE THREAD

**Issue by WhoPunkedU** [vn-ki/anime-downloader#30]
hey, sorry for bothering you, but it seems I have managed to run into an issue. Hopefully this isnt a waste of your time.

````
C:\Windows\System32>anime dl blackclover --url --provider kissanime
[32manime[0m: anime-downloader 3.1.0
 1: Black Clover
 2: Black Clover (TV) (Dub)
 3: Black Clover (TV) (Sub)

Enter the anime no:  [1]: 2
anime: Selected Black Clover (TV) (Dub)
anime: Extracting episode info from page
anime: Found anime: Black Clover (TV) (Dub)
anime: Quality 720p not found. Trying 360p.
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\anime_downloader\cli.py", line 115, in dl
    util.print_episodeurl(episode)
  File "c:\program files (x86)\python36-32\lib\site-packages\anime_downloader\util.py", line 95, in print_episodeurl
    print(episode.source().stream_url)
  File "c:\program files (x86)\python36-32\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 26, in stream_url
    self.get_data()
  File "c:\program files (x86)\python36-32\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 41, in get_data
    raise NotFoundError
anime_downloader.sites.exceptions.NotFoundError`

it looks like an issue with how it finds the quality, but i'm no expert
```

**Comment by WhoPunkedU** [comment]
the same thing happens if i dont use --provider kissanime

**Comment by vn-ki** [comment]
Fixed in https://github.com/vn-ki/anime-downloader/commit/09ba8f71c2a9939f76214c69d710eb01ee854371.

Just released a new version. Update and it should work.

**Comment by WhoPunkedU** [comment]
thank you @vn-ki
