### ISSUE TITLE
Animepahe doesn't seem to be working

### ISSUE THREAD

**Issue by sreekaran16** [vn-ki/anime-downloader#300]
**Describe the bug**

```
anime dl throws an error "ERROR: 'anime_title'" when trying to download from animepahe. Other sites seem to be working fine. Error existed when running v4.0.1; Updated to v4.1.0 and the error is still there.
```

**To reproduce**

```
anime dl 'dororo' --provider animepahe -e 2: -xd "{aria2}"
```

<details>
<summary>LOG</summary>

```
anime -ll DEBUG dl 'dororo' --provider animepahe -q 720p -e 2: -xd "{aria2}"
2020-03-21 00:25:26 enryuu anime_downloader.util[18212] INFO anime-downloader 4.1.0
2020-03-21 00:25:26 enryuu anime_downloader.util[18212] DEBUG Platform: Windows-10-10.0.18362-SP0
2020-03-21 00:25:26 enryuu anime_downloader.util[18212] DEBUG Python 3.8.2
2020-03-21 00:25:26 enryuu anime_downloader.sites.helpers.request[18212] DEBUG HTML file temp_dir: C:\Users\SKARAN~1\AppData\Local\Temp\animedlox2qc2jp
2020-03-21 00:25:26 enryuu anime_downloader.sites.helpers.request[18212] DEBUG -----
2020-03-21 00:25:26 enryuu anime_downloader.sites.helpers.request[18212] DEBUG GET https://animepahe.com/api
2020-03-21 00:25:26 enryuu anime_downloader.sites.helpers.request[18212] DEBUG {'params': {'l': 8, 'm': 'search', 'q': "'dororo'"}}
2020-03-21 00:25:26 enryuu anime_downloader.sites.helpers.request[18212] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/19.0.1047.0 Safari/535.22'}
2020-03-21 00:25:26 enryuu anime_downloader.sites.helpers.request[18212] DEBUG -----
send: b'GET /api?l=8&m=search&q=%27dororo%27 HTTP/1.1\r\nHost: animepahe.com\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/19.0.1047.0 Safari/535.22\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 20 Mar 2020 18:55:29 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d8a67c8347406edeb67f687a229ccf8821584730528; expires=Sun, 19-Apr-20 18:55:28 GMT; path=/; domain=.animepahe.com; HttpOnly; SameSite=Lax; Secure
header: Vary: Accept-Encoding
header: Cache-Control: no-cache, private
header: Set-Cookie: XSRF-TOKEN=eyJpdiI6InVwMGFJUFhHRDRObTB1d0t4RmhnVEE9PSIsInZhbHVlIjoiOGk5RDlBdHVmMEZyVzEzc1dtaEFKQXAyRUI4U0R5Q0c3dUdhRHEyckhOaGFPelZmMVJIeVJjZkZiZENKaGZaaCIsIm1hYyI6IjkyMDg4ODYyMzZiMjBjNjI0ZmRiNGMxZDllMDRjMzNjYTUyMmVlMTgyMTg3NmM0ZGMzMzk5NTdmOWYyODNjNDMifQ%3D%3D; expires=Fri, 20-Mar-2020 20:55:28 GMT; Max-Age=7200; path=/
header: Set-Cookie: laravel_session=eyJpdiI6Ijd3XC9jVkpQZmpwcGZ6ZjlKSStiQ1h3PT0iLCJ2YWx1ZSI6IlBCTDQrTkx4OHdoM1F0NG9MZWowb1d3ZHlZTENCS1VidW4rdnFWMzlQUjllRUViUlRkQkVMeFRjUkhaWktiY2QiLCJtYWMiOiI4ZWNjMWM3Nzg3Nzg1YTcxOTQyMjYwNzYyYmFiZWZhNGVlYzYyMWQ5ZGM0NTVkYzk3OTJkYjA3ZGJjZjA0ZmE1In0%3D; expires=Fri, 20-Mar-2020 20:55:28 GMT; Max-Age=7200; path=/; httponly
header: Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
header: Content-Encoding: gzip
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 5771a5cc3a13d5bb-BOM
header: alt-svc: h3-27=":443"; ma=86400, h3-25=":443"; ma=86400, h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
2020-03-21 00:25:27 enryuu anime_downloader.session[18212] DEBUG uncached request
2020-03-21 00:25:27 enryuu anime_downloader.sites.helpers.request[18212] DEBUG https://animepahe.com/api?l=8&m=search&q=%27dororo%27
2020-03-21 00:25:27 enryuu anime_downloader.sites.helpers.request[18212] DEBUG C:\Users\SKARAN~1\AppData\Local\Temp\animedlox2qc2jp\tmpak3v3pql
2020-03-21 00:25:27 enryuu anime_downloader.sites.animepahe[18212] DEBUG Dororo
2020-03-21 00:25:27 enryuu anime_downloader.sites.animepahe[18212] DEBUG Dorohedoro
+--------+------------+--------+
|      2 | Dorohedoro |        |
|      1 | Dororo     |        |
|--------+------------+--------|
|   SlNo | Title      | Meta   |
+--------+------------+--------+
Enter the anime no:  [1]: 1
2020-03-21 00:25:42 enryuu anime_downloader.util[18212] INFO Selected Dororo
2020-03-21 00:25:42 enryuu anime_downloader.sites.anime[18212] INFO Extracting episode info from page
2020-03-21 00:25:42 enryuu anime_downloader.sites.helpers.request[18212] DEBUG -----
2020-03-21 00:25:42 enryuu anime_downloader.sites.helpers.request[18212] DEBUG GET https://animepahe.com/anime/dororo
2020-03-21 00:25:42 enryuu anime_downloader.sites.helpers.request[18212] DEBUG {}
2020-03-21 00:25:42 enryuu anime_downloader.sites.helpers.request[18212] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/19.0.1047.0 Safari/535.22'}
2020-03-21 00:25:42 enryuu anime_downloader.sites.helpers.request[18212] DEBUG -----
send: b'GET /anime/dororo HTTP/1.1\r\nHost: animepahe.com\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/19.0.1047.0 Safari/535.22\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCookie: __cfduid=d8a67c8347406edeb67f687a229ccf8821584730528; XSRF-TOKEN=eyJpdiI6InVwMGFJUFhHRDRObTB1d0t4RmhnVEE9PSIsInZhbHVlIjoiOGk5RDlBdHVmMEZyVzEzc1dtaEFKQXAyRUI4U0R5Q0c3dUdhRHEyckhOaGFPelZmMVJIeVJjZkZiZENKaGZaaCIsIm1hYyI6IjkyMDg4ODYyMzZiMjBjNjI0ZmRiNGMxZDllMDRjMzNjYTUyMmVlMTgyMTg3NmM0ZGMzMzk5NTdmOWYyODNjNDMifQ%3D%3D; laravel_session=eyJpdiI6Ijd3XC9jVkpQZmpwcGZ6ZjlKSStiQ1h3PT0iLCJ2YWx1ZSI6IlBCTDQrTkx4OHdoM1F0NG9MZWowb1d3ZHlZTENCS1VidW4rdnFWMzlQUjllRUViUlRkQkVMeFRjUkhaWktiY2QiLCJtYWMiOiI4ZWNjMWM3Nzg3Nzg1YTcxOTQyMjYwNzYyYmFiZWZhNGVlYzYyMWQ5ZGM0NTVkYzk3OTJkYjA3ZGJjZjA0ZmE1In0%3D\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 20 Mar 2020 18:55:44 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Vary: Accept-Encoding
header: Cache-Control: no-cache, private
header: Set-Cookie: XSRF-TOKEN=eyJpdiI6InMwYk9cL3lwRTc5TzVSRTROc3hQRlJnPT0iLCJ2YWx1ZSI6InFKN1pmOFVFa1NtS01zZHpcL0tHOVFOVjJNQ0ZuUXZrblVEbTR5TkFtUU1NNDBrU3p5UWVCM1VkTFJKMTBLTmhKIiwibWFjIjoiMTk1ZjI4NTY5MTBjMzA3OGQ5MjUxOWJlNWQyMmE5ODNiNmVkMzhlYzRiNTc3MTU0OTMyYTEyMDRjNzFlNDI5YyJ9; expires=Fri, 20-Mar-2020 20:55:44 GMT; Max-Age=7200; path=/
header: Set-Cookie: laravel_session=eyJpdiI6InpXaDF4bDJKQVVJSXlnVnZNczRTTkE9PSIsInZhbHVlIjoiSDVFT1lkajB4MXVHbHlYXC96QkRRZ0xiRExPalBJalhvSzFCMEJLMzhYNWorNWVEZ1lBXC9NM1lxQk1RNE9uUGNMIiwibWFjIjoiNzVlNTJiODJiZWQxYzdlNTczYWY1ZjIxZTgyOTViNTk1ZWU1M2I3OTRmNDNlZDllMDczNzYwMjY3MmZhZjE3MyJ9; expires=Fri, 20-Mar-2020 20:55:44 GMT; Max-Age=7200; path=/; httponly
header: Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 5771a62d8815d5bb-BOM
header: Content-Encoding: gzip
header: alt-svc: h3-27=":443"; ma=86400, h3-25=":443"; ma=86400, h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
2020-03-21 00:25:42 enryuu anime_downloader.session[18212] DEBUG uncached request
2020-03-21 00:25:42 enryuu anime_downloader.sites.helpers.request[18212] DEBUG https://animepahe.com/anime/dororo
2020-03-21 00:25:42 enryuu anime_downloader.sites.helpers.request[18212] DEBUG C:\Users\SKARAN~1\AppData\Local\Temp\animedlox2qc2jp\tmpf3rpim_t
2020-03-21 00:25:43 enryuu anime_downloader.sites.helpers.request[18212] DEBUG -----
2020-03-21 00:25:43 enryuu anime_downloader.sites.helpers.request[18212] DEBUG GET https://animepahe.com/api
2020-03-21 00:25:43 enryuu anime_downloader.sites.helpers.request[18212] DEBUG {'params': {'m': 'release', 'id': '2923', 'sort': 'episode_asc', 'page': 1}}
2020-03-21 00:25:43 enryuu anime_downloader.sites.helpers.request[18212] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/19.0.1047.0 Safari/535.22'}
2020-03-21 00:25:43 enryuu anime_downloader.sites.helpers.request[18212] DEBUG -----
send: b'GET /api?id=2923&m=release&page=1&sort=episode_asc HTTP/1.1\r\nHost: animepahe.com\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.22 (KHTML, like Gecko) Chrome/19.0.1047.0 Safari/535.22\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCookie: __cfduid=d8a67c8347406edeb67f687a229ccf8821584730528; XSRF-TOKEN=eyJpdiI6InMwYk9cL3lwRTc5TzVSRTROc3hQRlJnPT0iLCJ2YWx1ZSI6InFKN1pmOFVFa1NtS01zZHpcL0tHOVFOVjJNQ0ZuUXZrblVEbTR5TkFtUU1NNDBrU3p5UWVCM1VkTFJKMTBLTmhKIiwibWFjIjoiMTk1ZjI4NTY5MTBjMzA3OGQ5MjUxOWJlNWQyMmE5ODNiNmVkMzhlYzRiNTc3MTU0OTMyYTEyMDRjNzFlNDI5YyJ9; laravel_session=eyJpdiI6InpXaDF4bDJKQVVJSXlnVnZNczRTTkE9PSIsInZhbHVlIjoiSDVFT1lkajB4MXVHbHlYXC96QkRRZ0xiRExPalBJalhvSzFCMEJLMzhYNWorNWVEZ1lBXC9NM1lxQk1RNE9uUGNMIiwibWFjIjoiNzVlNTJiODJiZWQxYzdlNTczYWY1ZjIxZTgyOTViNTk1ZWU1M2I3OTRmNDNlZDllMDczNzYwMjY3MmZhZjE3MyJ9\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 20 Mar 2020 18:55:45 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Vary: Accept-Encoding
header: Cache-Control: no-cache, private
header: Set-Cookie: XSRF-TOKEN=eyJpdiI6IllKTE5XVlY5U2xpKytjMXl0VmNTQXc9PSIsInZhbHVlIjoiU2dmalpCSG5Kd1NqdGl5bllOMkVGZzhXQ3cyeUZ5OUFUYmczUjlLN0xUQWFXc3B4OCszVDFXM0t0MFFCZnRCRCIsIm1hYyI6ImYwZDZhZmQ1YjFhMmUwNjZlODU5NjdjMTk3NzQxMDQ1ZGYxNjQ3MmU2ZjMwYzNhYjkwODZhMGM1ZmM2MThkZTYifQ%3D%3D; expires=Fri, 20-Mar-2020 20:55:44 GMT; Max-Age=7200; path=/
header: Set-Cookie: laravel_session=eyJpdiI6InFsMzR6UlBOWityRVJRcDIrdzdtR0E9PSIsInZhbHVlIjoiU25KdWlSYnlGMnRGaFBzbERzYkdjSUVUQ0Y0TlBTUTQ1alpmZklycE54d2p3T3JkTWpqRGdsNlBSbmtYbDZpeiIsIm1hYyI6IjQ2NWU5Y2VjOGRhZmNhMDBiMzU1OTQxZTA1ZTA5NmY4YWQ5M2JhNzZkOTQ4NjYzOGViNmRlZjNiNzgzNDQ3ZjIifQ%3D%3D; expires=Fri, 20-Mar-2020 20:55:44 GMT; Max-Age=7200; path=/; httponly
header: Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
header: Content-Encoding: gzip
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 5771a6302f46d5bb-BOM
header: alt-svc: h3-27=":443"; ma=86400, h3-25=":443"; ma=86400, h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
2020-03-21 00:25:43 enryuu anime_downloader.session[18212] DEBUG uncached request
2020-03-21 00:25:43 enryuu anime_downloader.sites.helpers.request[18212] DEBUG https://animepahe.com/api?id=2923&m=release&page=1&sort=episode_asc
2020-03-21 00:25:43 enryuu anime_downloader.sites.helpers.request[18212] DEBUG C:\Users\SKARAN~1\AppData\Local\Temp\animedlox2qc2jp\tmpsagyvtoo
Traceback (most recent call last):
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\Scripts\anime-script.py", line 11, in <module>
    load_entry_point('anime-downloader==4.1.0', 'console_scripts', 'anime')()
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\site-packages\anime_downloader\cli.py", line 53, in main
    cli()
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\site-packages\anime_downloader\commands\dl.py", line 91, in command
    anime = cls(anime_url, quality=quality,
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\site-packages\anime_downloader\sites\anime.py", line 84, in __init__
    self._episode_urls = self.get_data()
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\site-packages\anime_downloader\sites\animepahe.py", line 105, in get_data
    self._scrape_metadata(resp['data'])
  File "C:\Users\skaranzx16\AppData\Roaming\Python\Python38\site-packages\anime_downloader\sites\animepahe.py", line 150, in _scrape_metadata
    self.title = data[0]['anime_title']
KeyError: 'anime_title'
```

**Comment by Blatzar** [comment]
currently animepahe + [ cfscrape is broken](https://github.com/Anorov/cloudflare-scrape/issues/341), will fix it once cfscrape works again, I've already fixed the animepahe script

**Comment by sreekaran16** [comment]
Got it, thanks! Could you please update me on this thread when fixed?

**Comment by LordShenron** [comment]
It seems animepahe now added captcha verification too. It broke all anime downloaders i was using for animepahe :(

**Comment by Blatzar** [comment]
Closing this as animepahe now works
