### ISSUE TITLE
NoneType object has no attribute group 

### ISSUE THREAD

**Issue by ZakaRehman** [vn-ki/anime-downloader#331]
**Describe the bug**

using animerush can't download episode 600 onward without getting that error

**To reproduce**

```
anime -ll DEBUG dl "One Piece" --provider animerush -xd "{aria2}" -e 601:926
```

<details>
<summary>LOG</summary>

```
Traceback (most recent call last):
  File "/home/yeet/.local/bin/anime", line 11, in <module>
    sys.exit(main())
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/commands/dl.py", line 96, in command
    animes = util.parse_ep_str(anime, episode_range)
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/util.py", line 136, in parse_ep_str
    for episode in split_anime(anime, episode_grammar):
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 198, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 293, in __init__
    try_data()
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 291, in try_data
    self.source().stream_url
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/extractors/base_extractor.py", line 29, in stream_url
    self.get_data()
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/extractors/base_extractor.py", line 41, in get_data
    data = self._get_data()
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/extractors/mp4upload.py", line 14, in _get_data
    script = re.search(regex,soup).group().replace('</script>','')
AttributeError: 'NoneType' object has no attribute 'group'


```

**Comment by Blatzar** [comment]
Happens because the mp4extractor is used instead of yourupload, will fix

**Comment by ZakaRehman** [comment]
thanks

**Comment by Blatzar** [comment]
Should be fixed and merged now. Closing Issue.

**Comment by ZakaRehman** [comment]
i get this error now
Traceback (most recent call last):
  File "/home/yeet/.local/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader==4.2.0', 'console_scripts', 'anime')()
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/commands/dl.py", line 96, in command
    animes = util.parse_ep_str(anime, episode_range)
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/util.py", line 136, in parse_ep_str
    for episode in split_anime(anime, episode_grammar):
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 198, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 293, in __init__
    try_data()
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 291, in try_data
    self.source().stream_url
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/extractors/base_extractor.py", line 29, in stream_url
    self.get_data()
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/extractors/base_extractor.py", line 41, in get_data
    data = self._get_data()
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/extractors/yourupload.py", line 12, in _get_data
    file = re.search(regex,helpers.get(self.url).text).group(1)
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/sites/helpers/request.py", line 67, in setup_func
    res.raise_for_status()
  File "/home/yeet/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.yourupload.com/embed/3234U5

**Comment by ZakaRehman** [comment]
i get this issue now

Traceback (most recent call last):
  File "/home/yeet/.local/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader==4.2.0', 'console_scripts', 'anime')()
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yeet/.local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/commands/dl.py", line 96, in command
    animes = util.parse_ep_str(anime, episode_range)
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/util.py", line 136, in parse_ep_str
    for episode in split_anime(anime, episode_grammar):
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 198, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 293, in __init__
    try_data()
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 291, in try_data
    self.source().stream_url
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/extractors/base_extractor.py", line 29, in stream_url
    self.get_data()
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/extractors/base_extractor.py", line 41, in get_data
    data = self._get_data()
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/extractors/yourupload.py", line 12, in _get_data
    file = re.search(regex,helpers.get(self.url).text).group(1)
  File "/home/yeet/.local/lib/python3.6/site-packages/anime_downloader/sites/helpers/request.py", line 67, in setup_func
    res.raise_for_status()
  File "/home/yeet/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.yourupload.com/embed/3234U5

**Comment by Blatzar** [comment]
The file is deleted on their side, the scraping works, nothing I can fix

**Comment by ZakaRehman** [comment]
oh okay thanks
