### ISSUE TITLE
Problem with windows version

### ISSUE THREAD

**Issue by joshua-612** [vn-ki/anime-downloader#34]
Traceback (most recent call last):
  File "C:\Python27\Scripts\anime-script.py", line 11, in <module>
    load_entry_point('anime-downloader==2.4.1', 'console_scripts', 'anime')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2318, in load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build\bdist.win-amd64\egg\anime_downloader\cli.py", line 9, in <module>
  File "build\bdist.win-amd64\egg\anime_downloader\players\mpv.py", line 1, in <module>
  File "C:\Python27\lib\site-packages\anime_downloader-2.4.1-py2.7.egg\anime_downloader\players\baseplayer.py", line 8
    class BasePlayer(metaclass=ABCMeta):
                              ^
SyntaxError: invalid syntax

**Comment by vn-ki** [comment]
There are a few problems with your setup. Clear them and you're good to go.

1. You need python 3.
2. The latest version is 3.1.1. You seem to be using 2.4.1.

**Comment by joshua-612** [comment]
Thanks that worked.

**OFF TOPIC** 
I am first year cs student studying in pune
just started learning programming what are some tips, advice, resources 

since you are/were in IIT and this looks like a complex program and you know your stuff.

**Comment by vn-ki** [comment]
Hi, @joshua-612. I'm a first year student too. 

> this looks like a complex program

Trust me, it's not.

> you know your stuff.

I'm still a beginner.

If you don't know any programming language, I'll suggest you learn a language first. Python, IMO, is the easiest language to learn.

If you already know the basics of python, you can contribute to open source projects or create your own (open source) project as a means to learn more. 

I'm also closing this issue as it seems to be resolved. If you have questions, feel free to ask in this thread.

**Comment by joshua-612** [comment]
How and when did you first got started ? Should i make small games or solve challenges on code-chef for practice as a beginner.

**Comment by vn-ki** [comment]
> Should i make small games or solve challenges on code-chef for practice as a beginner.

If you interested in competetive programming, you should challenges on code chef. I have never really made any games, so I can't comment on that.
