### ISSUE TITLE
Animeout failing sometimes

### ISSUE THREAD

**Issue by Blatzar** [vn-ki/anime-downloader#346]
**Describe the bug**

**To reproduce**
bl@arch ~> anime -ll DEBUG dl 'naruto' --provider animeout
2020-04-16 10:02:38 arch anime_downloader.util[18614] INFO anime-downloader 4.2.0
2020-04-16 10:02:38 arch anime_downloader.util[18614] DEBUG Platform: Linux-5.6.3-arch1-1-x86_64-with-glibc2.2.5                                                              
2020-04-16 10:02:38 arch anime_downloader.util[18614] DEBUG Python 3.8.2
2020-04-16 10:02:39 arch anime_downloader.sites.helpers.request[18614] DEBUG HTML file temp_dir: /tmp/animedldc3_o00m                                                         
2020-04-16 10:02:39 arch anime_downloader.sites.helpers.request[18614] DEBUG -----
2020-04-16 10:02:39 arch anime_downloader.sites.helpers.request[18614] DEBUG GET https://animeout.xyz/                                                                        
2020-04-16 10:02:39 arch anime_downloader.sites.helpers.request[18614] DEBUG {'params': {'s': 'naruto'}}                                                                      
2020-04-16 10:02:39 arch anime_downloader.sites.helpers.request[18614] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/4.0.213.1 Safari/532.1'}                                                   
2020-04-16 10:02:39 arch anime_downloader.sites.helpers.request[18614] DEBUG -----
send: b'GET /?s=naruto HTTP/1.1\r\nHost: animeout.xyz\r\nuser-agent: Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/4.0.213.1 Safari/532.1\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx/1.10.3 (Ubuntu)
header: Date: Thu, 16 Apr 2020 08:02:56 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: _wpas_session=7ab3db8b52287d6499ce907e721f2d54%7C%7C1587025974%7C%7C1587025614; expires=Thu, 16-Apr-2020 08:32:54 GMT; Max-Age=1800; path=/; domain=www.animeout.xyz
header: X-Powered-By: W3 Total Cache/0.13.1
header: Link: <https://animeout.xyz/wp-json/>; rel="https://api.w.org/"
header: X-Fastcgi-Cache: MISS
header: Content-Encoding: gzip
2020-04-16 10:02:41 arch anime_downloader.session[18614] DEBUG uncached request
2020-04-16 10:02:41 arch anime_downloader.sites.helpers.request[18614] DEBUG https://animeout.xyz/?s=naruto                                                                   
2020-04-16 10:02:41 arch anime_downloader.sites.helpers.request[18614] DEBUG /tmp/animedldc3_o00m/tmpfvwj8jsm                                                                 
+--------+----------------------------------------------------------------+--------+
|     16 | Bleach (Completed Batch) (480p|60MB)                           |        |
|     15 | Heroman  (Complete Batch) (720p|150MB)                         |        |
|     14 | Project Lists                                                  |        |
|     13 | Ookami Shoujo to Kuro Ouji (Complete Batch)                    |        |
|     12 | Shingeki no Kyojin (Complete BD Batch)(1080p-300MB|720p-200MB) |        |
|     11 | Naruto Shippuden The Movie 1                                   |        |
|     10 | Naruto Shippuuden Movie 3 – Hi no Ishi wo Tsugu Mono           |        |
|      9 | Naruto Shippuden Movie 4 – The Lost Tower                      |        |
|      8 | Naruto Shippuden Movie 2 – Bonds                               |        |
|      7 | Gekijouban Naruto: Blood Prison (Movie) (720p|600MB)           |        |
|      6 | Road to Ninja: Naruto the Movie (Movie) (BD|720p|500MB)        |        |
|      5 | The Last Naruto the Movie (Dual Audio)                         |        |
|      4 | Boruto Naruto The Movie English Sub                            |        |
|      3 | Naruto Shippuuden (Latest Ep-500)                              |        |
|      2 | Naruto (2002)(Original)(Complete)                              |        |
|      1 | Boruto : Naruto Next Generations (Episode 152)                 |        |
|--------+----------------------------------------------------------------+--------|
|   SlNo | Title                                                          | Meta   |
+--------+----------------------------------------------------------------+--------+
Enter the anime no:  [1]: 4
2020-04-16 10:02:48 arch anime_downloader.util[18614] INFO Selected Boruto Naruto The Movie English Sub
2020-04-16 10:02:48 arch anime_downloader.sites.anime[18614] INFO Extracting episode info from page
2020-04-16 10:02:48 arch anime_downloader.sites.helpers.request[18614] DEBUG -----
2020-04-16 10:02:48 arch anime_downloader.sites.helpers.request[18614] DEBUG GET https://www.animeout.xyz/download-boruto-naruto-movie-english-sub/                           
2020-04-16 10:02:48 arch anime_downloader.sites.helpers.request[18614] DEBUG {}
2020-04-16 10:02:48 arch anime_downloader.sites.helpers.request[18614] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/4.0.213.1 Safari/532.1'}
2020-04-16 10:02:48 arch anime_downloader.sites.helpers.request[18614] DEBUG -----
send: b'GET /download-boruto-naruto-movie-english-sub/ HTTP/1.1\r\nHost: www.animeout.xyz\r\nuser-agent: Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/4.0.213.1 Safari/532.1\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx/1.10.3 (Ubuntu)
header: Date: Thu, 16 Apr 2020 08:03:04 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: _wpas_session=8b6f728489cf05a641c9b8d5f39181c7%7C%7C1587025983%7C%7C1587025623; expires=Thu, 16-Apr-2020 08:33:03 GMT; Max-Age=1800; path=/; domain=www.animeout.xyz
header: Link: <https://www.animeout.xyz/wp-json/>; rel="https://api.w.org/"
header: Link: <https://www.animeout.xyz/?p=71836>; rel=shortlink
header: X-Pingback: https://www.animeout.xyz/xmlrpc.php
header: Last-Modified: Thu, 16 Apr 2020 08:03:04 GMT
header: Expires: Thu, 16 Apr 2020 09:03:04 GMT
header: Pragma: public
header: Cache-Control: max-age=3600, public
header: ETag: "e8513c8a714b1ed0efe570e9b5424b15"
header: X-Powered-By: W3 Total Cache/0.13.1
header: Content-Encoding: gzip
header: Vary: Accept-Encoding
header: X-Fastcgi-Cache: MISS
2020-04-16 10:02:49 arch anime_downloader.session[18614] DEBUG uncached request
2020-04-16 10:02:49 arch anime_downloader.sites.helpers.request[18614] DEBUG https://www.animeout.xyz/download-boruto-naruto-movie-english-sub/
2020-04-16 10:02:49 arch anime_downloader.sites.helpers.request[18614] DEBUG /tmp/animedldc3_o00m/tmpvzjsyg1y
2020-04-16 10:02:49 arch anime_downloader.sites.helpers.request[18614] DEBUG -----
2020-04-16 10:02:49 arch anime_downloader.sites.helpers.request[18614] DEBUG GET https://www.animeout.xyz/download-boruto-naruto-movie-english-sub/
2020-04-16 10:02:49 arch anime_downloader.sites.helpers.request[18614] DEBUG {}
2020-04-16 10:02:49 arch anime_downloader.sites.helpers.request[18614] DEBUG {'user-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/4.0.213.1 Safari/532.1'}
2020-04-16 10:02:49 arch anime_downloader.sites.helpers.request[18614] DEBUG -----
2020-04-16 10:02:49 arch anime_downloader.session[18614] DEBUG cached request
2020-04-16 10:02:49 arch anime_downloader.sites.helpers.request[18614] DEBUG https://www.animeout.xyz/download-boruto-naruto-movie-english-sub/
2020-04-16 10:02:49 arch anime_downloader.sites.helpers.request[18614] DEBUG /tmp/animedldc3_o00m/tmp5rb9js09
2020-04-16 10:02:49 arch anime_downloader.sites.anime[18614] DEBUG EPISODE IDS: length: 0, ids: []
Traceback (most recent call last):
  File "/usr/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader==4.2.0', 'console_scripts', 'anime')()
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/commands/dl.py", line 92, in command
    anime = cls(anime_url, quality=quality,
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 84, in __init__
    self._episode_urls = self.get_data()
  File "/home/bl/.local/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 171, in get_data
    if not isinstance(self._episode_urls[0], tuple):
IndexError: list index out of range
-->

**Comment by ngomile** [comment]
Changing the link selector from 'div.article-content > p > a' to 'article.post a' seems to do the trick.

**Comment by Blatzar** [comment]
Closing this as it's fixed
