### ISSUE TITLE
NotFoundError on kissanime and 9anime

### ISSUE THREAD

**Issue by phanirithvij** [vn-ki/anime-downloader#37]
# Version: **3.1.1**

## In **kissmanga** and also __9anime__ when I started downloading _**code geass**_ it says

```shell
anime dl 'code geass' --provider 9anime
```
Output:
```
...

anime_downloader.sites.exceptions.NotFoundError
```
Screenshot:

![9animeeeor](https://user-images.githubusercontent.com/29627898/42320948-c3ec9df0-8074-11e8-8b5b-2f8dd595c488.png)

```shell
anime dl 'code geass' --provider kissanime
```
Output:
```
...

anime_downloader.sites.exceptions.NotFoundError
```
Screenshot:

![kissanimeerror](https://user-images.githubusercontent.com/29627898/42321083-43ced5e2-8075-11e8-9925-b99559dfd14e.png)

**Comment by vn-ki** [comment]
Weird. I cannot reproduce it. Can you try again using `-ll DEBUG`? ie,
```
anime dl 'code geass' --provider 9anime -ll DEBUG
```

**Comment by phanirithvij** [comment]
```shell
anime dl 'code geass' --provider 9anime -ll 
```
OUTPUT:

```shell
DEBUG
INFO root: anime-downloader 3.1.1
DEBUG root: Platform: Linux-4.8.0-53-generic-x86_64-with-LinuxMint-18.2-sonya
DEBUG root: Python 3.5.2
DEBUG root: https://www7.9anime.is/search?keyword=code+geass
DEBUG root: Search results
DEBUG root: <SearchResult Title: Code Geass: Nunnally in Wonderland URL: https://www7.9anime.is/watch/code-geass-nunnally-in-wonderland.kmr4>
DEBUG root: <SearchResult Title: Code Geass: Fukkatsu no Lelouch URL: https://www7.9anime.is/watch/code-geass-fukkatsu-no-lelouch.5y49>
DEBUG root: <SearchResult Title: Code Geass: Lelouch of the Rebellion (Dub) URL: https://www7.9anime.is/watch/code-geass-lelouch-of-the-rebellion-dub.k3w>
DEBUG root: <SearchResult Title: Code Geass: Hangyaku no Lelouch Recaps URL: https://www7.9anime.is/watch/code-geass-hangyaku-no-lelouch-recaps.rnvo>
DEBUG root: <SearchResult Title: Code Geass: Lelouch of the Rebellion R2 URL: https://www7.9anime.is/watch/code-geass-lelouch-of-the-rebellion-r2.3x5r>
DEBUG root: <SearchResult Title: Code Geass: Hangyaku no Lelouch III - Oudou URL: https://www7.9anime.is/watch/code-geass-hangyaku-no-lelouch-iii-oudou.8m13>
DEBUG root: <SearchResult Title: Code Geass: Hangyaku no Lelouch I - Koudou URL: https://www7.9anime.is/watch/code-geass-hangyaku-no-lelouch-i-koudou.6kj4>
DEBUG root: <SearchResult Title: Code Geass: Hangyaku no Lelouch II - Handou URL: https://www7.9anime.is/watch/code-geass-hangyaku-no-lelouch-ii-handou.j7w8>
DEBUG root: <SearchResult Title: Code Geass: Lelouch of the Rebellion URL: https://www7.9anime.is/watch/code-geass-lelouch-of-the-rebellion.2x52>
DEBUG root: <SearchResult Title: Code Geass: Lelouch of the Rebellion R2 (Dub) URL: https://www7.9anime.is/watch/code-geass-lelouch-of-the-rebellion-r2-dub.6vp>
DEBUG root: <SearchResult Title: Code Geass: Akito the Exiled - Memories of Hatred (Dub) URL: https://www7.9anime.is/watch/code-geass-akito-the-exiled-memories-of-hatred-dub.6oj4>
DEBUG root: <SearchResult Title: Code Geass: Lelouch of the Rebellion Picture Dramas URL: https://www7.9anime.is/watch/code-geass-lelouch-of-the-rebellion-picture-dramas.wz27>
DEBUG root: <SearchResult Title: Code Geass: Lelouch of the Rebellion R2 Picture Dramas (Dub) URL: https://www7.9anime.is/watch/code-geass-lelouch-of-the-rebellion-r2-picture-dramas-dub.wvp6>
DEBUG root: <SearchResult Title: Code Geass: Akito the Exiled - The Wyvern Divided URL: https://www7.9anime.is/watch/code-geass-akito-the-exiled-the-wyvern-divided.mqjv>
DEBUG root: <SearchResult Title: Code Geass: Akito the Exiled - Memories of Hatred URL: https://www7.9anime.is/watch/code-geass-akito-the-exiled-memories-of-hatred.kkxw>
DEBUG root: <SearchResult Title: Code Geass: Akito the Exiled - The Wyvern Arrives (Dub) URL: https://www7.9anime.is/watch/code-geass-akito-the-exiled-the-wyvern-arrives-dub.3lvy>
DEBUG root: <SearchResult Title: Code Geass: Hangyaku no Lelouch R2 Special Edition Zero Requiem URL: https://www7.9anime.is/watch/code-geass-hangyaku-no-lelouch-r2-special-edition-zero-requiem.ln96>
DEBUG root: <SearchResult Title: Code Geass: Akito the Exiled - The Brightness Falls URL: https://www7.9anime.is/watch/code-geass-akito-the-exiled-the-brightness-falls.l3x3>
DEBUG root: <SearchResult Title: Code Geass: Akito the Exiled - To Beloved Ones URL: https://www7.9anime.is/watch/code-geass-akito-the-exiled-to-beloved-ones.jj2n>
DEBUG root: <SearchResult Title: Code Geass: Akito the Exiled - The Wyvern Divided (Dub) URL: https://www7.9anime.is/watch/code-geass-akito-the-exiled-the-wyvern-divided-dub.4mv7>
DEBUG root: <SearchResult Title: Code Geass: Akito the Exiled - To Beloved Ones (Dub) URL: https://www7.9anime.is/watch/code-geass-akito-the-exiled-to-beloved-ones-dub.2kvq>
DEBUG root: <SearchResult Title: Code Geass: Akito the Exiled - The Wyvern Arrives URL: https://www7.9anime.is/watch/code-geass-akito-the-exiled-the-wyvern-arrives.9208>
DEBUG root: <SearchResult Title: Code Geass: Lelouch of the Rebellion Picture Dramas (Dub) URL: https://www7.9anime.is/watch/code-geass-lelouch-of-the-rebellion-picture-dramas-dub.vm22>
DEBUG root: <SearchResult Title: Code Geass: Hangyaku no Lelouch Picture Drama - Hajimari no Zenya URL: https://www7.9anime.is/watch/code-geass-hangyaku-no-lelouch-picture-drama-hajimari-no-zenya.njwj>
DEBUG root: <SearchResult Title: Code Geass: Akito the Exiled - The Brightness Falls (Dub) URL: https://www7.9anime.is/watch/code-geass-akito-the-exiled-the-brightness-falls-dub.5nvm>
DEBUG root: <SearchResult Title: Code Geass: Hangyaku no Lelouch - Kiseki no Birthday Picture Drama URL: https://www7.9anime.is/watch/code-geass-hangyaku-no-lelouch-kiseki-no-birthday-picture-drama.kmp4>
DEBUG root: <SearchResult Title: Code Geass: Hangyaku no Lelouch Special Edition Black Rebellion URL: https://www7.9anime.is/watch/code-geass-hangyaku-no-lelouch-special-edition-black-rebellion.jlq3>
DEBUG root: <SearchResult Title: Code Geass: Lelouch of the Rebellion R2 Picture Dramas URL: https://www7.9anime.is/watch/code-geass-lelouch-of-the-rebellion-r2-picture-dramas.p214>
DEBUG root: <SearchResult Title: Code Geass: Lelouch of the Rebellion R2 Extra Flash - Baba Theater Redux URL: https://www7.9anime.is/watch/code-geass-lelouch-of-the-rebellion-r2-extra-flash-baba-theater-redux.njxk>
DEBUG root: <SearchResult Title: Code Geass: Hangyaku no Lelouch - Kiseki no Birthday Picture Drama Flash Special URL: https://www7.9anime.is/watch/code-geass-hangyaku-no-lelouch-kiseki-no-birthday-picture-drama-flash-special.m137>
 1: Code Geass: Nunnally in Wonderland      	OVA                 
 2: Code Geass: Fukkatsu no Lelouch         	Preview | Ep 2 Previ
 3: Code Geass: Lelouch of the Rebellion (Du	Ep 25/25 | DUB      
 4: Code Geass: Hangyaku no Lelouch Recaps  	Ep 2/2 | Special    
 5: Code Geass: Lelouch of the Rebellion R2 	Ep 25/25            
 6: Code Geass: Hangyaku no Lelouch III - Ou	Preview             
 7: Code Geass: Hangyaku no Lelouch I - Koud	Movie               
 8: Code Geass: Hangyaku no Lelouch II - Han	Preview             
 9: Code Geass: Lelouch of the Rebellion    	Ep 25/25            
10: Code Geass: Lelouch of the Rebellion R2 	Ep 25/25 | DUB      
11: Code Geass: Akito the Exiled - Memories 	Movie | DUB         
12: Code Geass: Lelouch of the Rebellion Pic	Ep 8/9 | Special    
13: Code Geass: Lelouch of the Rebellion R2 	Preview | Ep ?/9 | D
14: Code Geass: Akito the Exiled - The Wyver	Movie               
15: Code Geass: Akito the Exiled - Memories 	Movie               
16: Code Geass: Akito the Exiled - The Wyver	Movie | DUB         
17: Code Geass: Hangyaku no Lelouch R2 Speci	OVA                 
18: Code Geass: Akito the Exiled - The Brigh	Movie               
19: Code Geass: Akito the Exiled - To Belove	Movie               
20: Code Geass: Akito the Exiled - The Wyver	Movie | DUB         
21: Code Geass: Akito the Exiled - To Belove	Movie | DUB         
22: Code Geass: Akito the Exiled - The Wyver	Movie               
23: Code Geass: Lelouch of the Rebellion Pic	Ep 8/9 | Special | D
24: Code Geass: Hangyaku no Lelouch Picture 	Special             
25: Code Geass: Akito the Exiled - The Brigh	Movie | DUB         
26: Code Geass: Hangyaku no Lelouch - Kiseki	Special             
27: Code Geass: Hangyaku no Lelouch Special 	OVA                 
28: Code Geass: Lelouch of the Rebellion R2 	Ep 8/9 | Special    
29: Code Geass: Lelouch of the Rebellion R2 	Ep 9/9 | Special    
30: Code Geass: Hangyaku no Lelouch - Kiseki	Special             

Enter the anime no:  [1]: 5
INFO root: Selected Code Geass: Lelouch of the Rebellion R2
INFO root: Extracting episode info from page
DEBUG root: data-ts: 1530788400
DEBUG root: EPISODE IDS: length: 25, ids: ['9yo6ym', '9yo6mm', 'z5lp8m', '092j8r', 'vyvwlv', 'qqxo05', 'lnljqq', '3xrmoy', 'y2qzzj', 'qqxo1n', 'oqjm2j', '9yovpx', '1on6ym', 'mo2068', '6xlmn0', 'rrl50n', '7xjn91', 'y2qn0z', '4xqk0x', 'p4r97x', 'p4r9lx', 'lnlvn3', 'lnlv83', 'y2qy8x', 'w61rn4']
INFO root: Found anime: Code Geass: Lelouch of the Rebellion R2
INFO root: Downloading to /home/phani/Projects/spotify-downloader
DEBUG root: Extracting stream info of id: 9yo6ym
DEBUG root: API call URL: https://9anime.is/ajax/episode/info with params {'server': '33', 'ts': '1530788400', 'id': '9yo6ym', '_': 674}
DEBUG root: URL: https://www7.9anime.is/ajax/episode/info?server=33&ts=1530788400&id=9yo6ym&_=674
DEBUG root: Returned data: {'params': [], 'backup': 0, 'type': 'iframe', 'grabber': 'https://www7.9anime.is/grabber-api/?server=33', 'target': 'https://www.rapidvideo.com/e/FOHKS021LY', 'subtitle': '', 'name': '01'}
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FOHKS021LY&q=720p
DEBUG root: list index out of range
WARNING root: Quality 720p not found. Trying 360p.
DEBUG root: API call URL: https://9anime.is/ajax/episode/info with params {'server': '33', 'ts': '1530788400', 'id': '9yo6ym', '_': 674}
DEBUG root: URL: https://www7.9anime.is/ajax/episode/info?server=33&ts=1530788400&id=9yo6ym&_=674
DEBUG root: Returned data: {'params': [], 'backup': 0, 'type': 'iframe', 'grabber': 'https://www7.9anime.is/grabber-api/?server=33', 'target': 'https://www.rapidvideo.com/e/FOHKS021LY', 'subtitle': '', 'name': '01'}
INFO root: Downloading Code Geass: Lelouch of the Rebellion R2-1
INFO root: ./Code_Geass_Lelouch_of_the_Rebellion_R2/Code_Geass_Lelouch_of_the_Rebellion_R2_1.mp4
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FOHKS021LY&q=360p
DEBUG root: list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/cli.py", line 131, in dl
    format=file_format)
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/sites/anime.py", line 172, in download
    r = requests.get(self.source().stream_url, stream=True)
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/extractors/base_extractor.py", line 26, in stream_url
    self.get_data()
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/extractors/base_extractor.py", line 41, in get_data
    raise NotFoundError
anime_downloader.sites.exceptions.NotFoundError
```

**Comment by vn-ki** [comment]
@phanirithvij Can you go to this site: https://www.rapidvideo.com/e/FOHKS021LY&q=720p
, and press Ctrl+U, and paste the source here?

**Comment by phanirithvij** [comment]
It's working now 
It seems rapidvideo was not available for my IP because of some reason for some time 
I did a reboot and It worked

By the way would you add continue download option?

It started downloading from the beginning after I aborted it once
