### ISSUE TITLE
Problem with animeout

### ISSUE THREAD

**Issue by gingerbeardman** [vn-ki/anime-downloader#374]
**Describe the bug**

download error with animeout

**To reproduce**

```
$ anime --log-level DEBUG dl 'kite' --provider animeout
```
choose 1) Kite OVA

<details>
<summary>LOG</summary>

```
$ anime --log-level DEBUG dl 'kite' --provider animeout
2020-05-26 12:21:03 matt.local anime_downloader.util[31646] INFO anime-downloader 4.3.0
2020-05-26 12:21:03 matt.local anime_downloader.util[31646] DEBUG Platform: macOS-10.14.6-x86_64-i386-64bit
2020-05-26 12:21:03 matt.local anime_downloader.util[31646] DEBUG Python 3.8.2
2020-05-26 12:21:03 matt.local anime_downloader.sites.helpers.request[31646] DEBUG -----
2020-05-26 12:21:03 matt.local anime_downloader.sites.helpers.request[31646] DEBUG GET https://animeout.xyz/
2020-05-26 12:21:03 matt.local anime_downloader.sites.helpers.request[31646] DEBUG {'params': {'s': 'kite'}}
2020-05-26 12:21:03 matt.local anime_downloader.sites.helpers.request[31646] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.2 (KHTML, like Gecko) Chrome/22.0.1216.0 Safari/537.2'}
2020-05-26 12:21:03 matt.local anime_downloader.sites.helpers.request[31646] DEBUG -----
2020-05-26 12:21:03 matt.local anime_downloader.session[31646] DEBUG cached request
2020-05-26 12:21:03 matt.local anime_downloader.sites.helpers.request[31646] DEBUG https://animeout.xyz/?s=kite
2020-05-26 12:21:03 matt.local anime_downloader.sites.helpers.request[31646] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedlluk91zy5/tmpmp4zl983
+--------+-------------------------------------------------------+--------+
|      9 | Gintama’ (2011-2013)(Episode 202-265)(720p|90MB)      |        |
|      8 | Get Backers (Episode 1-49) (480p|65MB) (Dual Audio)   |        |
|      7 | Pocket Monsters  (Complete Batch) (480p|70MB)         |        |
|      6 | Mezzo DSA (Complete Batch) (Episode 1-13) (480p|65MB) |        |
|      5 | Chobits  (Dual Audio) (480p|60MB)                     |        |
|      4 | Project Lists                                         |        |
|      3 | Mirai Nikki                                           |        |
|      2 | Seitokai Yakuindomo 2 (2014)(OVA)                     |        |
|      1 | Kite OVA                                              |        |
|--------+-------------------------------------------------------+--------|
|   SlNo | Title                                                 | Meta   |
+--------+-------------------------------------------------------+--------+
Enter the anime no:  [1]: 1
2020-05-26 12:21:04 matt.local anime_downloader.util[31646] INFO Selected Kite OVA
2020-05-26 12:21:04 matt.local anime_downloader.sites.anime[31646] INFO Extracting episode info from page
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG -----
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG GET https://www.animeout.xyz/kite/
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG {}
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.2 (KHTML, like Gecko) Chrome/22.0.1216.0 Safari/537.2'}
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG -----
2020-05-26 12:21:04 matt.local anime_downloader.session[31646] DEBUG cached request
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG https://www.animeout.xyz/kite/
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedlluk91zy5/tmp8yuviemk
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG -----
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG GET https://www.animeout.xyz/kite/
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG {}
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.2 (KHTML, like Gecko) Chrome/22.0.1216.0 Safari/537.2'}
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG -----
2020-05-26 12:21:04 matt.local anime_downloader.session[31646] DEBUG cached request
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG https://www.animeout.xyz/kite/
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedlluk91zy5/tmpd6cwe_zu
2020-05-26 12:21:04 matt.local anime_downloader.sites.anime[31646] DEBUG EPISODE IDS: length: 1, ids: ["http://download.animeout.com/series/OVA/Kite/[AOT] Kite (Director's Cut) [Ayrton].mkv"]
2020-05-26 12:21:04 matt.local anime_downloader.commands.dl[31646] INFO Found anime: Kite OVA
2020-05-26 12:21:04 matt.local anime_downloader.commands.dl[31646] INFO Downloading to /Users/matt/Downloads/1234_JD
2020-05-26 12:21:04 matt.local anime_downloader.sites.anime[31646] DEBUG Extracting stream info of id: http://download.animeout.com/series/OVA/Kite/[AOT] Kite (Director's Cut) [Ayrton].mkv
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG -----
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG GET http://download.animeout.com/series/OVA/Kite/[AOT] Kite (Director's Cut) [Ayrton].mkv
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG {}
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.2 (KHTML, like Gecko) Chrome/22.0.1216.0 Safari/537.2'}
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG -----
2020-05-26 12:21:04 matt.local anime_downloader.session[31646] DEBUG cached request
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG http://ddl.animeout.com/index.php?url=sv1.animeout.com/series/OVA/Kite/%5BAOT%5D%20Kite%20(Director's%20Cut)%20%5BAyrton%5D.mkv
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedlluk91zy5/tmpuz2gkc1q
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG -----
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG GET http://ddl.animeout.com/public.php?url=sv1.animeout.com/series/OVA/Kite/[AOT] Kite (Director's Cut) [Ayrton].mkv
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG {}
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.2 (KHTML, like Gecko) Chrome/22.0.1216.0 Safari/537.2'}
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG -----
2020-05-26 12:21:04 matt.local anime_downloader.session[31646] DEBUG cached request
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG http://ddl.animeout.com/public.php?url=sv1.animeout.com/series/OVA/Kite/%5BAOT%5D%20Kite%20(Director's%20Cut)%20%5BAyrton%5D.mkv
2020-05-26 12:21:04 matt.local anime_downloader.sites.helpers.request[31646] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedlluk91zy5/tmpgifjxyb8
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader==4.3.0', 'console_scripts', 'anime')()
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/anime_downloader/commands/dl.py", line 112, in command
    for episode in animes:
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 198, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 293, in __init__
    try_data()
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 289, in try_data
    self.get_data()
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 349, in get_data
    self._sources = self._get_sources()
  File "/usr/local/Cellar/anime-downloader/HEAD-57f82b7/libexec/lib/python3.8/site-packages/anime_downloader/sites/animeout.py", line 40, in _get_sources
    url = re.search(r'http[^"]*',script).group()
AttributeError: 'NoneType' object has no attribute 'group'


```

**Comment by ArjixGamer** [comment]
it seems that smth changed in the website?
That is the only problem that i can think of.

**Comment by ArjixGamer** [comment]
here is the important part in the log:
`File "C:\Python38\lib\site-packages\anime_downloader-4.3.0-py3.8.egg\anime_downloader\sites\animeout.py", line 40, in _get_sources
    url = re.search(r'http[^"]*',script).group()
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by ArjixGamer** [comment]
i printed the url before it gets the .group() property and it printed `None`

**Comment by ArjixGamer** [comment]
wait, my bad. The script variable prints None, the url variable gives an Error

**Comment by gingerbeardman** [comment]
Was trying to find Kite (1998) and tried all hosts, some others also errors. Will post them separately when I can.

**Comment by Blatzar** [comment]
having a hard time fully replicating the issue, but I think I've solved it, just need some testing from you.
Can you replace animeout.py AnimeoutEpisode with the following and see if it works, if it doesn't post output.
```
class AnimeOutEpisode(AnimeEpisode, sitename='animeout'):
        def _get_sources(self):
            soup = helpers.soupify(helpers.get(self.url))
            link = soup.select('div.Center > p > h2 > a')[0].get('href')
            print(link)
            print(helpers.soupify(helpers.get(link)).select('script'))
            script = helpers.soupify(helpers.get(link)).select('script')[2]
            print(script)
            url = re.search(r'http[^"]*',str(script)).group()
            return [('no_extractor', url,)]
```

**Comment by ArjixGamer** [comment]
yes, you have fixed it. It printed the url and the script and then aria2 started the download

**Comment by gingerbeardman** [comment]
Fixed
