### ISSUE TITLE
Logger is not defined

### ISSUE THREAD

**Issue by tzulberti** [vn-ki/anime-downloader#376]
**Describe the bug**

**To reproduce**

```
anime dl --provider kickass Goddess
anime: anime-downloader 4.3.0
+--------+--------------------------------------------------+--------+
|     10 | Candidate For Goddess OVA                        |        |
|      9 | Candidate For Goddess                            |        |
|      8 | Ah! My Goddess: The Movie (Dub)                  |        |
|      7 | Ah! My Goddess: Itsumo Futari De                 |        |
|      6 | Ah! My Goddess: Everyone Has Wings               |        |
|      5 | Ah! My Goddess The Movie                         |        |
|      4 | Ah! My Goddess OVA                               |        |
|      3 | Ah! My Goddess - Flights of Fancy Specials (Dub) |        |
|      2 | Ah! My Goddess - Flights of Fancy (Dub)          |        |
|      1 | Ah! My Goddess                                   |        |
|--------+--------------------------------------------------+--------|
|   SlNo | Title                                            | Meta   |
+--------+--------------------------------------------------+--------+
Enter the anime no:  [1]: 4
anime: Selected Ah! My Goddess OVA
anime: Extracting episode info from page
anime: Found anime: Ah! My Goddess OVA
anime: Downloading to /media/tzulberti/217d93ee-8bf5-4251-ab12-a42ffec137ae/otros/Downloads
ERROR: name 'loggger' is not defined

```

**Comment by Blatzar** [comment]
Probably due to this: https://github.com/vn-ki/anime-downloader/commit/57f82b7a4e60ad634bfdbd3077dcfb9877edd4e0
Update from git to solve this.

Please use `anime -ll DEBUG dl` in the future to make debugging easier.
Wouldn't recommend kickass as it's quite inconsistent.

**Comment by ArjixGamer** [comment]
also, the folder path looks like it contains some kind of hash or address. are you on a server?

**Comment by tzulberti** [comment]
> Probably due to this: [57f82b7](https://github.com/vn-ki/anime-downloader/commit/57f82b7a4e60ad634bfdbd3077dcfb9877edd4e0)
> Update from git to solve this.

Thank you.

> 
> Please use `anime -ll DEBUG dl` in the future to make debugging easier.
> Wouldn't recommend kickass as it's quite inconsistent.

My bad. The issue template mention:  `--log-level`  but when I used it I got the following error:

``` 
anime dl --provider kickass --log-level DEBUG Goddess
Usage: anime dl [OPTIONS] ANIME_URL
Try 'anime dl --help' for help.

Error: no such option: --log-level
``` 

I have just realized that the `--log-level`  should go before the `dl` subcommand. 

Again, my bad

**Comment by parthibann** [comment]
Facing the same issue:
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/anime_downloader/commands/dl.py", line 112, in command
    for episode in animes:
  File "/usr/local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 198, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/usr/local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 293, in __init__
    try_data()
  File "/usr/local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 291, in try_data
    self.source().stream_url
  File "/usr/local/lib/python3.6/site-packages/anime_downloader/extractors/base_extractor.py", line 29, in stream_url
    self.get_data()
  File "/usr/local/lib/python3.6/site-packages/anime_downloader/extractors/base_extractor.py", line 41, in get_data
    data = self._get_data()
  File "/usr/local/lib/python3.6/site-packages/anime_downloader/extractors/vidstream.py", line 41, in _get_data
    return self._get_link(sources)
  File "/usr/local/lib/python3.6/site-packages/anime_downloader/extractors/vidstream.py", line 72, in _get_link
    loggger.debug("The streaming link's quality cannot be identified.")
NameError: name 'loggger' is not defined

**Comment by Blatzar** [comment]
> Facing the same issue:
> NameError: name 'loggger' is not defined

> Probably due to this: [57f82b7](https://github.com/vn-ki/anime-downloader/commit/57f82b7a4e60ad634bfdbd3077dcfb9877edd4e0)
> Update from git to solve this.
