### ISSUE TITLE
Problem with animepahe

### ISSUE THREAD

**Issue by gingerbeardman** [vn-ki/anime-downloader#382]
**Describe the bug**

AttributeError: 'NoneType' object has no attribute 'groups'

**To reproduce**

```
$ anime -ll DEBUG dl 'penguin highway' --provider animepahe
```

<details>
<summary>LOG</summary>

```
matt@matt:~$ anime -ll DEBUG dl 'penguin highway' --provider animepahe
2020-05-31 19:03:27 matt.local anime_downloader.util[40941] INFO anime-downloader 4.3.0
2020-05-31 19:03:27 matt.local anime_downloader.util[40941] DEBUG Platform: macOS-10.14.6-x86_64-i386-64bit
2020-05-31 19:03:27 matt.local anime_downloader.util[40941] DEBUG Python 3.8.2
2020-05-31 19:03:27 matt.local anime_downloader.sites.helpers.request[40941] DEBUG -----
2020-05-31 19:03:27 matt.local anime_downloader.sites.helpers.request[40941] DEBUG GET https://animepahe.com/api
2020-05-31 19:03:27 matt.local anime_downloader.sites.helpers.request[40941] DEBUG {'params': {'l': 8, 'm': 'search', 'q': 'penguin highway'}}
2020-05-31 19:03:27 matt.local anime_downloader.sites.helpers.request[40941] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11'}
2020-05-31 19:03:27 matt.local anime_downloader.sites.helpers.request[40941] DEBUG -----
2020-05-31 19:03:27 matt.local anime_downloader.session[40941] DEBUG cached request
2020-05-31 19:03:27 matt.local anime_downloader.sites.helpers.request[40941] DEBUG https://animepahe.com/api?l=8&m=search&q=penguin+highway
2020-05-31 19:03:27 matt.local anime_downloader.sites.helpers.request[40941] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedlpl8av4dq/tmp2_e8g554
2020-05-31 19:03:27 matt.local anime_downloader.sites.animepahe[40941] DEBUG Penguin Highway
+--------+-----------------+--------+
|      1 | Penguin Highway |        |
|--------+-----------------+--------|
|   SlNo | Title           | Meta   |
+--------+-----------------+--------+
Enter the anime no:  [1]: 1
2020-05-31 19:03:31 matt.local anime_downloader.util[40941] INFO Selected Penguin Highway
2020-05-31 19:03:31 matt.local anime_downloader.sites.anime[40941] INFO Extracting episode info from page
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG -----
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG GET https://animepahe.com/anime/penguin-highway
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG {}
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11'}
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG -----
send: b'GET /anime/penguin-highway HTTP/1.1\r\nHost: animepahe.com\r\nConnection: keep-alive\r\nUpgrade-Insecure-Requests: 1\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.9\r\nAccept-Encoding: gzip, deflate\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 31 May 2020 18:03:31 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d69e06468082beb7ff893f06b45df77291590948211; expires=Tue, 30-Jun-20 18:03:31 GMT; path=/; domain=.animepahe.com; HttpOnly; SameSite=Lax; Secure
header: Vary: Accept-Encoding
header: Cache-Control: no-cache, private
header: Set-Cookie: XSRF-TOKEN=eyJpdiI6IlBsam1ZaGlaYmQyZ1RQUm81dldiZnc9PSIsInZhbHVlIjoiY0pia2p6UUpHaGF4cXBsM2NUYWR5aUpDRW9JeEY0c1FxTVluT3YrVmphVUZxTUNyd3VqcUpZeDJHNkhIaFlXdCIsIm1hYyI6Ijg1YWI0OWUzZWFhNmJhMWZkNzMzYzVhMjY0N2UyMGUyZjkyY2Y5ZjkwMDQ2NGU1NDdjOTVkY2VjOTEwYmVjMWQifQ%3D%3D; expires=Sun, 31-May-2020 20:03:31 GMT; Max-Age=7200; path=/
header: Set-Cookie: laravel_session=eyJpdiI6InlYQ1VCRUdlc09MVWwyQjlXTnBheUE9PSIsInZhbHVlIjoiZWNcL0k2dE1IMWd1QWNrU1FseG9QTEtHanE1KzVVN1FXQXNiWXQxZnZPWDZpYzNwQXFmUHNVVHg3eUZUYldcL2tJIiwibWFjIjoiYTZlYWVjZWI4Zjg1ZjdkMDQ3MWJhNDgxYWVhZjU4NmI5ZjFkZjI2Mzc3NDEyOGQ2MTZmMmUyNTljNTVkZDI2MSJ9; expires=Sun, 31-May-2020 20:03:31 GMT; Max-Age=7200; path=/; httponly
header: Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 030d80421f00000722759ae200000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 59c29cb03b900722-LHR
header: Content-Encoding: gzip
header: alt-svc: h3-27=":443"; ma=86400
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG https://animepahe.com/anime/penguin-highway
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedlpl8av4dq/tmpzxbalboi
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG -----
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG GET https://animepahe.com/api
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG {'params': {'m': 'release', 'id': '3132', 'sort': 'episode_asc', 'page': 1}}
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11'}
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG -----
2020-05-31 19:03:31 matt.local anime_downloader.session[40941] DEBUG cached request
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG https://animepahe.com/api?id=3132&m=release&page=1&sort=episode_asc
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedlpl8av4dq/tmpy4zp4pa0
2020-05-31 19:03:31 matt.local anime_downloader.commands.dl[40941] INFO Found anime: Penguin Highway
2020-05-31 19:03:31 matt.local anime_downloader.commands.dl[40941] INFO Downloading to /Users/matt/Downloads/1234_JD
2020-05-31 19:03:31 matt.local anime_downloader.sites.anime[40941] DEBUG Extracting stream info of id: https://animepahe.com/anime/penguin-highway/29450
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG -----
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG GET https://animepahe.com/anime/penguin-highway/29450
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG {}
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11'}
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG -----
send: b'GET /anime/penguin-highway/29450 HTTP/1.1\r\nHost: animepahe.com\r\nConnection: keep-alive\r\nUpgrade-Insecure-Requests: 1\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.9\r\nAccept-Encoding: gzip, deflate\r\nCookie: __cfduid=d69e06468082beb7ff893f06b45df77291590948211; XSRF-TOKEN=eyJpdiI6IlBsam1ZaGlaYmQyZ1RQUm81dldiZnc9PSIsInZhbHVlIjoiY0pia2p6UUpHaGF4cXBsM2NUYWR5aUpDRW9JeEY0c1FxTVluT3YrVmphVUZxTUNyd3VqcUpZeDJHNkhIaFlXdCIsIm1hYyI6Ijg1YWI0OWUzZWFhNmJhMWZkNzMzYzVhMjY0N2UyMGUyZjkyY2Y5ZjkwMDQ2NGU1NDdjOTVkY2VjOTEwYmVjMWQifQ%3D%3D; laravel_session=eyJpdiI6InlYQ1VCRUdlc09MVWwyQjlXTnBheUE9PSIsInZhbHVlIjoiZWNcL0k2dE1IMWd1QWNrU1FseG9QTEtHanE1KzVVN1FXQXNiWXQxZnZPWDZpYzNwQXFmUHNVVHg3eUZUYldcL2tJIiwibWFjIjoiYTZlYWVjZWI4Zjg1ZjdkMDQ3MWJhNDgxYWVhZjU4NmI5ZjFkZjI2Mzc3NDEyOGQ2MTZmMmUyNTljNTVkZDI2MSJ9\r\n\r\n'
reply: 'HTTP/1.1 302 Found\r\n'
header: Date: Sun, 31 May 2020 18:03:31 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Cache-Control: no-cache, private
header: Location: https://animepahe.com/play/penguin-highway/b78c7b6276bd0e8de577f4b5b6a38cd3a0c589afe8086b1a96fec8bc3114d6db
header: Set-Cookie: XSRF-TOKEN=eyJpdiI6IkYzYUZqcUNlUGNTK0pQaFVUZDlzbXc9PSIsInZhbHVlIjoiXC9LYitEaGlmY3Y0VzFmbXFlVllZSFwvMXZqOGF3RGlnQUNcL0ZhaldSc0ZIZUZINWE0ZzFuV3ZkWTh2TjRkcU9mbCIsIm1hYyI6IjhlNmJiMDEzYzI1ZWFkOGFlMzZiZmZiNDhjODY4YzJiNWY0ZWZiZjI5MTQxYTkyMzY4ODlmMmNlMThhNzBlNzUifQ%3D%3D; expires=Sun, 31-May-2020 20:03:31 GMT; Max-Age=7200; path=/
header: Set-Cookie: laravel_session=eyJpdiI6IkkxeGNNRUNSREVmSkVSQjlmMEZmTmc9PSIsInZhbHVlIjoiVjd3T3FWKzhlWWJwNnV4Vzc3blBYWmV1bWoxZGh6ZGpGbEE1STJ0N2xJZGdaOVNKRlZmZk5UZWxYXC84alh5TVwvIiwibWFjIjoiYzBiMTdhNWNhNjdlOTUyYjEyMDAzM2UxMjIwM2Y2ZGY0ZDRjZjViOTI1M2JmYjYyZjIxNzBhODYxZDFjYTk2MiJ9; expires=Sun, 31-May-2020 20:03:31 GMT; Max-Age=7200; path=/; httponly
header: Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 030d80428b00000722759b5200000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 59c29cb0dd770722-LHR
header: alt-svc: h3-27=":443"; ma=86400
send: b'GET /play/penguin-highway/b78c7b6276bd0e8de577f4b5b6a38cd3a0c589afe8086b1a96fec8bc3114d6db HTTP/1.1\r\nHost: animepahe.com\r\nConnection: keep-alive\r\nUpgrade-Insecure-Requests: 1\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.9\r\nAccept-Encoding: gzip, deflate\r\nCookie: __cfduid=d69e06468082beb7ff893f06b45df77291590948211; XSRF-TOKEN=eyJpdiI6IkYzYUZqcUNlUGNTK0pQaFVUZDlzbXc9PSIsInZhbHVlIjoiXC9LYitEaGlmY3Y0VzFmbXFlVllZSFwvMXZqOGF3RGlnQUNcL0ZhaldSc0ZIZUZINWE0ZzFuV3ZkWTh2TjRkcU9mbCIsIm1hYyI6IjhlNmJiMDEzYzI1ZWFkOGFlMzZiZmZiNDhjODY4YzJiNWY0ZWZiZjI5MTQxYTkyMzY4ODlmMmNlMThhNzBlNzUifQ%3D%3D; laravel_session=eyJpdiI6IkkxeGNNRUNSREVmSkVSQjlmMEZmTmc9PSIsInZhbHVlIjoiVjd3T3FWKzhlWWJwNnV4Vzc3blBYWmV1bWoxZGh6ZGpGbEE1STJ0N2xJZGdaOVNKRlZmZk5UZWxYXC84alh5TVwvIiwibWFjIjoiYzBiMTdhNWNhNjdlOTUyYjEyMDAzM2UxMjIwM2Y2ZGY0ZDRjZjViOTI1M2JmYjYyZjIxNzBhODYxZDFjYTk2MiJ9\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 31 May 2020 18:03:31 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Vary: Accept-Encoding
header: Set-Cookie: res=720; expires=Mon, 31-May-2021 18:03:31 GMT; Max-Age=31536000; path=/
header: Cache-Control: no-cache, private
header: Set-Cookie: XSRF-TOKEN=eyJpdiI6Ik5LazhYZmtVT0dKakhFd0VVUUljVXc9PSIsInZhbHVlIjoia3lySnpCMFc5WVFZbVdDa1cwcEgyS0xXVjBpN2J1SFdScU83Qk1OcG4yV01DT0l6YnMrQWs1NXNOSnMzTlBJViIsIm1hYyI6ImZkZGQzYWYwYjkxM2VmZTMyOGUzMjcxMDM2YzllZDNkNTNiY2YwNDQ4OTQ3MjgxYjNiY2ViNmVkODg5NDY2YTUifQ%3D%3D; expires=Sun, 31-May-2020 20:03:31 GMT; Max-Age=7200; path=/
header: Set-Cookie: laravel_session=eyJpdiI6Ink0XC9cL0dGS1dFTlFvMkxHanQxZkMwQT09IiwidmFsdWUiOiJZVFBZVm9GUEhaSDF4Z3JmOW0rWVpqWEdmMTdMa1B1d2ZXK2NvTlM3UWJETjQ5MjdGVFpDODFcL3N6Sis5QkxaayIsIm1hYyI6Ijg1ZDlhZmU5MDg0ZTViZGMzMDU1NTEyZjU4Njk0MzNhNDQwYWZiZDE3ZDQ5ZDQzMGYzNjE1OGEzOTJjZjQ0OGQifQ%3D%3D; expires=Sun, 31-May-2020 20:03:31 GMT; Max-Age=7200; path=/; httponly
header: Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 030d80433400000722759bd200000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
header: CF-RAY: 59c29cb1e89e0722-LHR
header: Content-Encoding: gzip
header: alt-svc: h3-27=":443"; ma=86400
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG https://animepahe.com/play/penguin-highway/b78c7b6276bd0e8de577f4b5b6a38cd3a0c589afe8086b1a96fec8bc3114d6db
2020-05-31 19:03:31 matt.local anime_downloader.sites.helpers.request[40941] DEBUG /var/folders/sy/jcz9n9dn2t98677rzpmyvkr00000gn/T/animedlpl8av4dq/tmpvpm5b0r6
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader==4.3.0', 'console_scripts', 'anime')()
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/commands/dl.py", line 112, in command
    for episode in animes:
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 198, in __iter__
    yield episode_class(ep_id[1], parent=self, ep_no=ep_id[0])
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 293, in __init__
    try_data()
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 289, in try_data
    self.get_data()
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/sites/anime.py", line 349, in get_data
    self._sources = self._get_sources()
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/sites/animepahe.py", line 42, in _get_sources
    episode_id, session_id = re.search(r'getEmbeds\((\d+), "([^"]+)', source_text).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
matt@matt:~$


```

**Comment by ArjixGamer** [comment]
anime pahe is broken, dont post issues on it

**Comment by MichaelDavidJohnson** [comment]
As an append to Arjix's comment. Don't make repeated issues. You could have made this into one issue "problems with many sites" and then it wouldn't clog our notifs.

**Comment by gingerbeardman** [comment]
@MichaelDavidJohnson OK if that's what you want me to do in future. I had mentioned it earlier in https://github.com/vn-ki/anime-downloader/issues/374#issuecomment-633968137 and did not get any guidance at that point that multiple issues were frowned upon
