### ISSUE TITLE
Problem with erai-raws

### ISSUE THREAD

**Issue by gingerbeardman** [vn-ki/anime-downloader#386]
**Describe the bug**

    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://ddgu.ddos-guard.net/ddgu/

**To reproduce**

```
anime -ll DEBUG dl 'penguin highway' --provider erai-raws
```

<details>
<summary>LOG</summary>

```

matt@matt:~$ anime -ll DEBUG dl 'penguin highway' --provider erai-raws
2020-05-31 19:11:02 matt.local anime_downloader.util[41698] INFO anime-downloader 4.3.0
2020-05-31 19:11:02 matt.local anime_downloader.util[41698] DEBUG Platform: macOS-10.14.6-x86_64-i386-64bit
2020-05-31 19:11:02 matt.local anime_downloader.util[41698] DEBUG Python 3.8.2
2020-05-31 19:11:02 matt.local anime_downloader.sites.helpers.request[41698] DEBUG -----
2020-05-31 19:11:02 matt.local anime_downloader.sites.helpers.request[41698] DEBUG POST https://ddgu.ddos-guard.net/ddgu/
2020-05-31 19:11:02 matt.local anime_downloader.sites.helpers.request[41698] DEBUG {'data': {'u': b'aHR0cHM6Ly9lcmFpLXJhd3MuaW5mby9hbmltZS1saXN0Lw==', 'h': b'aHR0cHM6Ly9lcmFpLXJhd3MuaW5mbw==', 'p': ''}, 'allow_redirects': False}
2020-05-31 19:11:02 matt.local anime_downloader.sites.helpers.request[41698] DEBUG {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11', 'Referer': 'https://erai-raws.info/anime-list/'}
2020-05-31 19:11:02 matt.local anime_downloader.sites.helpers.request[41698] DEBUG -----
send: b'POST /ddgu/ HTTP/1.1\r\nHost: ddgu.ddos-guard.net\r\nuser-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.66 Safari/535.11\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nReferer: https://erai-raws.info/anime-list/\r\nContent-Length: 96\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'h=aHR0cHM6Ly9lcmFpLXJhd3MuaW5mbw%3D%3D&p=&u=aHR0cHM6Ly9lcmFpLXJhd3MuaW5mby9hbmltZS1saXN0Lw%3D%3D'
reply: 'HTTP/1.1 503 Service Unavailable\r\n'
header: Server: ddos-guard
header: Date: Sun, 31 May 2020 18:11:02 GMT
header: Connection: close
header: Cache-Control: no-cache, no-store, must-revalidate
header: Content-Type: text/html; charset=UTF-8
header: Content-Length: 11178
2020-05-31 19:11:02 matt.local anime_downloader.session[41698] DEBUG uncached request
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    load_entry_point('anime-downloader==4.3.0', 'console_scripts', 'anime')()
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/cli.py", line 53, in main
    cli()
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/commands/dl.py", line 92, in command
    anime_url = util.search(anime_url, provider, choice)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/util.py", line 79, in search
    search_results = cls.search(query)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/sites/erairaws.py", line 44, in search
    cls.bypass(cls)
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/sites/erairaws.py", line 17, in bypass
    bypass_link = helpers.post('https://ddgu.ddos-guard.net/ddgu/', data = {'u':u, 'h':h, 'p':''}, headers = {'Referer': url}, allow_redirects = False).headers["Location"]
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/anime_downloader/sites/helpers/request.py", line 67, in setup_func
    res.raise_for_status()
  File "/usr/local/Cellar/anime-downloader/HEAD-16c6268/libexec/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://ddgu.ddos-guard.net/ddgu/
matt@matt:~$

```

**Comment by ArjixGamer** [comment]
it seems that either anime dl got blocked by ddos guard or their service has problems.
`requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://ddgu.ddos-guard.net/ddgu/
matt@matt:~$`

**Comment by AbdullahM0hamed** [comment]
Ddos Guard changed how the way they function. Will look into it.
