### ISSUE TITLE
i am getting a"No connection adapters were found for ''https://9anime.is/watch/fullmetal-alchemist-brotherhood.0r7/j69y93''" error when i enter anime dl 'https://9anime.is/watch/fullmetal-alchemist-brotherhood.0r7/j69y93' --episodes 1 as 

### ISSUE THREAD

**Issue by redfanglicker** [vn-ki/anime-downloader#46]
`**Describe` the bug**

**To reproduce**

```
INFO root: anime-downloader 3.2.0
DEBUG root: Platform: Windows-10-10.0.17713-SP0
DEBUG root: Python 3.7.0
INFO root: Extracting episode info from page
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\program files\python37\lib\site-packages\anime_downloader\cli.py", line 89, in dl
    anime = cls(anime_url, quality=quality)
  File "c:\program files\python37\lib\site-packages\anime_downloader\sites\anime.py", line 39, in __init__
    self.get_data()
  File "c:\program files\python37\lib\site-packages\anime_downloader\sites\anime.py", line 49, in get_data
    r = requests.get(self.url, headers=desktop_headers)
  File "c:\program files\python37\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "c:\program files\python37\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\program files\python37\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\program files\python37\lib\site-packages\requests\sessions.py", line 616, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\program files\python37\lib\site-packages\requests\sessions.py", line 707, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for ''https://www8.9anime.is/watch/my-hero-academia-3.l7yq/93kpjn''
```

<details>
<summary>LOG</summary>

```


```

</details>

**Comment by vn-ki** [comment]
I see that documentation had the other one. I have updated the documentation. 

9anime sometimes redirects 9anime.is to their correct domain.

**Comment by vn-ki** [comment]
I was too hasty to close the issue. The issue is not what I have mentioned above. It is something else.

Please check your internet connection and report please. If it still doesn't solve your problem, I will reopen the issue.
