### ISSUE TITLE
Character Encode Error

### ISSUE THREAD

**Issue by Arthurdw** [vn-ki/anime-downloader#469]
**Describe the bug**
Title pretty much describes the problem, but to be more specific here's an image.
![Error THinus](https://brain.is-inside.me/ZokkH94q.png)

**To reproduce**
```
anime dl "fate extra"
```

<details>
<summary>LOG</summary>

```
Try 'anime dl --help' for help.

Error: no such option: --log-level
```

EHHH

**Comment by ArjixGamer** [comment]
--log-level is an option for ``anime`` alone. Not for ``anime dl``. Try ``anime -ll DEBUG dl "fate extra"`` -ll DEBUG is the short for --log-level DEBUG.

**Comment by ArjixGamer** [comment]
Plz send the correct logs

**Comment by Blatzar** [comment]
Internal downloader issue most likely. Use aria2, either place {aria2} in config (as external_downloader) or remove your config to let it regenerate with aria2.

**Comment by Arthurdw** [comment]
@ArjixGamer here you go:
<details>
<summary>LOG</summary>
```
PS E:\Anime\dl> anime -ll DEBUG dl "fate extra"
2020-08-13 23:21:40 DESKTOP-G6QORQG anime_downloader.util[15444] INFO anime-downloader 4.2.0
2020-08-13 23:21:40 DESKTOP-G6QORQG anime_downloader.util[15444] DEBUG Platform: Windows-10-10.0.18362-SP0
2020-08-13 23:21:40 DESKTOP-G6QORQG anime_downloader.util[15444] DEBUG Python 3.8.3
2020-08-13 23:21:40 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG -----
2020-08-13 23:21:40 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG GET https://twist.moe/api/anime
2020-08-13 23:21:40 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG {}
2020-08-13 23:21:40 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.46 Safari/537.36', 'x-access-token': '1rj2vRtegS8Y60B3w3qNZm5T2Q0TN2NR'}
2020-08-13 23:21:40 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG -----
2020-08-13 23:21:40 DESKTOP-G6QORQG anime_downloader.session[15444] DEBUG cached request
2020-08-13 23:21:40 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG https://twist.moe/api/anime
2020-08-13 23:21:40 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG C:\Users\GEBRUI~1\AppData\Local\Temp\animedlhzhurir8\tmp0j9gqm_w
+--------+---------------------------------------------+--------+
|      5 | Fate/kaleid liner Prisma☆Illya              |        |
|      4 | Fate/kaleid liner Prisma☆Illya 3rei!!       |        |
|      3 | Fate/stay night: Unlimited Blade Works (TV) |        |
|      2 | Fate/stay night                             |        |
|      1 | Fate/Extra Last Encore                      |        |
|--------+---------------------------------------------+--------|
|   SlNo | Title                                       | Meta   |
+--------+---------------------------------------------+--------+
Enter the anime no:  [1]:
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.util[15444] INFO Selected Fate/Extra Last Encore
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.sites.anime[15444] INFO Extracting episode info from page
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG -----
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG GET https://twist.moe/api/anime/fate-extra-last-encore/sources
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG {}
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.46 Safari/537.36', 'x-access-token': '1rj2vRtegS8Y60B3w3qNZm5T2Q0TN2NR'}
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG -----
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.session[15444] DEBUG cached request
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG https://twist.moe/api/anime/fate-extra-last-encore/sources
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.sites.helpers.request[15444] DEBUG C:\Users\GEBRUI~1\AppData\Local\Temp\animedlhzhurir8\tmpmss0iu46
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.commands.dl[15444] INFO Found anime: fate-extra-last-encore
INFO:anime_downloader.commands.dl:Found anime: fate-extra-last-encore
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.commands.dl[15444] INFO Downloading to E:\Anime\dl
INFO:anime_downloader.commands.dl:Downloading to E:\Anime\dl
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.sites.anime[15444] DEBUG Extracting stream info of id: https://twist.moe/anime/fateextra/[Chyuu] Fate⁄EXTRA Last Encore - 01 [720p][AB90BA3C].mp4
DEBUG:anime_downloader.sites.anime:Extracting stream info of id: https://twist.moe/anime/fateextra/[Chyuu] Fate⁄EXTRA Last Encore - 01 [720p][AB90BA3C].mp4
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.sites.anime[15444] DEBUG Sources : [('no_extractor', 'https://twist.moe/anime/fateextra/[Chyuu] Fate⁄EXTRA Last Encore - 01 [720p][AB90BA3C].mp4')]
DEBUG:anime_downloader.sites.anime:Sources : [('no_extractor', 'https://twist.moe/anime/fateextra/[Chyuu] Fate⁄EXTRA Last Encore - 01 [720p][AB90BA3C].mp4')]
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.sites.anime[15444] INFO Downloading fate-extra-last-encore-1
INFO:anime_downloader.sites.anime:Downloading fate-extra-last-encore-1
2020-08-13 23:21:43 DESKTOP-G6QORQG anime_downloader.downloader.base_downloader[15444] INFO .\../fate-extra-last-encore/fate-extra-last-encore_01.mp4
INFO:anime_downloader.downloader.base_downloader:.\../fate-extra-last-encore/fate-extra-last-encore_01.mp4
Traceback (most recent call last):
  File "C:\Python38\Scripts\anime-script.py", line 11, in <module>
    load_entry_point('anime-downloader==4.2.0', 'console_scripts', 'anime')()
  File "c:\python38\lib\site-packages\anime_downloader\cli.py", line 53, in main
    cli()
  File "c:\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python38\lib\site-packages\anime_downloader\commands\dl.py", line 136, in command
    episode.download(force=force_download,
  File "c:\python38\lib\site-packages\anime_downloader\sites\anime.py", line 385, in download
    downloader.download()
  File "c:\python38\lib\site-packages\anime_downloader\downloader\base_downloader.py", line 55, in download
    self.check_if_exists()
  File "c:\python38\lib\site-packages\anime_downloader\downloader\base_downloader.py", line 34, in check_if_exists
    r = session.get_session().get(
  File "c:\python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "c:\python38\lib\site-packages\requests_cache\core.py", line 132, in request
    response = super(CachedSession, self).request(
  File "c:\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python38\lib\site-packages\requests_cache\core.py", line 109, in send
    return send_request_and_cache_response()
  File "c:\python38\lib\site-packages\requests_cache\core.py", line 97, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "c:\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "c:\python38\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\python38\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python38\lib\http\client.py", line 1281, in _send_request
    self.putheader(hdr, value)
  File "c:\python38\lib\http\client.py", line 1213, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2044' in position 46: ordinal not in range(256)
```
</details>

@Blatzar yeah that fixes it.
