### ISSUE TITLE
ERROR: HTTPSConnectionPool + ERROR: (with no detail)

### ISSUE THREAD

**Issue by falcorr** [vn-ki/anime-downloader#476]
I've just come across the utility and haven't had much luck with it. There's a lot of time between error and last output, like something is really struggling. I've had one episode complete so far, the rest of my experience has been errors such as below. When the one episode did download, it also used the 'internal downloader' and said aria2 would be faster - aria2 is available and works via PATH.

**Describe the bug**
`ERROR: HTTPSConnectionPool(host='s5.mp4upload.com', port=282): Max retries exceeded with url: /d/qcxzxrtqz3b4quuoxovegiask5lbqvcatigj6b7ljwujw6goztvrhfua/Ovvideo.mp4 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))`
and also
`ERROR: (with no detail)`

**To reproduce**
`anime dl "Overlord" --provider justdubs`
and
`anime dl "Overlord" --provider 9anime --episodes 2:13`
respectively

<details>
<summary>LOG</summary>
Error: no such option: --log-level

**Comment by MichaelDavidJohnson** [comment]
`anime -ll DEBUG dl "Overlord" -- provider justdubs`

**Comment by MichaelDavidJohnson** [comment]
Aria2 needs to be selected either with the `-xd` flag or changing the config.

**Comment by falcorr** [comment]
(there's that very long delay in action) I'll post after it finally gives up.

Some thoughts: could the delay be involved, e.g. a window of time for a certificate closing up. Or, an issue with timezones.

**Comment by falcorr** [comment]
```
G:\Youtubing>anime -ll DEBUG dl "Overlord" --provider justdubs
2020-08-20 13:18:53 CPC anime_downloader.util[33580] INFO anime-downloader 4.6.3
2020-08-20 13:18:53 CPC anime_downloader.util[33580] DEBUG Platform: Windows-10-10.0.18362-SP0
2020-08-20 13:18:53 CPC anime_downloader.util[33580] DEBUG Python 3.7.4
2020-08-20 13:18:53 CPC anime_downloader.sites.helpers.request[33580] DEBUG -----
2020-08-20 13:18:53 CPC anime_downloader.sites.helpers.request[33580] DEBUG GET http://justdubs.org/search/node/Overlord
2020-08-20 13:18:53 CPC anime_downloader.sites.helpers.request[33580] DEBUG {}
2020-08-20 13:18:53 CPC anime_downloader.sites.helpers.request[33580] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36'}
2020-08-20 13:18:53 CPC anime_downloader.sites.helpers.request[33580] DEBUG -----
2020-08-20 13:18:53 CPC anime_downloader.session[33580] DEBUG cached request
2020-08-20 13:18:53 CPC anime_downloader.sites.helpers.request[33580] DEBUG http://justdubs.org/search/node/Overlord
2020-08-20 13:18:53 CPC anime_downloader.sites.helpers.request[33580] DEBUG C:\Users\DYIMYS~1\AppData\Local\Temp\animedlp2r1_qwc\tmplm787bl3
2020-08-20 13:18:53 CPC anime_downloader.sites.justdubs[33580] DEBUG [<a href="http://justdubs.org/watch-overlord-season-3-english-dubbed">Overlord Season 3</a>, <a href="http://justdubs.org/watch-overlord-season-2-english-dubbed">Overlord Season 2</a>, <a href="http://justdubs.org/watch-overlord-english-dubbed">Overlord</a>, <a href="http://justdubs.org/watch-disgaea-netherworld-battle-chronicle-english-dubbed">Disgaea: Netherworld Battle Chronicle</a>, <a href="http://justdubs.org/watch-isekai-quartet-2nd-season-english-dubbed">ISEKAI QUARTET 2nd Season</a>, <a href="http://justdubs.org/watch-legend-mystical-ninja-english-dubbed">Legend of the Mystical Ninja</a>]
+--------+---------------------------------------+--------+
|      6 | Legend of the Mystical Ninja          |        |
|      5 | ISEKAI QUARTET 2nd Season             |        |
|      4 | Disgaea: Netherworld Battle Chronicle |        |
|      3 | Overlord                              |        |
|      2 | Overlord Season 2                     |        |
|      1 | Overlord Season 3                     |        |
|--------+---------------------------------------+--------|
|   SlNo | Title                                 | Meta   |
+--------+---------------------------------------+--------+
Enter the anime no: [1]: 1
2020-08-20 13:18:59 CPC anime_downloader.util[33580] INFO Selected Overlord Season 3
2020-08-20 13:18:59 CPC anime_downloader.sites.anime[33580] INFO Extracting episode info from page
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG -----
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG GET http://justdubs.org/watch-overlord-season-3-english-dubbed
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG {}
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36'}
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG -----
2020-08-20 13:18:59 CPC anime_downloader.session[33580] DEBUG cached request
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG http://justdubs.org/watch-overlord-season-3-english-dubbed
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG C:\Users\DYIMYS~1\AppData\Local\Temp\animedlp2r1_qwc\tmp6b1mbqo7
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG -----
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG GET http://justdubs.org/watch-overlord-season-3-english-dubbed
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG {}
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36'}
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG -----
2020-08-20 13:18:59 CPC anime_downloader.session[33580] DEBUG cached request
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG http://justdubs.org/watch-overlord-season-3-english-dubbed
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG C:\Users\DYIMYS~1\AppData\Local\Temp\animedlp2r1_qwc\tmpph63j_qp
2020-08-20 13:18:59 CPC anime_downloader.sites.anime[33580] DEBUG EPISODE IDS: length: 13, ids: ['http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-1', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-2', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-3', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-4', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-5', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-6', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-7', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-8', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-9', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-10', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-11', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-12', 'http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-13']
2020-08-20 13:18:59 CPC anime_downloader.commands.dl[33580] INFO Found anime: Overlord Season 3
2020-08-20 13:18:59 CPC anime_downloader.commands.dl[33580] INFO Downloading to G:\Youtubing
2020-08-20 13:18:59 CPC anime_downloader.sites.anime[33580] DEBUG Extracting stream info of id: http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-1
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG -----
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG GET http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-1
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG {}
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36'}
2020-08-20 13:18:59 CPC anime_downloader.sites.helpers.request[33580] DEBUG -----
send: b'GET /watch-overlord-season-3-english-dubbed/ep-1 HTTP/1.1\r\nHost: justdubs.org\r\nuser-agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Thu, 20 Aug 2020 03:19:00 GMT
header: Content-Type: text/html; charset=utf-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=dacdbbbb6b4036d034b8881fffcd7cacd1597893539; expires=Sat, 19-Sep-20 03:18:59 GMT; path=/; domain=.justdubs.org; HttpOnly; SameSite=Lax
header: X-Drupal-Cache: MISS
header: Expires: Sun, 19 Nov 1978 05:00:00 GMT
header: Last-Modified: Thu, 20 Aug 2020 03:19:18 GMT
header: Cache-Control: public, max-age=21600
header: Content-Language: en
header: X-Generator: Drupal 7 (http://drupal.org)
header: Link: <http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-1>; rel="canonical",<http://justdubs.org/node/209074>; rel="shortlink"
header: Vary: Cookie,Accept-Encoding
header: CF-Cache-Status: DYNAMIC
header: cf-request-id: 04ab798ef8000016bd543ed200000001
header: Server: cloudflare
header: CF-RAY: 5c58f859fcc916bd-SYD
header: Content-Encoding: gzip
2020-08-20 13:19:02 CPC anime_downloader.session[33580] DEBUG uncached request
2020-08-20 13:19:02 CPC anime_downloader.sites.helpers.request[33580] DEBUG http://justdubs.org/watch-overlord-season-3-english-dubbed/ep-1
2020-08-20 13:19:02 CPC anime_downloader.sites.helpers.request[33580] DEBUG C:\Users\DYIMYS~1\AppData\Local\Temp\animedlp2r1_qwc\tmpeu_f_slz
2020-08-20 13:19:02 CPC anime_downloader.sites.anime[33580] DEBUG Sources : [('mp4upload', 'https://www.mp4upload.com/embed-2dwuyvyqilgf.html')]
2020-08-20 13:19:02 CPC anime_downloader.sites.helpers.request[33580] DEBUG -----
2020-08-20 13:19:02 CPC anime_downloader.sites.helpers.request[33580] DEBUG GET https://www.mp4upload.com/embed-2dwuyvyqilgf.html
2020-08-20 13:19:02 CPC anime_downloader.sites.helpers.request[33580] DEBUG {}
2020-08-20 13:19:02 CPC anime_downloader.sites.helpers.request[33580] DEBUG {'user-agent': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36'}
2020-08-20 13:19:02 CPC anime_downloader.sites.helpers.request[33580] DEBUG -----
send: b'GET /embed-2dwuyvyqilgf.html HTTP/1.1\r\nHost: www.mp4upload.com\r\nuser-agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2224.3 Safari/537.36\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Thu, 20 Aug 2020 03:19:03 GMT
header: Server: Apache/2.2.22 (Debian) DAV/2 mod_fcgid/2.3.6 mod_ruby/1.2.6 Ruby/1.8.7(2012-02-08) mod_ssl/2.2.22 OpenSSL/1.0.1t
header: Expires: Wed, 19 Aug 2020 03:19:03 GMT
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
header: Content-Length: 4031
header: Keep-Alive: timeout=5, max=100
header: Connection: Keep-Alive
header: Content-Type: text/html ; charset=UTF-8
2020-08-20 13:19:05 CPC anime_downloader.session[33580] DEBUG uncached request
2020-08-20 13:19:05 CPC anime_downloader.sites.helpers.request[33580] DEBUG https://www.mp4upload.com/embed-2dwuyvyqilgf.html
2020-08-20 13:19:05 CPC anime_downloader.sites.helpers.request[33580] DEBUG C:\Users\DYIMYS~1\AppData\Local\Temp\animedlp2r1_qwc\tmp81476h8q
2020-08-20 13:19:05 CPC anime_downloader.sites.anime[33580] INFO Downloading Overlord Season 3-1
2020-08-20 13:19:05 CPC anime_downloader.downloader.base_downloader[33580] INFO .\Overlord_Season_3/Overlord_Season_3_01.mp4
Traceback (most recent call last):
  File "c:\python\python374-32\lib\site-packages\urllib3\contrib\pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "c:\python\python374-32\lib\site-packages\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "c:\python\python374-32\lib\site-packages\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "c:\python\python374-32\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\python374-32\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "c:\python\python374-32\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "c:\python\python374-32\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "c:\python\python374-32\lib\site-packages\urllib3\connection.py", line 394, in connect
    ssl_context=context,
  File "c:\python\python374-32\lib\site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\python\python374-32\lib\site-packages\urllib3\contrib\pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\python374-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\python\python374-32\lib\site-packages\urllib3\connectionpool.py", line 762, in urlopen
    **response_kw
  File "c:\python\python374-32\lib\site-packages\urllib3\connectionpool.py", line 762, in urlopen
    **response_kw
  File "c:\python\python374-32\lib\site-packages\urllib3\connectionpool.py", line 762, in urlopen
    **response_kw
  [Previous line repeated 7 more times]
  File "c:\python\python374-32\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "c:\python\python374-32\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s5.mp4upload.com', port=282): Max retries exceeded with url: /d/qcxzp4lwz3b4quuosovb6o2ucfcwdzidz2rgremdc4gy5sz4achrmbef/Ovvideo.mp4 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\python374-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\python374-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python374-32\Scripts\anime.exe\__main__.py", line 7, in <module>
  File "c:\python\python374-32\lib\site-packages\anime_downloader\cli.py", line 53, in main
    cli()
  File "c:\python\python374-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python\python374-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python\python374-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python\python374-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python\python374-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python\python374-32\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python\python374-32\lib\site-packages\anime_downloader\commands\dl.py", line 147, in command
    range_size=chunk_size)
  File "c:\python\python374-32\lib\site-packages\anime_downloader\sites\anime.py", line 427, in download
    downloader.download()
  File "c:\python\python374-32\lib\site-packages\anime_downloader\downloader\base_downloader.py", line 55, in download
    self.check_if_exists()
  File "c:\python\python374-32\lib\site-packages\anime_downloader\downloader\base_downloader.py", line 35, in check_if_exists
    self.source.stream_url, headers=headers, stream=True)
  File "c:\python\python374-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "c:\python\python374-32\lib\site-packages\requests_cache\core.py", line 136, in request
    **kwargs
  File "c:\python\python374-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python\python374-32\lib\site-packages\requests_cache\core.py", line 109, in send
    return send_request_and_cache_response()
  File "c:\python\python374-32\lib\site-packages\requests_cache\core.py", line 97, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "c:\python\python374-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\python\python374-32\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='s5.mp4upload.com', port=282): Max retries exceeded with url: /d/qcxzp4lwz3b4quuosovb6o2ucfcwdzidz2rgremdc4gy5sz4achrmbef/Ovvideo.mp4 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

**Comment by falcorr** [comment]
I'm not sure how to find that -xd flag but I've specified aria2 in the config and it appears to be working now. So, the issue is limited to the internal downloader. 

Unrelated but I've just found specifying 720p quality (and fallback 1080p > 480p > 360p) still downloads 1080p.

**Comment by MichaelDavidJohnson** [comment]
`anime -ll DEBUG dl "Overlord" -- provider justdubs -xd {aria2}`

**Comment by MichaelDavidJohnson** [comment]
Quality options are pretty redundant, we can only take what we can get from the provider after all, it's better to just find a provider that has the highest quality for you and stick with that (be it twist.moe or nyaa). 

If your issue is solved, how about join the Discord and close the issue!

**Comment by falcorr** [comment]
Not too fussed, I just wouldn't mind saving a bit of space with 720p which I don't mind for anime. 

Would join Discord but I'm an absolute lurker and basically offer nothing for live chat, hah. 

Thanks for the speedy fix.
