### ISSUE TITLE
Got this error after downloading 60 episodes

### ISSUE THREAD

**Issue by gorybloodfest** [vn-ki/anime-downloader#49]
**Describe the bug**
I was downloading bleach episodes with the command "anime dl bleach" then all of a sudden i got an error. details below.

anime dl bleach

<details>

```
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python\lib\site-packages\anime_downloader\cli.py", line 133, in dl
    format=file_format)
  File "c:\python\lib\site-packages\anime_downloader\sites\anime.py", line 180, in download
    total_size = int(r.headers['Content-length'])
  File "c:\python\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```

</details>

**Comment by vn-ki** [comment]
Does this happen even after retries?

Also how is bleach?

**Comment by phanirithvij** [comment]
I liked it but I suggest leaving the fillers
I mean there are lot of fillers and I think the anime's ending is not that bad compared to the manga's ending

**Comment by vn-ki** [comment]
@phanirithvij Oh. Nice. I think I'll try it out if I get some time.

@gorybloodfest I'll close this issue now.
