### ISSUE TITLE
9anime stopped working again on v.3.4.0

### ISSUE THREAD

**Issue by Alistair1231** [vn-ki/anime-downloader#61]
**Describe the bug**
Hey. first of all, really awesome program. thanks for your work and for publishing and maintaining it. :)
to the bug:  

**To reproduce**  
> tried it on win10 and the ubuntu app from the store. updated node (+node-legacy) and python3 but didin't make any difference.   
```
anime dl "dragon ball" -ll DEBUG
```

```
anime dl "dragon ball" -ll DEBUG
INFO root: anime-downloader 3.4.0
DEBUG root: Platform: Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-16.04-xenial
DEBUG root: Python 3.5.2
DEBUG root: https://www8.9anime.is/search?keyword=dragon+ball
DEBUG root: Search results
DEBUG root: Dragon Ball
DEBUG root: Dragon Ball (Dub)
DEBUG root: Dragon Ball Super
DEBUG root: Dragon Ball Z Kai
DEBUG root: Dragon Ball Super Movie (Dub)
DEBUG root: Dragon Ball Z (Uncrop)
DEBUG root: Dragon Ball GT (Dub)
DEBUG root: Dragon Ball Specials
DEBUG root: Dragon Ball Z
DEBUG root: Dragon Ball Z (Dub)
DEBUG root: Dragon Ball Super Movie
DEBUG root: Dragon Ball Super (Dub)
DEBUG root: Dragon Ball GT
DEBUG root: Dragon Ball Z Kai (Dub)
DEBUG root: Dragon Ball Specials (Dub)
DEBUG root: Dragon Ball Z: Resurrection 'F' (Dub)
DEBUG root: Dragon Ball Z: Resurrection 'F'
DEBUG root: Dragon Ball: Episode of Bardock (Dub)
DEBUG root: Dragon Ball: Episode of Bardock
DEBUG root: Dragon Ball Z Movie 12: Fusion Reborn
DEBUG root: Dragon Ball Z Movie 09: Bojack Unbound (Dub)
DEBUG root: Dragon Ball Z Movie 05: Cooler's Revenge (Dub)
DEBUG root: Dragon Ball Z: Saiya-jin Zetsumetsu Keikaku
DEBUG root: Dragon Ball Z Kai: The Final Chapters (Dub)
DEBUG root: Dragon Ball: Super Saiya-jin Zetsumetsu Keikaku (Dub)
DEBUG root: Dragon Ball Z Movie 12: Fusion Reborn (Dub)
DEBUG root: Dragon Ball Special - History of Japan
DEBUG root: Dragon Ball Movie 3: Mystical Adventure (Dub)
DEBUG root: Dragon Ball Z Movie 05: Cooler's Revenge
DEBUG root: Dragon Ball Z Kai: The Final Chapters
 1: Dragon Ball                                 Ep 153/153
 2: Dragon Ball (Dub)                           DUB | Ep 153/153
 3: Dragon Ball Super                           Ep 131/131
 4: Dragon Ball Z Kai                           Ep 98/98
 5: Dragon Ball Super Movie (Dub)               DUB | Preview
 6: Dragon Ball Z (Uncrop)                      Ep ?/291
 7: Dragon Ball GT (Dub)                        DUB | Ep 64/64
 8: Dragon Ball Specials                        Special | Ep 2/2
 9: Dragon Ball Z                               Ep 291/291
10: Dragon Ball Z (Dub)                         DUB | Ep 291/291
11: Dragon Ball Super Movie                     Preview
12: Dragon Ball Super (Dub)                     DUB | Ep 74/131
13: Dragon Ball GT                              Ep 64/64
14: Dragon Ball Z Kai (Dub)                     DUB | Ep 98/98
15: Dragon Ball Specials (Dub)                  Special | DUB | Ep 2
16: Dragon Ball Z: Resurrection 'F' (Dub)       DUB | Movie
17: Dragon Ball Z: Resurrection 'F'             Movie
18: Dragon Ball: Episode of Bardock (Dub)       DUB | OVA
19: Dragon Ball: Episode of Bardock             OVA
20: Dragon Ball Z Movie 12: Fusion Reborn       Movie
21: Dragon Ball Z Movie 09: Bojack Unbound (    DUB | Movie
22: Dragon Ball Z Movie 05: Cooler's Revenge    DUB | Movie
23: Dragon Ball Z: Saiya-jin Zetsumetsu Keik    OVA | Ep 2/2
24: Dragon Ball Z Kai: The Final Chapters (D    DUB | Ep 69/69
25: Dragon Ball: Super Saiya-jin Zetsumetsu     DUB | OVA
26: Dragon Ball Z Movie 12: Fusion Reborn (D    DUB | Movie
27: Dragon Ball Special - History of Japan      Special | Ep 02 RAW/
28: Dragon Ball Movie 3: Mystical Adventure     DUB | Movie
29: Dragon Ball Z Movie 05: Cooler's Revenge    Movie
30: Dragon Ball Z Kai: The Final Chapters       Ep 69/69

Enter the anime no:  [1]: 9
INFO root: Selected Dragon Ball Z
INFO root: Extracting episode info from page
DEBUG root: Metadata scraping error: list index out of range
DEBUG root: data-ts: 1533834000
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 9, in <module>
    load_entry_point('anime-downloader==3.4.0', 'console_scripts', 'anime')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader-3.4.0-py3.5.egg/anime_downloader/cli.py", line 99, in dl
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader-3.4.0-py3.5.egg/anime_downloader/sites/anime.py", line 42, in __init__
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader-3.4.0-py3.5.egg/anime_downloader/sites/anime.py", line 60, in get_data
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader-3.4.0-py3.5.egg/anime_downloader/sites/nineanime.py", line 102, in _scarpe_episodes
anime_downloader.sites.exceptions.NotFoundError: ('No episodes found in url "https://www8.9anime.is/watch/dragon-ball-z.51ov"', 'https://www8.9anime.is/watch/dragon-ball-z.51ov')
<details>
<summary>LOG</summary>
```

```
</details>

**Comment by vn-ki** [comment]
Update to 3.4.1 and enjoy. Thanks for the bug report.

**Comment by Alistair1231** [comment]
uuum.... is it my fault, or why do I get now this error? (on win and "ubuntu" btw) 
command:
```
$ sudo anime dl "dragon ball" -ll DEBUG
```  

Output:  
```
INFO root: anime-downloader 3.4.1
DEBUG root: Platform: Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-16.04-xenial
DEBUG root: Python 3.5.2
DEBUG root: https://www8.9anime.is/search?keyword=dragon+ball
DEBUG root: Search results
...
 1: Dragon Ball                                 Ep 153/153
 2: Dragon Ball (Dub)                           Ep 153/153 | DUB
 3: Dragon Ball Super                           Ep 131/131
 4: Dragon Ball Z Kai                           Ep 98/98
 5: Dragon Ball Super Movie (Dub)               Preview | DUB
 6: Dragon Ball Z (Uncrop)                      Ep ?/291
 7: Dragon Ball GT (Dub)                        Ep 64/64 | DUB
 8: Dragon Ball Specials                        Ep 2/2 | Special
 9: Dragon Ball Z                               Ep 291/291
...
Enter the anime no:  [1]: 9
INFO root: Selected Dragon Ball Z
INFO root: Extracting episode info from page
DEBUG root: Metadata scraping error: list index out of range
DEBUG root: data-ts: 1533823200
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/cli.py", line 99, in dl
    fallback_qualities=fallback_qualities)
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/sites/anime.py", line 42, in __init__
    self.get_data()
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/sites/anime.py", line 60, in get_data
    self._episode_urls = self._scarpe_episodes(soup)
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/sites/nineanime.py", line 104, in _scarpe_episodes
    soup = BeautifulSoup(requests.get(api_url).json()['html'], 'html.parser')
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
