### ISSUE TITLE
3.4.1 update produces now another error

### ISSUE THREAD

**Issue by Alistair1231** [vn-ki/anime-downloader#62]
**Describe the bug**
uum hi again! :D 
just updated and now I get a different error... (on win and "ubuntu" btw)

**To reproduce**
```
$ sudo anime dl "dragon ball" -ll DEBUG
```  

```
INFO root: anime-downloader 3.4.1
DEBUG root: Platform: Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-16.04-xenial
DEBUG root: Python 3.5.2
DEBUG root: https://www8.9anime.is/search?keyword=dragon+ball
DEBUG root: Search results
...
 1: Dragon Ball                                 Ep 153/153
 2: Dragon Ball (Dub)                           Ep 153/153 | DUB
 3: Dragon Ball Super                           Ep 131/131
 4: Dragon Ball Z Kai                           Ep 98/98
 5: Dragon Ball Super Movie (Dub)               Preview | DUB
 6: Dragon Ball Z (Uncrop)                      Ep ?/291
 7: Dragon Ball GT (Dub)                        Ep 64/64 | DUB
 8: Dragon Ball Specials                        Ep 2/2 | Special
 9: Dragon Ball Z                               Ep 291/291
...
Enter the anime no:  [1]: 9
INFO root: Selected Dragon Ball Z
INFO root: Extracting episode info from page
DEBUG root: Metadata scraping error: list index out of range
DEBUG root: data-ts: 1533823200
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/cli.py", line 99, in dl
    fallback_qualities=fallback_qualities)
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/sites/anime.py", line 42, in __init__
    self.get_data()
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/sites/anime.py", line 60, in get_data
    self._episode_urls = self._scarpe_episodes(soup)
  File "/usr/local/lib/python3.5/dist-packages/anime_downloader/sites/nineanime.py", line 104, in _scarpe_episodes
    soup = BeautifulSoup(requests.get(api_url).json()['html'], 'html.parser')
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Alistair1231** [comment]
ah. and wooow that was super quick! AWESOME

**Comment by vn-ki** [comment]
I'm sorry. I made a stupid mistake. Update to 3.4.2. :)

**Comment by Alistair1231** [comment]
works perfect now. thanks. :)
and damn you're quick. :D
