### ISSUE TITLE
last one for now? :D 3.4.2 bug if selection not default

### ISSUE THREAD

**Issue by Alistair1231** [vn-ki/anime-downloader#63]
**Describe the bug**
if selection not 1, then error

**To reproduce**

```
PS D:\!!Downloads\!Anime> anime dl "Bravo"
[32manime[0m: anime-downloader 3.4.2
 1: Girls Bravo                                 Ep 11/11
 2: Girls Bravo (Dub)                           DUB | Ep 11/11
 3: Girls Bravo: Second Season                  Ep 13/13
 4: Girls Bravo: Second Season (Dub)            DUB | Ep 13/13

Enter the anime no:  [1]: 3
[32manime[0m: Selected Girls Bravo: Second Season
[32manime[0m: Extracting episode info from page
'NoneType' object has no attribute 'find_all'
PS D:\!!Downloads\!Anime> anime dl "Bravo" -ll DEBUG
INFO root: anime-downloader 3.4.2
DEBUG root: Platform: Windows-10-10.0.17134-SP0
DEBUG root: Python 3.7.0
DEBUG root: https://www8.9anime.is/search?keyword=Bravo
DEBUG root: Search results
DEBUG root: Girls Bravo
DEBUG root: Girls Bravo (Dub)
DEBUG root: Girls Bravo: Second Season
DEBUG root: Girls Bravo: Second Season (Dub)
 1: Girls Bravo                                 Ep 11/11
 2: Girls Bravo (Dub)                           DUB | Ep 11/11
 3: Girls Bravo: Second Season                  Ep 13/13
 4: Girls Bravo: Second Season (Dub)            DUB | Ep 13/13

Enter the anime no:  [1]: 3
INFO root: Selected Girls Bravo: Second Season
INFO root: Extracting episode info from page
DEBUG root: Metadata scraping error: list index out of range
DEBUG root: data-ts: 1533798000
Traceback (most recent call last):
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alistair1231\AppData\Local\Programs\Python\Python37-32\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\cli.py", line 99, in dl
    fallback_qualities=fallback_qualities)
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\anime.py", line 42, in __init__
    self.get_data()
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\anime.py", line 60, in get_data
    self._episode_urls = self._scarpe_episodes(soup)
  File "c:\users\alistair1231\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\nineanime.py", line 106, in _scarpe_episodes
    episodes = episodes.find_all('li')
AttributeError: 'NoneType' object has no attribute 'find_all'
PS D:\!!Downloads\!Anime>
```

w/ def. selection  
```
PS D:\!!Downloads\!Anime> anime dl "Bravo" -ll DEBUG
INFO root: anime-downloader 3.4.2
DEBUG root: Platform: Windows-10-10.0.17134-SP0
DEBUG root: Python 3.7.0
DEBUG root: https://www8.9anime.is/search?keyword=Bravo
DEBUG root: Search results
DEBUG root: Girls Bravo
DEBUG root: Girls Bravo (Dub)
DEBUG root: Girls Bravo: Second Season
DEBUG root: Girls Bravo: Second Season (Dub)
 1: Girls Bravo                                 Ep 11/11
 2: Girls Bravo (Dub)                           DUB | Ep 11/11
 3: Girls Bravo: Second Season                  Ep 13/13
 4: Girls Bravo: Second Season (Dub)            DUB | Ep 13/13

Enter the anime no:  [1]:
INFO root: Selected Girls Bravo
INFO root: Extracting episode info from page
DEBUG root: Metadata scraping error: list index out of range
DEBUG root: data-ts: 1533798000
DEBUG root: EPISODE IDS: length: 11, ids: ['w0ly87', 'w0lyn7', 'j8x663', '84o73y', 'z6o2nm', 'qp423w', 'po92ox', 'ml0457', 'po92qx', '57lyjv', '045y89']
INFO root: Found anime: Girls Bravo
INFO root: Downloading to D:\!!Downloads\!Anime
DEBUG root: Extracting stream info of id: w0ly87
DEBUG root: API call URL: https://9anime.is/ajax/episode/info with params {'id': 'w0ly87', 'server': '33', 'ts': '1533798000', '_': 777}
DEBUG root: URL: https://www8.9anime.is/ajax/episode/info?id=w0ly87&server=33&ts=1533798000&_=777
DEBUG root: Returned data: {'grabber': 'https://www8.9anime.is/grabber-api/?server=33', 'params': [], 'backup': 0, 'target': 'https://www.rapidvideo.com/e/FU3FEOMPV4', 'type': 'iframe', 'name': '01', 'subtitle': ''}
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FU3FEOMPV4&q=1080p
INFO root: Downloading episode 1 of Girls Bravo
DEBUG root: cmd: {aria2}
DEBUG root: episode: <anime_downloader.sites.nineanime.NineAnimeEpisode object at 0x045D0770>
DEBUG root: file format: {anime_title}_{ep_no}
DEBUG root: formatted cmd: aria2c https://www2372.playercdn.net/173/0/ZwVqu8kxIVfxX3UPOabTJg/1533865440/180809/aRYO58qFajOlpkX.mp4 -x 12 -s 12 -j 12 -k 10M -o Girls_Bravo_1.mp4 --continue=true --dir=D:\!!Downloads\!Anime --stream-piece-selector=inorder --min-split-size=5M

08/09 21:44:00 [NOTICE] Downloading 1 item(s)

Aborted!
```

**Comment by vn-ki** [comment]
Can you try this again? 9anime has some problems with rapidvideo that they are trying to fix. I think you encountered this because of that. It seems to be working now.

**Comment by vn-ki** [comment]
I'm assuming this is fixed and will close this issue now.
