### ISSUE TITLE
Error when trying to download or watch

### ISSUE THREAD

**Issue by Eren4363** [vn-ki/anime-downloader#64]
When trying to download or watch anything, I get the error below. I'm on Mac OS 10.13.6 and python 3.7 installed via homebrew

**To reproduce**

```
$ anime dl "violet evergarden" -ll DEBUG
```
<details>
<summary>LOG</summary>

```
INFO root: anime-downloader 3.4.2
DEBUG root: Platform: Darwin-17.7.0-x86_64-i386-64bit
DEBUG root: Python 3.7.0
DEBUG root: https://www8.9anime.is/search?keyword=violet+evergarden
DEBUG root: Search results
DEBUG root: Violet Evergarden
DEBUG root: Violet Evergarden (Dub)
DEBUG root: Violet Evergarden Movie
DEBUG root: Violet Evergarden Special
 1: Violet Evergarden                       	Ep 13/13            
 2: Violet Evergarden (Dub)                 	DUB | Ep 13/13      
 3: Violet Evergarden Movie                 	Preview             
 4: Violet Evergarden Special               	Special             

Enter the anime no:  [1]: 1
INFO root: Selected Violet Evergarden
INFO root: Extracting episode info from page
DEBUG root: Metadata scraping error: list index out of range
DEBUG root: data-ts: 1534503600
DEBUG root: EPISODE IDS: length: 13, ids: ['kj5lqr', '79qlm8', 'y0zrqj', 'kj57wr', '57ojkm', 'onm7xj', '44n02m', 'qpojzn', '64pk07', 'w0xpw6', '94vn1x', 'z69v52', 'lkj7nz']
INFO root: Found anime: Violet Evergarden
INFO root: Downloading to /Users/erendogan
DEBUG root: Extracting stream info of id: kj5lqr
DEBUG root: API call URL: https://9anime.is/ajax/episode/info with params {'id': 'kj5lqr', 'server': '33', 'ts': '1534503600', '_': 777}
DEBUG root: URL: https://www8.9anime.is/ajax/episode/info?id=kj5lqr&server=33&ts=1534503600&_=777
DEBUG root: Returned data: {'grabber': 'https://www8.9anime.is/grabber-api/?server=33', 'params': [], 'backup': 0, 'target': 'https://www.rapidvideo.com/e/FU222WKMTB', 'type': 'iframe', 'name': '01', 'subtitle': ''}
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FU222WKMTB&q=720p
WARNING root: Quality 720p not found. Trying 480p.
DEBUG root: API call URL: https://9anime.is/ajax/episode/info with params {'id': 'kj5lqr', 'server': '33', 'ts': '1534503600', '_': 777}
DEBUG root: URL: https://www8.9anime.is/ajax/episode/info?id=kj5lqr&server=33&ts=1534503600&_=777
DEBUG root: Returned data: {'grabber': 'https://www8.9anime.is/grabber-api/?server=33', 'params': [], 'backup': 0, 'target': 'https://www.rapidvideo.com/e/FU222WKMTB', 'type': 'iframe', 'name': '01', 'subtitle': ''}
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FU222WKMTB&q=480p
WARNING root: Quality 480p not found. Trying 360p.
DEBUG root: API call URL: https://9anime.is/ajax/episode/info with params {'id': 'kj5lqr', 'server': '33', 'ts': '1534503600', '_': 777}
DEBUG root: URL: https://www8.9anime.is/ajax/episode/info?id=kj5lqr&server=33&ts=1534503600&_=777
DEBUG root: Returned data: {'grabber': 'https://www8.9anime.is/grabber-api/?server=33', 'params': [], 'backup': 0, 'target': 'https://www.rapidvideo.com/e/FU222WKMTB', 'type': 'iframe', 'name': '01', 'subtitle': ''}
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FU222WKMTB&q=360p
INFO root: Downloading Violet Evergarden-1
INFO root: ./Violet_Evergarden/Violet_Evergarden_1.mp4
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FU222WKMTB&q=360p
Traceback (most recent call last):
  File "/usr/local/bin/anime", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/cli.py", line 146, in dl
    range_size=chunk_size)
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/sites/anime.py", line 182, in download
    path, force, range_size=range_size)
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/downloader/base_downloader.py", line 14, in __init__
    self.url = source.stream_url
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/extractors/base_extractor.py", line 26, in stream_url
    self.get_data()
  File "/usr/local/lib/python3.7/site-packages/anime_downloader/extractors/base_extractor.py", line 41, in get_data
    raise NotFoundError
anime_downloader.sites.exceptions.NotFoundError
```

**Comment by vn-ki** [comment]
Please update to 3.4.3. It should work.
