### ISSUE TITLE
Error on version 3.4.5 

### ISSUE THREAD

**Issue by Jtgroos** [vn-ki/anime-downloader#69]
Hi just got back from holliday and downloaded the newst version but i cant. watch nor download anime atm.

**C:\Users\joey>anime watch --new**
[32manime[0m: anime-downloader 3.4.5
Enter a anime name or url: Chrome
 1: Chrome Shelled Regios                       Ep 24/24
 2: Chrome Shelled Regios (Dub)                 DUB | Ep 24/24

Enter the anime no:  [1]: 1
[32manime[0m: Selected Chrome Shelled Regios
[32manime[0m: Extracting episode info from page
Traceback (most recent call last):
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\joey\AppData\Local\Programs\Python\Python36-32\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\site-packages\anime_downloader\cli.py", line 207, in watch
    watcher.new(url)
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\site-packages\anime_downloader\watch.py", line 26, in new
    anime = AnimeInfo(url, timestamp=time())
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\site-packages\anime_downloader\watch.py", line 141, in __init__
    super(cls, self).__init__(*args, **kwargs)
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\site-packages\anime_downloader\sites\anime.py", line 42, in __init__
    self.get_data()
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\site-packages\anime_downloader\sites\anime.py", line 60, in get_data
    self._episode_urls = self._scarpe_episodes(soup)
  File "c:\users\joey\appdata\local\programs\python\python36-32\lib\site-packages\anime_downloader\sites\nineanime.py", line 107, in _scarpe_episodes
    soup = BeautifulSoup(requests.get(api_url,params=params).json()['html'], 'html.parser')
KeyError: 'html'

**C:\Users\joey>anime dl chrome**
[32manime[0m: anime-downloader 3.4.5
 1: Chrome Shelled Regios                       Ep 24/24
 2: Chrome Shelled Regios (Dub)                 DUB | Ep 24/24

Enter the anime no:  [1]: 1
[32manime[0m: Selected Chrome Shelled Regios
[32manime[0m: Extracting episode info from page
'html'

Maybe you are already working on this but just to be sure
thanks in advanced

**Comment by ngomile** [comment]
Try using a different provider like kissanime. I experienced the same thing but right now I'm exhausted to find out what it is.

**Comment by vn-ki** [comment]
9anime implemented recaptcha for their ajax requests. It will be sometime before 9anime works again.

I am not sure how to tackle the issue as of now.

**Comment by Jtgroos** [comment]
ah ok.. i will use kissanime for now and wait for the update

**Comment by BlackXDragon** [comment]
How do I use kissanime in the command?

**Comment by vn-ki** [comment]
https://github.com/vn-ki/anime-downloader/wiki/dl-command#search-and-download

> To search on kissanime,
```
anime dl 'code geass' --provider kissanime
```

From `anime dl --help`,

```
  --provider [9anime|kissanime|twist.moe|animepahe|kisscartoon]                                               
                                  The anime provider (website) for search.
```

**Comment by vn-ki** [comment]
This has been fixed.
