### ISSUE TITLE
html problem {I think}

### ISSUE THREAD

**Issue by Ahmad-Gangester** [vn-ki/anime-downloader#83]
**Describe the bug**

When I Try to download from 9anime I think the downloader can't get the video URL 
all I get is : 
```
[32manime[0m: anime-downloader 3.5.0
[32manime[0m: Extracting episode info from page
{'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0', 'referer': 'https://www1.9anime.to/watch/bleach.6j9/n5mv8j'}
{'valid': True} https://www1.9anime.to/ajax/film/servers-ping?ts=1538146800&_=632
'html'

```

**To reproduce**

```
anime dl 'https://www1.9anime.to/watch/bleach.6j9/n5mv8j' --episodes 1:366

```

<details>
<summary>LOG</summary>
```

INFO root: anime-downloader 3.5.0
DEBUG root: Platform: Windows-10-10.0.17134-SP0
DEBUG root: Python 3.7.0
INFO root: Extracting episode info from page
DEBUG root: data-ts: 1538146800
{'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/56.0', 'referer': 'https://www1.9anime.to/watch/bleach.6j9/n5mv8j'}
{'valid': True} https://www1.9anime.to/ajax/film/servers-ping?ts=1538146800&_=632
Traceback (most recent call last):
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python37-32\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\cli.py", line 99, in dl
    fallback_qualities=fallback_qualities)
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\anime.py", line 42, in __init__
    self.get_data()
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\anime.py", line 60, in get_data
    self._episode_urls = self._scarpe_episodes(soup)
  File "c:\users\ahmad\appdata\local\programs\python\python37-32\lib\site-packages\anime_downloader\sites\nineanime.py", line 112, in _scarpe_episodes
    soup = BeautifulSoup(requests.get(api_url,params=params, headers=headers).json()['html'], 'html.parser')
KeyError: 'html'

```
</details>

**Comment by vn-ki** [comment]
I think 3.6.1 might have solved this issue.

9anime is too messed up to work anyway. So closing.
