### ISSUE TITLE
When attempting to download from twist.moe, I get "No module named 'Crypto'" error

### ISSUE THREAD

**Issue by cooler9711** [vn-ki/anime-downloader#84]
**Describe the bug**
When I try to download an anime from twist.moe, I get a module not found error
I've also tried to download Crypto from pip, but even then, I still get the same error

**To reproduce**

```
anime dl "Dagashi Kashi" --provider twist.moe
```

<details>
<summary>LOG</summary>

> anime dl "Dagashi Kashi" --provider twist.moe --log-level DEBUG
INFO root: anime-downloader 3.5.0
DEBUG root: Platform: Linux-4.18.10-arch1-1-ARCH-x86_64-with-arch
DEBUG root: Python 3.7.0
Traceback (most recent call last):
  File "/usr/bin/anime", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/anime_downloader/cli.py", line 94, in dl
    anime_url = util.search(anime_url, provider)
  File "/usr/lib/python3.7/site-packages/anime_downloader/util.py", line 51, in search
    cls = get_anime_class(provider)
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/init.py", line 21, in get_anime_class
    'anime_downloader.sites.{}'.format(site[0])
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/twistmoe.py", line 1, in <module>
    from Crypto import Random
ModuleNotFoundError: No module named 'Crypto'

</details>

**Comment by ngomile** [comment]
Crypto is not installed and it's last release was in 2013. To put it short, it is not included with the downloader. Even though the twist extractor is built with it in mind for some reason.

**Comment by vn-ki** [comment]
```
pip install pycrypto
```
should fix it.

Seems like I didn't add it into the requirements.

**Comment by cooler9711** [comment]
that worked for the Crypto part

now i'm getting a different error

<details>
<summary>LOG</summary>

anime dl "Dagashi Kashi" --provider twist.moe --log-level DEBUG
INFO root: anime-downloader 3.5.0
DEBUG root: Platform: Linux-4.18.10-arch1-1-ARCH-x86_64-with-arch-Arch-Linux
DEBUG root: Python 3.7.0
Traceback (most recent call last):
  File "/usr/bin/anime", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/anime_downloader/cli.py", line 94, in dl
    anime_url = util.search(anime_url, provider)
  File "/usr/lib/python3.7/site-packages/anime_downloader/util.py", line 51, in search
    cls = get_anime_class(provider)
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/init.py", line 21, in get_anime_class
    'anime_downloader.sites.{}'.format(site[0])
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.7/site-packages/anime_downloader/sites/twistmoe.py", line 6, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python3.7/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3.7/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python3.7/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'

</detail>

**Comment by vn-ki** [comment]
Try reinstalling or installing inside a virtual env. This is probably caused by a different version of html5lib than needed.

**Comment by cooler9711** [comment]
how would i create a virtual env?

**Comment by cooler9711** [comment]
i was able to fix it. i needed to downgrade html5lib by doing `pip install --upgrade html5lib==1.0b8`. thanks for your help!

**Comment by danielb2** [comment]
Also ran into `No module named 'Crypto'`

Seems like it should be part of the pip description or some such (no idea how python tracks dependencies)
