### ISSUE TITLE
A bug (i think :)

### ISSUE THREAD

**Issue by Nerozin** [vn-ki/anime-downloader#98]
**Ok this is a weird bug, about 2 days ago i reinstalled anime-downloader after not using it for some time and at first it was working nicely. However today i started up my pc started the downloader and started downloading detective conan episodes from masterani.me using this:
anime dl -e 780:917 -q 480p https://www.masterani.me/anime/info/673-detective-conan
and is was working for a while when suddenly upon reaching episode 786 it stopped and showed this error:

anime dl -e 786:917 -q 480p https://www.masterani.me/anime/info/673-detective-conan
anime: anime-downloader 3.5.0
anime: Extracting episode info from page
anime: Found anime: Detective Conan
anime: Downloading to O:\Animes
Traceback (most recent call last):
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\NCS\AppData\Local\Programs\Python\Python37\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\cli.py", line 125, in dl
    for episode in anime:
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 78, in __getitem__
    ep_no=ep_id[0])
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 124, in __init__
    self.source().stream_url
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 26, in stream_url
    self.get_data()
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 38, in get_data
    data = self._get_data()
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\extractors\mp4upload.py", line 22, in _get_data
    domain, video_id, protocol = source_parts_re.match(mp4u_embed).groups()
AttributeError: 'NoneType' object has no attribute 'groups

And worse part is no matter which episode i choose or which server i choose or which series i choose it always returns with the same error**

**To reproduce**

```
Well i don't know if this will reproduce it but i guess you can try this:
anime dl -e 780:917 -q 480p https://www.masterani.me/anime/info/673-detective-conan
```

<details>
<summary>LOG</summary>

```
Is this the debug output cause i'm not sure:
INFO root: anime-downloader 3.5.0
DEBUG root: Platform: Windows-7-6.1.7601-SP1
DEBUG root: Python 3.7.0
INFO root: Extracting episode info from page
INFO root: Found anime: Detective Conan
INFO root: Downloading to O:\Animes
DEBUG root: Extracting stream info of id: https://www.masterani.me/anime/watch/673-detective-conan/810
DEBUG root: [cfscrape] Calling https://www.masterani.me/anime/watch/673-detective-conan/810
DEBUG root: Found sources [{'id': 379463, 'host_id': 1, 'embed_id': 'tobzmwbwce9t', 'quality': 720, 'type': 1, 'host': {'id': 1, 'name': 'MP4Upload', 'embed_prefix': 'https://mp4upload.com/embed-', 'embed_suffix': '.html'}}, {'id': 381536, 'host_id': 15, 'embed_id': 'k3zNcKCiIEg', 'quality': 720, 'type': 1, 'host': {'id': 15, 'name': 'Openload', 'embed_prefix': 'https://openload.co/embed/', 'embed_suffix': None}}, {'id': 379102, 'host_id': 1, 'embed_id': 'tk0d12oql4qt', 'quality': 480, 'type': 1, 'host': {'id': 1, 'name': 'MP4Upload', 'embed_prefix': 'https://mp4upload.com/embed-', 'embed_suffix': '.html'}}, {'id': 380487, 'host_id': 15, 'embed_id': 'qptz8-N_A3A', 'quality': 480, 'type': 1, 'host': {'id': 15, 'name': 'Openload', 'embed_prefix': 'https://openload.co/embed/', 'embed_suffix': None}}]. filtering...
DEBUG root: [('mp4upload', 'https://mp4upload.com/embed-tk0d12oql4qt.html')]
DEBUG root: Sources :
Traceback (most recent call last):
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\NCS\AppData\Local\Programs\Python\Python37\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\cli.py", line 125, in dl
    for episode in anime:
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 78, in __getitem__
    ep_no=ep_id[0])
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\sites\anime.py", line 124, in __init__
    self.source().stream_url
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 26, in stream_url
    self.get_data()
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\extractors\base_extractor.py", line 38, in get_data
    data = self._get_data()
  File "c:\users\ncs\appdata\local\programs\python\python37\lib\site-packages\anime_downloader\extractors\mp4upload.py", line 22, in _get_data
    domain, video_id, protocol = source_parts_re.match(mp4u_embed).groups()
AttributeError: 'NoneType' object has no attribute 'groups'


```

**Comment by Nerozin** [comment]
> This pull request #96 fixes this problem. Basically the regular expression to collect from mp4upload was a little wonky but this fixes it right up.

ok so what do i have to do to fix my issue ?
sorry i'm kinda new to all these.

**Comment by freddiaN** [comment]
you either wait for the next release with all the features added and Bugfixes since 3.5.0 or you run `sudo pip install -U git+https://github.com/vn-ki/anime-downloader.git#egg=anime-downloader[cloudflare]` to get the latest version from the repo's master branch

**Comment by freddiaN** [comment]
1. fuzzy finding works for masterani now, so you should be able to just give it search terms as 1 string and add `--provider masterani` to the command

2. please re-run those commands with `-ll DEBUG` and also wait a while. some shows seem to take longer to actually load (both the information and the actual downloading of the file).

3. why just 480p? o.O

**Comment by freddiaN** [comment]
alright I just ran the detective conan one and it seems like it does find all the correct information (pasting the `Stream URL` into my browser directly prompted me to download that episode) but it just doesn't seem to start the download(???), I had to wait until ep804 until it actually started downloading

**Comment by freddiaN** [comment]
@Nerozin I think you typed 11 instead of ll (L lowercase)

**Comment by Nerozin** [comment]
> @Nerozin I think you typed 11 instead of ll (2 lowercase L, meaning "log level")

Yeah got that later hehehe
